### ISSUE TITLE
Site Navigation

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#1]
The curation interfaces should have some sort of global navigation

**Comment by kilodalton** [comment]
@tsneddon @selinad If you have some specific actions/pages that a curator might want to go to from any point in the process please include lists  and/or screenshots in a comment here.

**Comment by tsneddon** [comment]
Hi Karen:

For version 0.5 we just need to link to the Dashboard as this page is where we put:

* curation history
* creating/viewing records

There should probably be a link to logout as well.

So, either:

Dashboard | Logout

or 

Dashboard | Account | Logout

Thanks,

Tam

**Comment by forresttanaka** [comment]
Is it proper to say that the large white navigation area in the header isn’t needed at all? Just Dashboard | Account | Logout at the top? That the dashboard page should be the only place that we have a link to the View/Create Gene Disease Record page?

If that’s the case, would you prefer to see Dashboard… etc in the blue menu and have no white menu, or everything in the white menu and have no blue menu? The white menu allows more space because on mobile it goes behind a hamburger button. The blue menu sticks around no matter what device you view it on.

**Comment by forresttanaka** [comment]
[Sorry if you get a notification about this multiple times, but I tried to post while on the Dumbarton Bridge where poor signal makes things…interesting. I’ll try again from memory]

Is it safe to say we don’t need both the white navigation and the blue navigation in the header? That Dashboard | Account | Logout is all we need? And that the only way to get to the View/Create Gene Disease page is from the Dashboard page?

If so, would you prefer everything in the blue menu or the white one? The white one has the advantage that we can add things to it more easily because on mobile it goes behind a hamburger menu. The blue one sticks around no matter what you view it on, so Dashboard | Account | Logout is probably all that will fit, and even that will be pretty tight on mobile.

**Comment by selinad** [comment]
I think it's safe to say all links will come off of the Dashboard, so we won't really need a navigation menu for curation (Tam, let me know if you disagree)...are we planning on implementing the Dashboard for 0.5?  If so, do we need a ticket?

I think the blue is fine, but maybe Tam has other thoughts; or if you feel like it should go on the white, that works too.  I don't suspect there will be a ton of curation on phones...too hard to read papers, etc.  I suppose someone could want to review the summary or something, however.

**Comment by tsneddon** [comment]
No other thoughts, whatever works best is OK with me.

**Comment by selinad** [comment]
Per our discussions this AM:

We will put a home icon next to "Account" and login status in the blue menu bar.  This will link to Home for gene curation (aka Dashboard).

Forrest will keep the white menu bar code for future use, but will not display this menu bar now. 

Re ClinGen icon - this should not link to Home for the gene curation App - since we do not need/want to link to clinicalgenome.org and it seems like it is in a place where it would link back to gene curation Home, let's have it NOT link anywhere for now until we have new logo.

**Comment by kilodalton** [comment]
This item has been addressed in several other subsequent tickets in terms of navigating through the site. Closing.
