### ISSUE TITLE
Change text from 'Modify/Modified' to 'Alter/Altered' in Summary page of VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1009]
A couple of text changes are required on the Summary page:

Change ‘Modify Pathogenicity (optional)’ to ‘Alter Pathogenicity (optional)’
Change ‘Modified Pathogenicity’ to ‘Altered Pathogenicity’

**Comment by selinad** [comment]
thx @wrightmw - we had a brief pow-wow after meeting and decided to leave as 'Modified.'  This is because modified is an adjective for either the strength being modified or the pathogenicity being modified (as opposed to the same word being used for a noun representing 2 different things).  We also thought "Modified" is closer to real meaning we want to convey...closing for now
