### ISSUE TITLE
Bug in deleting PMID evidence added in VCI

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1030]
bug found in testing #983 

@mrmin123 - was working great (love this feature!) until I tried to delete:
<img width="1436" alt="screen shot 2016-09-29 at 10 30 45 pm" src="https://cloud.githubusercontent.com/assets/11320314/18981604/b3c716a2-8694-11e6-96d3-c7fdb1fa23d2.png">

**Comment by mrmin123** [comment]
@selinad I can't reproduce this... what were the exact steps?

**Comment by selinad** [comment]
@mrmin123 I think I added 3 pieces of evidence, 2 with same PMID, then tried to delete.  I believe I did an edit in-between as well and maybe a cancel...

**Comment by mrmin123** [comment]
@selinad Ah, figured it out. It's because it's from a non-admin account, I believe. This is a bug.

**Comment by selinad** [comment]
I tried it again and had same problem - did an edit on one before trying to delete it.  Also, tried entering only 1 PMID , added evidence, edited evidence and tried to delete and got same...
<img width="1419" alt="screen shot 2016-09-29 at 11 11 35 pm" src="https://cloud.githubusercontent.com/assets/11320314/18982329/1d0a9314-869a-11e6-9c24-3d994038ee24.png">

**Comment by selinad** [comment]
that is one selective bug! 🐛

**Comment by mrmin123** [comment]
OK. Fixed.

**Comment by wrightmw** [comment]
This works well for me now. I can delete. Thanks for the fix @mrmin123

**Comment by selinad** [comment]
I could delete all but one thing - I think I edited this one first and couldn't delete, but then I could edit others and delete them...

![screen shot 2016-09-30 at 4 06 58 pm](https://cloud.githubusercontent.com/assets/11320314/19009367/05dbbf18-8728-11e6-9571-88410f626031.png)

**Comment by selinad** [comment]
@mrmin123 sleuthed this out - it was an issue caused by the slow network - basically the objecthad already been deleted, thus denying me access ( @mrmin123 please feel free to edit explanation).  This general issue is a known issue.

**Comment by mrmin123** [comment]
As @selinad pointed out this issue was primarily caused by the slow network, although exacerbated by the way we handle chained events such as deletes. In this particular scenario, the extra evidence object had been deleted but the edit action for the updated interpretation object (which has the link to the deleted extra evidence object removed) failed due to network error. Thus, the item showed up on the interface, but the user no longer had permission to delete the object.

Possible fixes include:

* Offload chained actions (only deletes right now?) to the backend
* Make it so that deleted items do not get embedded in parent objects, and/or make it so that deleted objects can be modified by the owner (I don't remember the latter being possible at all... not sure about the former... then again, if the latter doesn't work the former might still cause issues)

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
