### ISSUE TITLE
Patch to allow unlimited digits for CA ID

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1098]
A user wrote in that they are not able to retrieve info using a CA ID - this CA ID has more than 6 digits and  it turns out we have set the limit to be 6.

We need to create a patch asap that allows for unlimited digits for the CA ID.  thx!

**Comment by kgliu0101** [comment]
Found the bug in function `carValidateForm()` in file `/src/clincoded/static/components/add_external_resource.js`, limited by 6 digits in CA id. It's fixed by removing the limit in number of digit.

![screen shot 2016-10-27 at 11 18 59 am](https://cloud.githubusercontent.com/assets/9206696/19779815/91e24e0e-9c37-11e6-9c19-ec2fe7aae08e.png)

**Comment by kgliu0101** [comment]
And another one @selinad just registered this morning.
![screen shot 2016-10-27 at 11 27 35 am](https://cloud.githubusercontent.com/assets/9206696/19780028/7cc575e0-9c38-11e6-9340-9c08eb669eb0.png)

**Comment by selinad** [comment]
that's excellent @kgliu0101 - thank you!

**Comment by selinad** [comment]
I tested the 2 above on the instance and they worked perfectly.  Plus an older one already registered.  Nice work - thx!

**Comment by selinad** [comment]
Both long CA IDs work well!

**Comment by wrightmw** [comment]
Fixed...works for long CA IDs now! Great.

**Comment by kilodalton** [comment]
Included in last release (R8). Nice job and thanks for your hard work.
