### ISSUE TITLE
Add more descriptive text to Highest MAF section for user clarity

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1106]
We need to make it clearer to user what Highest MAF means:

@wrightmw - please edit:

This reflects the highest MAF observed, as calculated by the interface, across all subpopulations of ExAC, 1000 Genomes and ESP for the current data"

**Comment by wrightmw** [comment]
@selinad I think this looks good, except I'm not sure we should say "current data" because it's based on the versions of ExAC, 1000 Genomes and ESP in the interface which may not be the most current (because there will be a short lag from when new versions are released to when they are incorporated into MyVariant.info)....so maybe we should say something like?:
"This reflects the highest MAF observed, as calculated by the interface, across all subpopulations in the versions of ExAC, 1000 Genomes and ESP shown below"

**Comment by selinad** [comment]
Ah good point - thanks for that reminder.  Bringing in the version seems even more critical.

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

Please review the requested changes in the following instance:
https://1450-jz-revel.demo.clinicalgenome.org/

**Comment by selinad** [comment]
Looks great @jimmyzhen !  Super small detail -- add comma before "and ESP..." so it reads "...1000 Genomes, and ESP shown below"

**Comment by wrightmw** [comment]
@jimmyzhen This looks good.

**Comment by selinad** [comment]
Looks great!
