### ISSUE TITLE
Return version of gnomAD and ExAC

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1107]
Would it be possible to return the version of ExAC, 1000G and ESP on the page via myvariant.info?  Curators would like to see this.

If not, we can add a noter that basically says the data is what is currently presented in these external resources (or something similar)

**Comment by wrightmw** [comment]
MyVariant.info show version numbers in http://myvariant.info/v1/metadata (e.g. ExAC is currently version 0.3.1)

**Comment by selinad** [comment]
@wrightmw @jimmyzhen would this be reasonable to do for R15 alongside gnomAD data?

**Comment by wrightmw** [comment]
Links to #1523

**Comment by wrightmw** [comment]
@selinad @jimmyzhen 

MyVariant.info show version numbers in http://myvariant.info/v1/metadata 

1. They don't currently included gnomAD, I have written to them to ask them to include it. 

2. The _in silico_ predictors could just be included under the dbNSFP version number. 

3. MyVariant.info includes ClinVar versioning

3. 1KG version will need to be obtained from Ensembl

**Comment by selinad** [comment]
thx so much for all of this info, @wrightmw !

**Comment by selinad** [comment]
Also, when someone evaluates something with this data and we store it as a "blob," this information should also be stored in the blob

**Comment by jimmyzhen** [comment]
Hi @gcheung-SF,

I think this may be a good task for you to tackle for the next few days and to become more familiar with the VCI.

Please feel free to chat with me and/or @wrightmw about this. Thank you!

**Comment by jimmyzhen** [comment]
@gcheung-SF,

The **blob** mentioned above refers to a JSON object used to store the population data pertinent to a given variant when the user saves an evaluation on the **Population** tab in the VCI.

The JSON object is actually a linked object defined in the following schema:
https://github.com/ClinGen/clincoded/blob/dev/src/clincoded/schemas/evaluation.json#L25-L30
https://github.com/ClinGen/clincoded/blob/dev/src/clincoded/schemas/population.json

Below is an example of what the JSON data of a typical evaluation looks like:
https://curation-test.clinicalgenome.org/evaluations/294446fd-eeb2-4d98-8feb-dd635a62bc4d/?format=json

Note that the `populationData` object (the **blob**) in the tree. It consists of `gnomAD`, `exac`, `esp` and `tGenomes` children objects in which various population data is stored.

The requested changes in this ticket, if I am not misinterpreting, will be:
1. Display the versions of the external data sources in the UI (e.g. various table/panels in the **Population** tab in the VCI.
2. Store the versions along with each individual children objects in the `populationData` object.

@wrightmw, did I miss anything here?

**Comment by jimmyzhen** [comment]
Hi @gcheung-SF,

I briefly took a look at your code so far. Below are my thoughts:
1. The following metadata request and its subsequent data handling can be potentially decoupled from the `fetchMyVariantInfo()` function (e.g. https://github.com/ClinGen/clincoded/blob/7f9b77e385657bd490034751e6ac374b25e1eb31/src/clincoded/static/components/variant_central/index.js#L227-L231). It can be a function of its own since it does not require the use of variant data.
2. The following `setState` seems unnecessary (e.g. https://github.com/ClinGen/clincoded/blob/7f9b77e385657bd490034751e6ac374b25e1eb31/src/clincoded/static/components/variant_central/interpretation/population.js#L145, https://github.com/ClinGen/clincoded/blob/7f9b77e385657bd490034751e6ac374b25e1eb31/src/clincoded/static/components/variant_central/interpretation/population.js#L196).
3. I am not sure whether this is preferable (e.g. https://github.com/ClinGen/clincoded/blob/7f9b77e385657bd490034751e6ac374b25e1eb31/src/clincoded/static/components/variant_central/interpretation/population.js#L968-L970).
4. I probably prefer to change this line (e.g. https://github.com/ClinGen/clincoded/blob/7f9b77e385657bd490034751e6ac374b25e1eb31/src/clincoded/static/components/variant_central/interpretation/population.js#L975) to something like: `{version ? <span>Version: {version}</span> : null}`
5. You may want to confirm with @wrightmw on this - does it make sense to display the version number in the event when there is no `gnomAD` and/or `ExAC` population data being returned?
6. You may want to coordinate with @markmandell on this - Mark is currently working on allowing `gnomAD` and `ExAC` population data to be displayed for `Indel` variants (in addition to `single nucleotide`). As a result, the `singleNucleotide` condition at https://github.com/ClinGen/clincoded/blob/7f9b77e385657bd490034751e6ac374b25e1eb31/src/clincoded/static/components/variant_central/interpretation/population.js#L961 can be problematic for rendering the version if the variant in question happens to be a `deletion` or `insertion`.

Please feel free to let me know if you have any questions on the above.

**Comment by wrightmw** [comment]
@jimmyzhen @gcheung-SF 
In answer to point 5. Yes, it does make sense to show the version number even if there is no data returned. In essence we are stating that in that specific version number of gnomAD and/or ExAC there is no allele frequency data for that variant. In future versions there may be data for that variant.

**Comment by wrightmw** [comment]
Once we show versioning, we should add a note reminding people to check whether there is a newer version available at the orginal source (e.g gnomAD).

**Comment by gcheung-SF** [comment]
@wrightmw , 
I can work on adding that if you can show me where to add it.  Thanks!

**Comment by gcheung-SF** [comment]
@wrightmw ,
My change to display the version on the population tab is ready for review.  Please try it out on https://gctest.demo.clinicalgenome.org and let me know if there's any issues.  Thanks!

**Comment by wrightmw** [comment]
Thanks @gcheung-SF ...looks great

**Comment by gcheung-SF** [comment]
@bryanwulf, 
Please review the PR - https://github.com/ClinGen/clincoded/pull/1860.
Test site - https://gctest.demo.clinicalgenome.org/variant-central/?variant=ca55d9fe-3ccf-40b1-ae25-bb63fc5d23a3&tab=population

Thanks.

**Comment by bryanwulf** [comment]
@wrightmw It looks like version information doesn't appear when there's no population data:
https://gctest.demo.clinicalgenome.org/variant-central/?variant=79444ab6-d275-4b33-ab44-5ce82bfbbc81&interpretation=70dd3912-b6cd-4f6a-8b53-765329c3fec6&tab=population

Does this need to be fixed for this release?

**Comment by wrightmw** [comment]
Looks great! Thanks @gcheung-SF

**Comment by cgpreston** [comment]
Tested with 139214: See gnomAD/ExAC version listed (as expected, variant in both).
Tested with 41231, see gnomAD/ExAC version listed (as expected, variant NOT in either)
Tested with 25342, see gnomAD/ExAC version listed (as expected, variant in gnomAD, not in ExAC)
Tested with CA352991, see gnomAD/ExaC version listed (as expected, variant too large to return data for either) -

**Comment by wrightmw** [comment]
In R25 release

**Comment by wrightmw** [comment]
R29 testing: Looks great!

**Comment by wrightmw** [comment]
In R29 release.
