### ISSUE TITLE
Add ability to add PMID evidence to each criteria or criteria set

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1109]
Curators would like to be able to add evidence from a PMID (and eventually other sources - will be different ticket) for all criteria or criteria sets (e.g. for each Evaluation Save).  This is how it is on the Segregation/Case tab now.  This includes all evaluations on all tabs with evaluations.

**Comment by wrightmw** [comment]
@selinad Yeah, this is exactly what I heard too. They want the functionality of adding evidence via a PMID to be expanded beyond Segregation/Case and Experimental so that it would be available for all criteria, e.g. if there was evidence in a paper about allele frequency for a subpopulation not found in ExAC, 1000G or ESP then the curator could add the PMID to the relevant Population criteria.

**Comment by wrightmw** [comment]
As per my comment in #1161.. this looks great!

**Comment by selinad** [comment]
I just realized we did not put this in "Reputable Source" under segregation -- @wrightmw was this what they wanted or did we just miss it?  I think we were only going to consider a few sources reputable, so might be ok for now.

Adding to needs work but will not make new ticket until we've discussed.

**Comment by wrightmw** [comment]
@selinad I think this is how they wanted it, for now.  I think only the SCRP BRCA1/BRCA2 data currently falls within the remit of 'reputable source' but it has yet to be properly defined.

**Comment by selinad** [comment]
Great -- thx @wrightmw.  Can be moved to Release Ready then!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
