### ISSUE TITLE
"New Variant Curation" button does not work on Summary page

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1129]
When on Summary page if I click the "New Variant Curation" button in the header, I get the following error message:
![screen shot 2016-11-04 at 2 36 45 pm](https://cloud.githubusercontent.com/assets/15131169/20023299/6f6d8cd8-a29c-11e6-9302-88f57f5f9059.png)

**Comment by kgliu0101** [comment]
@wrightmw 

Would you please specify steps and data entered to get the bug?

**Comment by wrightmw** [comment]
@kgliu0101 I was on the Summary page and clicked the "New Variant Curation" button in the header...
<img width="1427" alt="screen shot 2016-11-08 at 1 39 44 pm" src="https://cloud.githubusercontent.com/assets/15131169/20112262/a20cbafe-a5b9-11e6-9aa8-412eaaa6be82.png">

**Comment by kgliu0101** [comment]
@wrightmw 

Do you remember variant id, criteria, disease, moi, and whatever you did on the Summary page?

**Comment by kgliu0101** [comment]
**Steps to evoke the bug:**
  1. Start VCI,
  2. Enter a new variant,
  3. Click "Interpretation +",
  4. Click "View Summary" without evaluate any criteria and expect to see
![screen shot 2016-11-09 at 4 46 02 pm](https://cloud.githubusercontent.com/assets/9206696/20160491/236dc9f2-a69c-11e6-944d-3dc69d1e8de6.png)
  5. Click "New Variant Curation" and expect to evoke the bug.

**Code related**
File `/src/clincoded/static/components/variant_central/interpretation/summary.js`, line 72-73:
![screen shot 2016-11-09 at 4 50 56 pm](https://cloud.githubusercontent.com/assets/9206696/20160569/bc118ef0-a69c-11e6-97a3-d96522e6c99f.png)

**Bug fixed by change line 72 to**
`if (this.state.interpretation && this.state.interpretation.evaluations && this.state.interpretation.evaluations.length) {`

**Comment by kgliu0101** [comment]
@wrightmw 

I edited related code in summary. Test instance is at [https://1129-kl-bug-new-variant-curation-button-29cc37b-kangliu.demo.clinicalgenome.org](https://1129-kl-bug-new-variant-curation-button-29cc37b-kangliu.demo.clinicalgenome.org)

**Comment by wrightmw** [comment]
@kilodalton This bug is now fixed

**Comment by wrightmw** [comment]
Well ... the "New Variant Curation" button works on the Summary Page... so great!

**Comment by selinad** [comment]
fixed!

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
