### ISSUE TITLE
Add logic to calculate score for evidence

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#1138]
In GCI rework, it's required to calculate score in some evidence pages including individual, experimental and family/segregation. This ticket will create algorithm for the calculations. Related logics and workflow steps are displayed in New Scoring Matrix Info in ASANA.

**Comment by selinad** [comment]
### Case Level Evidence - from Individual proband entries
For a **proband** Individual (not a non-proband), we need to have ability to calculate a score based on several parameters and display it in the Score Proband section on the individual page (whether coming from Family or not).  

Here is scoring matrix for **proband** Individuals (ignore Segregation Evidence section for now - that is derived from Family, so will be explained separately):
![screen shot 2016-11-11 at 3 18 45 pm](https://cloud.githubusercontent.com/assets/11320314/20233134/33b8366c-a822-11e6-95a7-96fe3a3d3aaa.png)

Here are parameters that need to be considered in scoring an Individual and how they are derived:
- Autosomal Dominant or X-linked  or Autosomal Recessive => from moi of GDM (selected when creating a record)
- hemizygous => from zygosity pull-down
- male, female => from Sex field for the Individual **proband**
- de novo => from Indvidual **proband**
- predicted or proven null variant, other variant type with some evidence of gene impact => from pull-down on variant page
- 2 variants in trans => Individual **proband** page

We need to calculate the Default value based on the above.  Tricky thing is that variant pull-down about gene impact (on variant page) must be selected to score, so we will need a way to indicate that no score generated unless they have gone to curate variant page to select from first pull-down about gene impact.


We also need to give them a range.  E.g. "Variant is de novo" in first row - range should be 0-3.  

The "7" on this row for Max Score means that when making algorithm for final scoring, max points that can come from that type is "7" (including scores that are different from default)

**Comment by selinad** [comment]
### Segregation Evidence (from Families)
The questions answered in the Segregation section allow 1) "Estimated LOD score" calculation if no published LOD score and 2) assignment of point based on LOD score

Here's the rubric for calculating estimated LOD score (can this be "automagically" done in interface?).  Note that is different for dominant versus recessive disease - this should come from moi of GDM, but there are some where this not clear, so will need to check on this on Monday's call:

![screen shot 2016-11-11 at 2 45 21 pm](https://cloud.githubusercontent.com/assets/11320314/20233421/27405782-a824-11e6-93e7-33f3d772ed8d.png)

Note that the interface is designed such that if curator enters published LOD score, that is value to be used.  No estimated LOD score should be calculated.  Also, curator can select NOT to use LOD score (either published or estimated) and then the LOD score would not get points

Here are number of points to give based on scoring system - note max
![screen shot 2016-11-11 at 3 36 34 pm](https://cloud.githubusercontent.com/assets/11320314/20233485/e57c6cf4-a824-11e6-8444-fe401066148b.png)

One additional item - LOD scores can be added between families within a GDM - e.g. 1.5 + 1.2 = 2.7 LOD - take this combined score to calculate number of points to give for Segregation (add LODs first across families then find points)

**Comment by selinad** [comment]
### Experimental Evidence
This is scored as before, so that part of the algorithm may still exist.  We also need to add ability for curators to select from range (calculate default, but allow adjustment within the range), as described for the Case Level evidence:
![screen shot 2016-11-11 at 2 45 35 pm](https://cloud.githubusercontent.com/assets/11320314/20233534/539e30dc-a825-11e6-912e-cee4ab1218bf.png)

**Comment by selinad** [comment]
Let me know if you want me to make the above 3 separate tickets.

**Comment by selinad** [comment]
@jimmyzhen they had a typo in their scoring matrix - here is the new one for the algorithm (numbers for M and O are reversed):
![screen shot 2016-11-28 at 2 04 05 pm](https://cloud.githubusercontent.com/assets/11320314/20688016/c6b0cea8-b573-11e6-8f50-bf39dab44d4d.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have spun up an instance for you to review what I have so far:
https://1138-jz-calc-score-d7cea24-jzhen.demo.clinicalgenome.org

![image](https://cloud.githubusercontent.com/assets/6956310/20853590/bee2bae8-b8a1-11e6-8b74-64b50961cada.png)

My PR for the Mode of Inheritance changes have not been merged into the `dev` branch yet. So you probably don't want to review the GDM creation.

Rather, you shall focus on the **Proband scoring interface** (as shown above) via this instance. At the moment, you are not able to save the score in the interface yet since I have not wired up the logic. And there is no error checking implemented either. Testing out the flow and logic in terms getting the calculated default scores and score ranges given different MOIs will be suitable with this instance.

Feel free to let me know if there are any questions. Thanks!

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Please use the following new instance for your review:
https://1138-jz-calc-score-1f2499c-jzhen.demo.clinicalgenome.org

You can now save and retrieve the scoring data in this instance.

**Comment by selinad** [comment]
@jimmyzhen and I just walked through it together as there is a bug when a curator changes one menu pull-down in the scoring area.  He is aware and will work on it -- we should hold off on further testing.

**Comment by jimmyzhen** [comment]
Hi @selinad,

The following new instance is ready for your review:
https://1138-jz-calc-score-e441755-jzhen.demo.clinicalgenome.org

It has been merged with the MOI adjectives as well as Min's recent changes on adding ClinVar/CA IDs. It also consists of the changes we've discussed in this ticket as well.

Let me know if you have any questions. Thank you.

**Comment by selinad** [comment]
Hi @jimmyzhen - wow! Super fast implementation, including changes we just discussed this am - nice.

Overall it is working very well -- just a few things:

![screen shot 2016-12-06 at 3 19 03 pm](https://cloud.githubusercontent.com/assets/11320314/20948557/9a1b11d0-bbc9-11e6-96d7-2bd627f43ab6.png)

- Would prefer if "Select a scenario" does not appear until after they choose to score or review.  
- "Select a scenario" sounds hypothetical; how about "Confirm Case Information type" (this is what is on the matrix)
- instead of "Select a Different Score" use "Select a score different from default score"
- can we add a note if they select review -- something like "Since you have selected "Review," your score will not be counted towards the matrix"

One bug:

For Mitochondrial and other mois that are not part of scoring matrix, the Review option behaves like Score (the Supports option behaves perfectly):

![screen shot 2016-12-06 at 3 29 49 pm](https://cloud.githubusercontent.com/assets/11320314/20948797/c3750ad0-bbca-11e6-828f-d4480d09fb5b.png)


However, it looks like the logic is working in general for the mois - will keep testing!

**Comment by selinad** [comment]
HI @jimmyzhen - you probably found this already - I am unable to change the “Confirm Case Information type” pulldown.  The first pull-down (Score, etc.) works great!

**Comment by selinad** [comment]
We need to remove this note from the relevant pages for the R9 release as we are adding the scoring.

![screen shot 2016-12-12 at 3 50 27 pm](https://cloud.githubusercontent.com/assets/11320314/21121725/d86989a4-c082-11e6-835b-d358cd7080f7.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have a new instance for you to review the scoring on Individual, Case Control and Experimental evidence:
https://1138-jz-calc-score-updated-dd8ad95-jzhen.demo.clinicalgenome.org

Please report any problems that you encounter. Thanks!

**Comment by selinad** [comment]
Hi @jimmyzhen @mrmin123 -- there were a few holes in the LOD score values (i.e. what score to assign for which LOD score values).  Here is additional info from the GCWG (where points is how much we give the given lod score - estimated or published)

lod range            points
0.75 – 0.99            1
1 – 1.24                  1.5
1.25 – 1.49            2.5 (10:1)
1.5 – 1.74               3
1.75 – 1.99            3.5
2 – 2.49                  4 (100:1)
2.5 – 2.99               4.5
3 – 3.49                  5 (1000:1)
3.5 - 3.99               5.5
4 – 4.49                  6
4.5 – 4.99               6.5
(>/=) 5                    7​ (MAX SCORE for segregation evidence)

**Comment by selinad** [comment]
Hi @jimmyzhen 

thx so much for all your hard work on this - there is a lot involved with the scoring (am working my way through!).

One thing I noticed -- should not be able to select a different score if No selection for type of case information:

![screen shot 2016-12-13 at 10 27 28 am](https://cloud.githubusercontent.com/assets/11320314/21153389/205ab3a4-c11f-11e6-949b-68960d79fe26.png)

**Comment by selinad** [comment]
@jimmyzhen the Experimental scoring is different than Case Level -- there are default scores depending on type. So, can remove Confirm Case Information pull down and use default scores depending on evidence type (curator has already selected type of experimental evidence).  There are ranges as well.  See experimental scoring guideline above.  Sorry for any confusion.

**Comment by selinad** [comment]
Hi @jimmyzhen -  for an Individual not part of a Family -- if I select proband, the score box appears, but pull-down for score is active w/o adding variant.  Believe this should be grayed out...

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw ,

I have the following new instance for you to review the scoring:
https://1138-jz-calc-score-experimental-dca9b41-jzhen.demo.clinicalgenome.org

This instance has combined with Min's most recent changes (that were merged into `dev` by Karen) as well as the fixes addressing the problems described in Selina's recent comments in this ticket (e.g. Experimental scoring, reverting caseControl scoring to what is currently in production, etc).

Let me know if you have any questions. Thanks.

**Comment by selinad** [comment]
This is great @jimmyzhen -- thanks for your hard work!  On a call but will take a look first thing this AM.

**Comment by selinad** [comment]
Hi @jimmyzhen in middle of testing and functionality great so far!

Thought I would add any items as I go:

small item: wrapping of asterisk on Experimental score area:
![screen shot 2016-12-14 at 11 15 50 am](https://cloud.githubusercontent.com/assets/11320314/21197060/e492794e-c1ee-11e6-97d9-7ae1f1bd2719.png)

**Comment by selinad** [comment]
@jimmyzhen - all behaving correctly for review in terms of score still showing, but I think we need to provide a note that says will not be counted -- I think a yellow box would be good for this as it is a warning.

Note: This is marked with the status "Review" and will not be included in the final score

@jimmyzhen -- also, would it be possible for changed score and associated text to remain if goes from Review to Score and vv (but not for No Selection or Contradicts -- then should reset).

**Comment by selinad** [comment]
Hi @jimmyzhen - other people scoring is generally working well!

A few issues:

- If I've created the evidence, when I go to View/Score, remove my previous scoring that is there in an un-editable mode since the edit panel shows with my existing score and I can change it there
- for new scores, remove the "Assessment" panel (keep only for existing evidence)
- @wrightmw entered a piece of evidence but did not score.  I should not be able to score it since he hasn't scored, but I can right now

**Comment by selinad** [comment]
Also, we talked about this - all experimental default scores and ranges look correct except one:  Rescue for "patient cells" - says not enough info.  I am checking with group on this as it says rescue in "animal model" on their grid not "patient cells"

**Comment by selinad** [comment]
@jimmyzhen we have the wording correct in our interface...(re above), so it's just a matter of making scoring work for that one part.  For our purposes, the rescue in animal systems = rescue in patient cells wrt scoring.  thx!

**Comment by selinad** [comment]
@jimmyzhen if I remove variants from Family and then go to score individual, works great - score goes gray.  Would it be quick to add a note when this is the case?

"Proband must be associated with at least one variant to Score this evidence"

Could go in yellow box or in italics below grayed out pull-down (Status)

**Comment by selinad** [comment]
@jimmyzhen for all other moi's than AD, AR, C-linked, it will need to have Supports (as you do now) but then give pull down option for all 5 types of case info (as we discussed, you may have had that implemented at one point).  No default score or ability to change score for those.  Next release we can make Y-linked like X-linked.  thx!

**Comment by wrightmw** [comment]
@jimmyzhen Apart from the required pull-downs mentioned above by @selinad for "all other moi's than AD, AR, C-linked"... this looks like it's working well to me.

**Comment by selinad** [comment]
Works great throughout interface for all mois and Experimental.  Super nice job @jimmyzhen !

**Comment by wrightmw** [comment]
Experimental scoring works well. Great work @jimmyzhen

**Comment by wrightmw** [comment]
Experimental scoring works well. Great work @jimmyzhen

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
