### ISSUE TITLE
Scoring: Changing to "No Selection" keeps scoreStatus as "Score"

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#1240]
If a curator scores something and then changes the score to "No Selection" on the UI the data remains
`"scoreStatus": "Score",`

This allows a second curator to continue to proceed with scoring since the scoreStatus , and leads to potential confusion/erroneous data if we were to try to get all records that had been scored.

It also incorrectly shows the status as "Score" for other curators.

Options: 
- Remove the "No Selection" option if the item has ever been scored 
- or allow them to delete their score.
- something else?

**Comment by mrmin123** [comment]
One thing to keep in mind regarding the `Remove the "No Selection" option if the item has ever been scored` option:

For the Assessment model we had a logic that if other people had Assessed on an evidence, the original evidence-creator would not be edit said piece of evidence. The only way they could was if the other people who Assessed on it changed their Assessments to 'None' or whatever it was at the time. If we block the 'No Selection' option, the above behavior would not be possible.

Of course this would be a moot point if we allow the user to delete their Score. Maybe the delete route is actually more logical from the user's perspective?

**Comment by kilodalton** [comment]
@mrmin123 Yes, good points. Delete may be a better may be more appropriate route to consider.

**Comment by jimmyzhen** [comment]
I think the default `Score` value in the `scoreStatus` object in the schema may or may not have contributed the problem.

It seems logical that we delete his/her score if the other curator changes the `Score Status` from either `Score` or `Review` to `No Selection`.

However, since we don't allow other curators to score the evidence until the evidence-curator scores it, would it make sense that we disallow the evidence-curator to change the `Score Status` to `No Selection` if there are other "active" scores?

**Comment by selinad** [comment]
Moving to needs work as related to #1251

**Comment by kilodalton** [comment]
Included in last release (R9). Nice job and thanks for your hard work.
