### ISSUE TITLE
Better handling when embedded ClinVarID in CAR response is deprecated at Clinvar

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1277]
From user:

I wanted to report a CAID that is not working in the variant curation interface. The CAID is CA323244. When I hit the save and view button nothing pops up. It’s weird since the VCI recognizes the variant and populates the preview box, but it won’t load the curation screen.

CAID in CAR: 
http://reg.genome.network/allele/CA323244.html

I can confirm this behavior on the demo version -- nothing is returned on interface upon hitting Save on the CA ID window

**Comment by jimmyzhen** [comment]
It looks like a similar issue:
`{"errors": [{"name": ["clinvarVariantId"], "description": "215080 is not of type 'string'", "location": "body"}], "description": "Failed validation", "code": 422, "@type": ["ValidationFailure", "error"], "status": "error", "title": "Unprocessable Entity"}`

**Comment by mrmin123** [comment]
https://www.ncbi.nlm.nih.gov/clinvar/variation/215080/ is a 404

Is this type of behavior expected from the VCI? As in, it reports a clinvar variant ID, but the variant does not exist in ClinVar? Is it because ClinVar reported the variant ID but the (web) database isn't updated yet?

**Comment by mrmin123** [comment]
FYI the bugfix for actually saving the variant is easy (cast the value from the CAR to string, like we do in #1259), but requires further downstream fixes. The VCI goes bonkers because the API calls made if a clinvar ID exists fails rather ungracefully at the moment:

![image](https://cloud.githubusercontent.com/assets/4326866/22437690/d73e9cb4-e6dd-11e6-83b2-cbf834237936.png)

**Comment by kilodalton** [comment]
The problem encountered in this ticket is due to the fact that a deprecated ClinVar ID was present in the CAR response. The deprecated CV ID was removed from the CAR, and then our interface worked as expected. 

As a general principle we should programmatically "double-check" that important identifiers (returned in any API response we receive) are connected to currently valid identifiers rather than try a secondary query and fail in an ungraceful (blocking) way.

**Comment by wrightmw** [comment]
This is dependent on ClinVar updating their XML for deprecated and merged entries.

**Comment by selinad** [comment]
@wrightmw what is the gist of the dependency?  Do we have an update on this? thx!

**Comment by wrightmw** [comment]
@selinad This is dependent on ClinVar updating their XML for deprecated and merged entries.

**Comment by courtneythaxton** [comment]
My interpretation of this, is that a CAiD alone should allow curation of evidence and not be linked to double checking in ClinVar. The same is true of ClinVar IDs. 

Obsolete @wrightmw
