### ISSUE TITLE
Get rid of Dashboard React Warning

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#129]
When /dashboard displays, React gives a “key” warning:

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Dashboard. See https://fb.me/react-warning-keys for more information.
```

Some iterative code in a component “render” method needs to add a “key” property to avoid this warning.

**Comment by kilodalton** [comment]
A separate warning exists due to non-conforming timestamps in the data and will be addressed in a separate ticket: 
`Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info. Error [...]`

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
