### ISSUE TITLE
Display of Pubmed Dates - Zero prepending display day

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#1314]
PMID 28259794

Renders on our interface
>>>2017 Mar 01

![image](https://cloud.githubusercontent.com/assets/1878194/23627081/21d3201e-0264-11e7-8cf6-58075a96324d.png)

_Note: should be `2017 Mar 1`_

This is a low-priority fix.

**Comment by selinad** [comment]
This works in curation-test -- thank you!

**Comment by jimmyzhen** [comment]
There also appears to be a spacing issue between the date and publication volume/issue:
![image](https://user-images.githubusercontent.com/6956310/31833355-2561d49a-b57f-11e7-9ed1-18a3157883ff.png)

**Comment by bryanwulf** [comment]
The following instance includes an update to remove a prepended zero from the day of an article's publication date when added from PubMed:
https://1314-bw-pubmed-dates-7b13e8513-bwulf.demo.clinicalgenome.org

In order to test the update, here are a couple of sample PMIDs associated with articles published on the first of a month:
29088483
29088396

Note: This update only modifies the date at the time when the article is added from PubMed.  Articles that currently display a prepended zero in our system (have already been added from PubMed) will continue to do so.  If we need to fix these existing articles, we'll likely need to update them directly in the DB.

**Comment by wrightmw** [comment]
29088483 and 29088396 display correctly @bryanwulf

**Comment by selinad** [comment]
ditto -- they both display correctly and I'm sorry as I somehow missed this original fix/instance.

**Comment by jimmyzhen** [comment]
Included in R15 release.
