### ISSUE TITLE
Multiple HPO terms entered in experimental field result in concatenated link

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1317]
On Model Systems, when there is > 1 HPO term entered, the View page shows concatenated HPO terms in link and link does not work -- other places where multiple HPO IDs are allowed in interface should probably be checked.

![screen shot 2017-03-08 at 2 57 40 pm](https://cloud.githubusercontent.com/assets/11320314/23728102/e6cf221c-040f-11e7-89b3-283609c4bd30.png)
![screen shot 2017-03-08 at 2 57 57 pm](https://cloud.githubusercontent.com/assets/11320314/23728111/ebe2f36e-040f-11e7-81a8-02868294b503.png)

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review the changes pertinent to this ticket in the following instance:
https://1317-jz-hpo-links-f4feeba-jzhen.demo.clinicalgenome.org

Please let me know if you have any questions. Thanks.

**Comment by selinad** [comment]
Primo!  Works perfectly @jimmyzhen -- this is the only place I ever noticed this. Just checked family and it did not have same problem.  Do you think it was an isolated coding thing?

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The problem was that the HPO IDs in Model Systems and Rescue are stored as strings while those in Family are stored as arrays. As a result, the UI simply renders the multiple IDs as one single string for the 2 types of Experimental Data.

Ideally, we should correct the problem by updating the schema and the stored data currently in production. Also update the code that store the IDs and the code to render the UI. But since this is a bigger task, I don't think we have the time for it in this release. So for the time being, I just fixed UI by splitting the IDs in the string into an array.

**Comment by selinad** [comment]
@jimmyzhen this works perfectly, but the Human HPO terms are not hyperlinked for some reason -- should I create new ticket for R12?
![screen shot 2017-06-14 at 12 39 25 pm](https://user-images.githubusercontent.com/11320314/27151198-afd2bb20-50fe-11e7-96fe-d40e71b8de7b.png)

**Comment by selinad** [comment]
@jimmyzhen it helps when I put the HPO terms in the HPO rather than free text fields :P  Works perfectly then!  Sorry for the alarm.
![Screen Shot 2017-06-14 at 1.40.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5579c6699ede26190013c548/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455f76b7191a379f1162b4f5a585ecc3c4a4356bcbbd671f3e57862804e0ee8d66b5d21ce6914afedd719bf09b9208b1d86e3b8891fd2f42f67b6d5db1063474f4dcbed5727a29f41c95cff4ce54a57ad113563e0752431.png)

**Comment by kilodalton** [comment]
Included in last release (R11). Nice job and thanks for your hard work.
