### ISSUE TITLE
Add Medaka (and maybe more organisms) to non-human model organism pulldowns

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1323]
Curator request to include Medaka fish (Oryzias latipes) in the animal models pulldown in the GCI Experimental (Model Systems). Will find out from gene curation WG and biocurators if other organisms should be added at the same time.

Add Saccharomyces cerevisiae and Chlamydomonas to this -- requires discussion (confirmation with larger GCWG) as to using a non-animal model.

![screen shot 2017-03-30 at 12 22 44 pm](https://cloud.githubusercontent.com/assets/15131169/24522233/b4204b1c-1543-11e7-9f94-2bdbe777d5a0.png)

**Comment by ErinRiggs** [comment]
@marinadistefano Didn't you have an example of a scenario where an expert felt that saccharomyces was an animal model?  We were going to bring this to the large group for discussion at some point.

**Comment by marinadistefano** [comment]
Sorry for forgetting to ever send you all this example. 

Alison Bertuch mentioned that in NHP2:Dyskeratosis Congenita had yeast models. After her suggestion, I ended up scoring the one yeast model:


Dez 2001 PMID: 11160879 We show that the presence of the H/ACA snoRNP proteins Cbf5p, Nhp2p and Nop10p, but not Gar1p, is required for the accumulation of mature
 non-polyadenylated hTR in yeast, while accumulation of TLC1 RNA is not affected by the absence of any of these proteins. (Animal model 1 pts bc yeast)



A second example of this was a yeast model for VPS8 and arthrogryposis. Alan Beggs also agreed to score this on based on the field (the vessicle sorting field largely uses yeast as their animal models because of the ability to make conditional or temperature sensitive deletions):

Horazdovsky 1996 PMID: 8969229: biochemical function- The authors deleted VPS8 from yeast and determined that there was a problem with missorting and secreting soluble vacuolar hydrolases. This null phenotype is similar to other components in the CORVET pathway, which are associated with a recessive form of Arthrogryposis.

 Epp et al 2013 PMID: 23840658: Experiments were performed in yeast. VIPAS39 and VPS33B are part of the CORVET complex, which facilitates endosomal biogenesis. Variants in these genes are associated with ARC, which is a recessive form of Arthrogryposis. The authors demonstrate with constructs that the N terminus of VPS8 is required for localization to CORVET. They also demonstrate with Co-IPs that VPS8 is a subunit of the CORVET complex and is required for its correct localization and function.

**Comment by wrightmw** [comment]
@jimmyzhen @selinad 
New organisms to be added to "Non-human model organism" pull-down:
Budding yeast (Saccharomyces cerevisiae) 4932
Fission yeast (Schizosaccharomyces pombe) 4896
Chlamydomonas (Chlamydomonas reinhardtii) 3055

**Comment by wrightmw** [comment]
@ErinRiggs @marinadistefano @jennygoldstein @BryceSeifert @TashaStrande @sarahhemphill

Hey everyone, can you please confirm that we should also add the new organisms in the "non-human model organism' pull-down in the Rescue section?:

![screen shot 2017-09-19 at 10 08 08 am](https://user-images.githubusercontent.com/15131169/30605384-bdbfca14-9d22-11e7-925b-2c9cc5ae0d1b.png)

**Comment by jennygoldstein** [comment]
Yes, these organisms can also be added in the rescue section.


Thanks,


Jenny


________________________________

**Comment by wrightmw** [comment]
Thanks @jennygoldstein

**Comment by jimmyzhen** [comment]
This change request will be included in the #1335 branch.

**Comment by wrightmw** [comment]
@jimmyzhen @selinad 
We should have totally spotted this before now but there are a number of typos in the pull-downs for these other species (shown corrected):

Dog (Canis lupus familiaris) 9615
Gerbil (Gerbillinae ) 10045
Rabbit (Oryctolagus cuniculus) 9986
Round worm (Caenorhabditis elegans) 6239
Zebrafish (Danio rerio) 7955

Here is the complete correct list:

"Budding yeast (Saccharomyces cerevisiae) 4932",
"Cat (Felis catus) 9685",
"Chicken (Gallus gallus) 9031",
"Chimpanzee (Pan troglodytes) 9598",
"Chlamydomonas (Chlamydomonas reinhardtii) 3055",
"Cow (Bos taurus) 9913",
"Dog (Canis lupus familiaris) 9615",
"Fission yeast (Schizosaccharomyces pombe) 4896",
"Frog (Xenopus) 262014",
"Fruit fly (Drosophila) 7215",
"Gerbil (Gerbillinae ) 10045",
"Guinea pig (Cavia porcellus) 10141",
"Hamster (Cricetinae) 10026",
"Macaque (Macaca) 9539",
"Mouse (Mus musculus) 10090",
"Pig (Sus scrofa) 9823",
"Rabbit (Oryctolagus cuniculus) 9986",
"Rat (Rattus norvegicus) 10116",
"Round worm (Caenorhabditis elegans) 6239",
"Sheep (Ovis aries) 9940",
"Zebrafish (Danio rerio) 7955"

**Comment by wrightmw** [comment]
@jimmyzhen Functionality of this works well on latest instance for all three new non-human model organism types. The only issue that needs to be addressed is the typos for some of the other organisms in the list. I have created a separate ticket for these #1482 .

**Comment by selinad** [comment]
Looks great @jimmyzhen !  Thank you.

**Comment by selinad** [comment]
@jimmyzhen This looks great for Model Systems and Rescue (present in dropdown) and can save them too.  Nice work!

**Comment by wrightmw** [comment]
@jimmyzhen It's great that these new ones have been added. It's a shame we can't fix the typos within this list until next release but there is a ticket for this (#1482).

**Comment by jimmyzhen** [comment]
Included in R13 release.
