### ISSUE TITLE
Add "Evidence Summary" text box in VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1330]
Curators need a place to write a summary of the evidence they have evaluated. This free text field will be exported to ClinVar. 

It was suggested that this would appear on the Summary page, this could be an option provided when the curator opts to submit their Summary to ClinVar.

**Comment by selinad** [comment]
We are moving this to be part of the Approval workflow

**Comment by wrightmw** [comment]
@sharrison6 We are planning to get the new "Evidence Summary" box you requested into the next release. What instruction text would you like to see inside the box to guide curators on the purpose of this field?

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

You may review the requested addition of Evidence Summary in VCI via the following instance:
https://1330-jz-evidence-summary-3874a76-jzhen.demo.clinicalgenome.org

**Comment by sharrison6** [comment]
In the ClinVar submission form, this field is described as "Free text describing the rationale for the clinical significance". Maybe we merge to two descriptions? "Summary of the evidence and rationale for the clinical significance (optional)". ?

**Comment by wrightmw** [comment]
Thanks @sharrison6 ... we'll update the text.

**Comment by wrightmw** [comment]
@jimmyzhen Other than text change, looks good to me.

**Comment by jimmyzhen** [comment]
@wrightmw,

The requested text change is now ready for review on the same instance.

**Comment by selinad** [comment]
@jimmyzhen thx for this!

A couple of thoughts:
* as we removed the box that mentioned disease needed to be associated for Likely P or P, maybe the "?" text should include this information.  From "editing interpretation is permitted after selecting this option" to "An interpretation can still be edited after it's marked "Provisional." If the Interpretation is "Likely Pathogenic" or "Pathogenic," it must be associated with a disease before it can be marked as "Provisional."
* This could be too time consuming...once something is saved and the button says "Update," could it be an unclickable "grayed out" version of the button until someone changes something in that section?  Or, maybe the green text that says something was successfully saved can disappear either after a few seconds or as soon as someone starts typing?
* I'm thinking I have no way to see if it's actually saved other than coming back and seeing it....that works well!

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

1. The 'provisional status help' message has been updated to include new help text. Also, the mouse-over behavior has been changed to a click interaction to display the popover, which is more suitable for longer text description and more text formatting flexibility.
2. Disabling the **Update** button until someone makes a change in the form can be tricky in this very case. Since we already have logic to enable/disable the **Save** or **Update** button depending on the modified pathogenicity (and its corresponding explanation), doing so would add extra complexity to the existing logic and risk introducing bugs. So I've opted for making the feedback message more "obvious" to users visually upon the save/update action. As Selina suggested, the feedback message has been configured to disappear in 6 seconds.

You may review the described changes on the same instance:
https://1330-jz-evidence-summary-3874a76-jzhen.demo.clinicalgenome.org/

**Comment by wrightmw** [comment]
@jimmyzhen  Thanks for implementing this. Given that this ticket was just to add the Evidence Summary box for the next release, then I don't want to suggest any substantive changes because this format is only interim. In the subsequent release we will be reformatting this whole section as part of the new approval/review process. Looks ok to me.

**Comment by selinad** [comment]
@jimmyzhen agreed!  (4:55 AM?!)

Looks great -- the message is more obvious and somehow having it disappear like that helps quite a bit.  The text on the "?" looks great and I like it's functionality.  Nicely done, thanks!

**Comment by selinad** [comment]
Hi @jimmyzhen this works well.  Only one funny thing I noticed and could make a ticket for for another release -- it's possible to hit "Save" the first time you go to the Summary without entering any info.  No harm, no foul, but maybe Save button could be inactive until first change?  

@wrightmw @jimmyzhen what do you think for future ticket?

**Comment by wrightmw** [comment]
@selinad Future ticket!
