### ISSUE TITLE
Small text changes to Functional Alteration and Model Systems

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1334]
Note: May want to implement in connection with #1321.  Putting it as R11 but can be moved.
 
Functional Alteration
- Change selection to "Candidate mutation in patient cells or non-patient cells?: *" (from "Patient cells with candidate mutation or engineered equivalent?: *")
- Change pull-down selection "Engineered equivalent" to "Non-patient cells" (leave "Patient cells" as is)

Model Systems
In first pull-down, change "Engineered equivalent" to "Cell-culture model" (will match text next to it)

**Comment by jimmyzhen** [comment]
Hi @selinad,

In terms of changing the label text to "Candidate mutation in patient cells or non-patient cells?"  should be straightforward since it only affects the display on the experimental data curation form page and the view-only page.

However, changing the pull-down selection text will likely affect more than just the display. Since we generally set the values of the pull-down selection to be the same as the selection text, making this change will require us to update any existing experimental records in which "Engineered equivalent" has been saved in the database.

While not visible to the users, the value of "Engineered equivalent" is also used and referenced in various places in the code to handle UI rendering and input validation. All these will need to be updated accordingly to reflect the selection value changes ("Non-patient cells" and "Cell-culture model").

Is there another approach to this selection text change that seemingly requires more effort to do? If not, then can we consider moving this ticket to R12?

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Do we still need this ticket now that we have #1444 and #1446?

**Comment by selinad** [comment]
@jimmyzhen -- thanks for checking.  We don't need it -- the tickets you mentioned are the most current, so I will close this one.
