### ISSUE TITLE
Add instruction text to Curation Central page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#140]
When a user creates a new GDM or enters an existing GDM such that no article is selected and the middle and right sections are empty, please add the following instruction text to the middle section:

*Add papers to this Gene-Disease Record using the Add New PMID(s) button; click on any added paper to view its abstract and begin curating evidence from that paper.*

**Comment by mrmin123** [comment]
@selinad How does this look?:

![image](https://cloud.githubusercontent.com/assets/4326866/9099520/33162232-3b86-11e5-8676-b6686171f67a.png)

**Comment by selinad** [comment]
Hi Min - it actually looks good, but I have to confess that I looked at the image before being reminded of the ticket and completely missed the blue :P  My eye went to the red, so I was thinking it was something about that ticket.

I was thinking it would go in the space where the abstract appears when you click on a paper.  So, at level with the Add PMID and in the center white section.  Another option would be to experiment with it going below the Add PMID button and staying within the same area as that button (i.e. below it, but not extending past the borders of the button)...I'm not sure about the blue since the button is blue.  Is there a way to indicate an alert without it being flashy and obnoxious?

**Comment by mrmin123** [comment]
I didn't make it red because there was already a red notice on the page, but that's a good point. How about I just remove the noticebar style and just make it plain text?:

Where literature information would show up:
![image](https://cloud.githubusercontent.com/assets/4326866/9116749/da63ace6-3c1a-11e5-9c36-ecc9d8188399.png)

Below 'Add PMID' button:
![image](https://cloud.githubusercontent.com/assets/4326866/9116931/eb53c4d6-3c1b-11e5-98f6-1c8c09588351.png)

**Comment by selinad** [comment]
Hi @mrmin123.  Looks good - I kind of like it under Add New PMID(s) - what is your favorite?  How would the text look if centered? thx!

**Comment by mrmin123** [comment]
@selinad I prefer it under the button, as well. I tried centering the text and making the font a bit smaller:

![image](https://cloud.githubusercontent.com/assets/4326866/9125184/cff7cf70-3c52-11e5-96e7-98a79f210eaa.png)

**Comment by selinad** [comment]
Thanks, @mrmin123.  @forresttanaka can pipe in, but I think we have been italicizing instructions - should we do that?  It might look better left justified after all...

**Comment by forresttanaka** [comment]
We only have one instance of long-form instructions — the one that appears above the abstract when you click a paper you haven’t added on the Gene Disease Record page, and it’s in italic.

I think it will look better left-justified, especially if you end up with only one or two words on the last line. Centered long-form text is slightly harder to read since your eye has to keep returning to a different spot on each line.

**Comment by selinad** [comment]
Thanks, @forresttanaka.  I vote for italics.  For the new page you are working on (the one you see after submitting Group data), will you be italicizing the instructions? Given the long-form instruction that already exists, I think the italics make sense, but am open to other opinions.

**Comment by forresttanaka** [comment]
Sure, I’ll do the instructions in italic on the Group Summary page, which is what I’m calling it based on the PPT.

**Comment by mrmin123** [comment]
Sounds good. Italics and left justification:
![image](https://cloud.githubusercontent.com/assets/4326866/9140366/861d4a40-3ce5-11e5-8498-7ab76706cb36.png)

**Comment by selinad** [comment]
nice! thx @mrmin123

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
