### ISSUE TITLE
Include filter status and quality metrics for ExAC and gnomAD data

### ISSUE THREAD

**Issue by heidirehm** [ClinGen/clincoded#1405]
Anne O'Donnell from MacArthur Lab raised concern on VCI display of ExAC/gnomAD data. I'm pasting Slack discussion here:

anneod
[10:41 PM] 
@heidi_rehm - major issue with the ClinGen tool - it seems to be pulling allele counts for ExAC filtered variants. Example is ClinVar VariationID: 60, which is http://exac.broadinstitute.org/variant/1-243468435-C-T

heidi_rehm 
[11:09 PM] 
Hmm, do you think this is OK if we can get Stanford to display filter status and warning of a low-quality site?

anneod
[11:25 PM] 
I think it’s pretty misleading - for this site there are 62 in ExAC but very low depth (less than 20X) - because it’s an intronic region - so all these calls are likely spurious. In gnomAD, the exome again have no coverage and fail QC, but it’s well covered in genomes - were AC = 2. There is a lot of junk in ExAC if you look at things that fail filter including at sites with very low coverage. (edited)

----- June 26th -----
heidi_rehm
[6:06 PM] 
I guess the question is, why is ExAC showing and if there is a reason, should we use same rationale and note caveats the same? Or if there is no reason or context in which this data should be shown, should it be removed from ExAC as well as our tool?

anneod 
[6:37 PM] 
So in ExAC, all variants in the call set are available in the data but we only show variants that pass qc filters as the default on the site. In the sites vcf - these are denoted by a PASS column. We recommend people only use PASS (high quality) site but we don’t actually take variants out of the call set. (edited)

[6:37] 
Same for gnomAD.

**Comment by wrightmw** [comment]
Related to #848 

Other examples of Filter Status that are not "PASS":

http://exac.broadinstitute.org/variant/7-142458451-A-T which has a Filter Status of InbreedingCoeff_Filter

http://exac.broadinstitute.org/variant/12-112884053-A-T which has a FIlter Status of VQSRTrancheSNP99.90to99.95

http://exac.broadinstitute.org/variant/7-37243784-T-C which has a Filter Status of AC_Adj0_Filter

http://exac.broadinstitute.org/variant/7-37355573-T-A which has a Filter Status of VQSRTrancheSNP99.60to99.80

**Comment by wrightmw** [comment]
@jimmyzhen This is now in MyVariant.info, they show a "filter" field when a variant is not "PASS".
For instance, for 
http://exac.broadinstitute.org/variant/7-142458451-A-T which has a Filter Status of InbreedingCoeff_Filter

In MyVariant.info this is http://myvariant.info/v1/variant/chr7:g.142458451A%3ET
it is "filter": "InbreedingCoeff_Filter"

**Comment by wrightmw** [comment]
@bryanwulf Is there time for this ticket to be this release?

**Comment by wrightmw** [comment]
If the "filter" fields are absent in the MyVariant.info response then they are PASS and can be ignored, but if the "filter" field is present then that indicates a warning that should be displayed on the table.

For instance, see https://myvariant.info/v1/variant/chr7:g.142458451A%3ET (this is ClinVar VariationID: 11877)

The ExAC "filter" field says "InbreedingCoeff_Filter":

![screen shot 2018-01-31 at 9 18 43 am](https://user-images.githubusercontent.com/15131169/35637481-3410f54e-0669-11e8-8c4d-dd7700bd22a9.png)

So, this should then be shown on the ExAC table in the VCI, for instance:

![screen shot 2018-01-31 at 9 33 48 am](https://user-images.githubusercontent.com/15131169/35637724-eede28a6-0669-11e8-9a86-070a98815b8a.png)

**Comment by bryanwulf** [comment]
@wrightmw @selinad Filter status information has been added to the ExAC and gnomAD population tables in this instance:
https://1523-bw-gnomad.demo.clinicalgenome.org/

A couple of useful ClinVar IDs to test with:
17000 - all filters are "Pass"
21134 - a "No variant" filter for gnomAD genome data
11877 - multiple filters

**Comment by wrightmw** [comment]
@bryanwulf Those examples you provided certainly do provide the correct Exomes/Genomes data and Filter Pass statuses. Great! I'll take a look at some different example types to make sure all is well, but looks good so far. 
@selinad I think it's great that we are presenting the checkboxes and filters as seen on the ExAC and gnomAD sites. However, I think we we may need explanatory text when users hover over the checkboxes to explain that they are not checkable (and what data we are bringing in), otherwise users may just think they are broken. What do you think?

**Comment by selinad** [comment]
Hi @bryanwulf  Fantastic!  It will be great to have this.

As we talked about -- it looks like MyVariant.info adds SEGDUP as a filter, even though gnomAD doesn't display it the same way.  Thus, we display it in a yellow box next to Filters, even though they have it at the top of the entry instead of next to Filter:

![image](https://user-images.githubusercontent.com/11320314/35834826-490391ec-0a8c-11e8-9b65-0e91bb2df06f.png)
 
wrt to @wrightmw comment -- I agree they look like one should be able to edit it.  We chatted through this, @wrightmw and found some icons that we all agreed upon that should make it clear they are just representing the status and are not an interactive part of the interface -- thx @bryanwulf and @jimmyzhen !

**Comment by wrightmw** [comment]
@selinad Glad to hear the checkbox icons will be more obvious. Great work on this @bryanwulf

**Comment by bryanwulf** [comment]
@wrightmw @selinad The icons have been updated in the instance:
https://1523-bw-gnomad.demo.clinicalgenome.org/

I'm going to proceed with a pull request.

**Comment by wrightmw** [comment]
@bryanwulf I like those new tickboxes.

**Comment by selinad** [comment]
me, too -- I like the new no-tick tickcircles!  thx @bryanwulf !

**Comment by selinad** [comment]
This looks great, @bryanwulf !  Very nice!

**Comment by wrightmw** [comment]
All the new VCI features are working well. Thanks @bryanwulf

**Comment by jimmyzhen** [comment]
Included in R16 release.
