### ISSUE TITLE
Add PubMed articles via the PubMed modal in the G, F and I Additional Information sections

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1475]
@ErinRiggs @marinadistefano @BryceSeifert @jennygoldstein @selinad @wrightmw @sarahhemphill @TashaStrande
This is a suggested item for discussion on one of our small GCI WG calls.

Currently papers pertaining to additional information about a Group, Family or Individual are added as free text into the Additional Information sections. Should these be added via the PubMed modal so that these PubMed IDs are stored as IDs instead of free text?:

![screen shot 2017-09-21 at 7 34 11 pm](https://user-images.githubusercontent.com/15131169/30727090-eebb9534-9f03-11e7-99bb-71a1f94e6e7e.png)

![screen shot 2017-09-21 at 7 34 18 pm](https://user-images.githubusercontent.com/15131169/30727096-f342c49c-9f03-11e7-81aa-d5fc9340512c.png)

![screen shot 2017-09-21 at 7 34 25 pm](https://user-images.githubusercontent.com/15131169/30727097-f885ab9a-9f03-11e7-929f-2bed6a252b8e.png)

**Comment by marinadistefano** [comment]
Is there a way to make the PMID optional? I would like to see a PMID if possible, but want to give the curators the option to do free text. Let's discuss on Monday.

Marina
________________________________

**Comment by ErinRiggs** [comment]
I don't think this is necessary, because you don't want to score the same group/family/individual twice.  I use this box when an older paper has described the phenotype of the family, but a newer paper (the one I'm choosing to score) describes their variant.  I don't want to score anything from the older paper, just let people know that it exists if they are interested.

I like Marina's suggestion of free text.  Marina, currently, that field "as-is" is optional, but you can only enter a PMID there.  Several times I've wanted to type in a sentence about what is actually in the paper I'm referencing ("The phenotype is described in detail in PMID 12345"), but the box only accepts numbers.

**Comment by courtneythaxton** [comment]
@wrightmw Low priority, however I can think of a few options for this. As mentioned above you can make the whole box free text, however you can lose context. 

IT might be nice to rework to present several boxes, in which you have a PMID and then associate a note to the PMID. Much like and annotation with hypothesis.

You can present at least 3 of these boxes and allow users to add more as needed.


<img width="512" alt="Screen Shot 2019-08-12 at 8 01 02 PM" src="https://user-images.githubusercontent.com/32530005/62906239-f43efe80-bd3b-11e9-80b6-5205c330a8b4.png">

What do you think @erinriggs @marinadistefano @jennygoldstein
