### ISSUE TITLE
Published LOD score should display to 2 decimal points

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1485]
If I enter 2.00 as the Published LOD score, it saves as "2" -- should save to 2 decimal points

**Comment by bryanwulf** [comment]
Places in which this value may be present: curation form page, view-only page, matrix and evidence summary.

**Comment by bryanwulf** [comment]
@selinad It looks like that precision, from "2.00" to "2" or "1.500000" to "1.5", is lost when the data is saved (when the form is submitted).

Does the data need to be saved exactly as it was input by the user (so that, wherever it might be displayed, it will appear as entered) or is there a specific page/location where the Published LOD score should always be shown with two decimal places?

**Comment by selinad** [comment]
@bryanwulf I'm sorry, I don't know how I missed this.  There is a calculated LOD score and a LOD score a user can enter.  This is in reference to a LOD score the user enters (on the Family page) when they want to use a published LOD score rather than the calculated one.  Let me know if you have any more questions and I will show you in person.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Given the latest changes to the segregation LOD score, do you think this is still a valid issue that needs to be addressed?

@bryanwulf, if Matt determines this to be a valid issue to be addressed, can you take this on since you are working on the alternate classification matrix? Thanks.

**Comment by wrightmw** [comment]
@bryanwulf @jimmyzhen Whether some of our figures are 6 as opposed to 6.00 does not look aesthetically good, however the actual numbers are correct (i.e. 6 is the same as 6.0 or 6.00, etc.)...so if this is a quick fix then by all means do it now.. but personally I don't think this is high priority.

**Comment by courtneythaxton** [comment]
@wrightmw This is aesthetic and would consider at a low priority at this point. While it would be nice to be consistent, we have a cap of 2 decimals for the segregation with the new calculator. Also, it does help to save on space in the evidence summary.

what do you think @erinriggs @Jennygoldstein
