### ISSUE TITLE
Notes field for PubMed articles

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1486]
Would it be useful for a curator to be able to add general notes about a PubMed article that are viewable when they look at the abstract in the GCI.

**Comment by wrightmw** [comment]
This could also be used to mark PubMed articles as not containing any pertinent information.

**Comment by selinad** [comment]
From #1139 : Ability to tag a paper as not having any evidence for a gene, disease, variant, etc. (triage)

**Comment by selinad** [comment]
Thought: ability to add on the right hand column where you add evidence (per paper) (lower priority)

**Comment by ErinRiggs** [comment]
In middle PubMed box:
1. Two tick boxes - one for "Non-scorable evidence" and another for "Other comments on PMID" AND a free text box for explanation.
2. If "Non-scorable evidence" is checked, pull over PMID and free text box explanation to Evidence Summary.
3. Place these boxes below title and authors but above abstract.
4. Visually demarcate box with a line and/or different color.
5. Need to have the ability to uncheck box if needed, so that evidence could be scored at a later date.

**Comment by wrightmw** [comment]
@ErinRiggs Would the comments be specific to the PMID article for that specific gene-disease record or would you expect the comments to be viewable when the same PMID article is used in any gene-disease record?

**Comment by wrightmw** [comment]
@courtneythaxton

**Comment by courtneythaxton** [comment]
@wrightmw Good question. My first inclination is that we would want this specific to the gene-disease record and not to the PMID, as if the PMID has different possible utility for scoring multiple disease entities, I would not want the lack of a score for one GDM to influence the inclusion of the PMID in another separate GDM.

What are your thoughts @ErinRiggs @marinadistefano @jennygoldstein

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PMID article notes](https://trello.com/c/tF7r8tuV/28-pmid-article-notes)

**Comment by courtneythaxton** [comment]
@wrightmw This is a high priority ticket, and specified.

**Comment by wrightmw** [comment]
Looks great in R31 release candidate! Can save both types of comment, and non-scorable evidence appears in table in the Evidence Summary.

**Comment by wrightmw** [comment]
Release 31
