### ISSUE TITLE
Couldn't find index page for 'mr.developer'

### ISSUE THREAD

**Issue by gto389** [ClinGen/clincoded#1509]
Running `buildout` failed due to following error:
```
Couldn't find index page for 'mr.developer' (maybe misspelled?)
Getting distribution for 'mr.developer==1.31'.
Couldn't find index page for 'mr.developer' (maybe misspelled?)
While:
  Installing.
  Loading extensions.
  Getting distribution for 'mr.developer==1.31'.
Error: Couldn't find a distribution for 'mr.developer==1.31'.
```

**Comment by jimmyzhen** [comment]
By consulting with the `zc.buildout`'s developer, the issue has been identified as related to [PyPI disabling non HTTPS access to APIs](https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html) rather than `mr.developer`. See [discussion on their GitHub repo](https://github.com/buildout/buildout/issues/420) for more details.

Upgrading `zc.buildout` from _2.3.1_ to the latest _2.9.5_ appears to have helped and the buildout process can now be successfully completed locally, on Travis CI, and on AWS S3 as well.

The following files have been updated as a result of the upgrade:
![image](https://user-images.githubusercontent.com/6956310/32138986-766a911e-bbf2-11e7-85f6-09c1beab2013.png)

In the process of debugging the issue, the `setuptools` has also been identified as being out-of-date and hence we shall attempt upgrading it as well, possibly in a different ticket.

**Comment by jimmyzhen** [comment]
The fix for this issue has been included in the https://github.com/ClinGen/clincoded/tree/1505_jz_vep_deletion_variant branch.

**Comment by jimmyzhen** [comment]
Included in R14 release.
