### ISSUE TITLE
Updates to existing disease terms following MonDO release update

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1516]
MonDO made significant changes in its latest release, affecting many clique leaders.  We have a file of these changes.  @wrightmw and I will identify records that need to be updated.  

@jimmyzhen is there a way for you to spit out what we have into a Google doc like we did when this happened before (ie. GDMs, Groups, Families, etc. + Interpretations).

**Comment by jimmyzhen** [comment]
I've spun up an instance that consists of the test curation interfaces and a "local" OLS build.

When testing this instance, you should expect that looking up a disease by MonDO ID should bring back data from the "local" OLS build.

Given the mappings file provided to us by Chris Mungall, I wrote an upgrade script to migrate all the Orphanet, DOID, OMIM and NCIT IDs to their new MonDO IDs accordingly (along with the disease terms and definitions).

There might be a few non-MonDO IDs not affected by the upgrade script, possibly because they were entered into our database after we provided the list of disease IDs to Chris.

The test instance URL can be found in the `Slack` "General" channel.

**Comment by selinad** [comment]
@jimmyzhen what is the "disease collection page?"

**Comment by selinad** [comment]
@jimmyzhen this looks great -- I have spot checked several in GCI and VCI.
Do you want us to check all prod records against rc records to verify mappings?

**Comment by jimmyzhen** [comment]
I don't think that's necessary.

**Comment by jimmyzhen** [comment]
Included in R14 release.
