### ISSUE TITLE
Allow Classification Matrix and Evidence Summary to be viewable to any logged in user once record is marked Provisional

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1528]
Once a user has marked and saved a Classification as "Provisional," provide any other user with the ability to view that Classification Matrix and Evidence Summary (need to discuss as there could be multiple Provisional Classifications, so we need to provide users with ability to view all -- this would mean listing Provisional Classifciations and owner and having View button next to it.  

Maybe we want to do this from View all Gene-Disease records page?  We could also do this from the header, but need to be able to show all existing Classifications (like we do for Interpretations).

Marking this as R14, but can be moved to R15.

**Comment by selinad** [comment]
@erinriggs @marinadistefano @jennygoldstein can you please confirm it is still a desire for the Matrix Classification and Evidence Summary to be viewable by all once a record is marked provisional?

thx!

**Comment by ErinRiggs** [comment]
I think that is correct, but Marina/Jenny please confirm.

**Comment by jennygoldstein** [comment]
Yes, I think so too.

**Comment by selinad** [comment]
Thanks @erinriggs @jennygoldstein -- we will implement it accordingly unless you think it requires further discussion on Monday.

**Comment by wrightmw** [comment]
It is envisaged that the "All GDMs" list will have all Saved Provisional/Approved Classifications listed for each Gene-Disease record. 
For this ticket, the curators would be happy to have all Saved Provisional/Approved Classifications shown in the header, so that they can link through to Provisional/Approved Classifications saved by other curators/Affiliations.

**Comment by jimmyzhen** [comment]
Addressing this ticket in the #1616 branch.

**Comment by wrightmw** [comment]
@jimmyzhen Great work on this!

![screen shot 2018-08-06 at 10 32 36 am](https://user-images.githubusercontent.com/15131169/43731714-36a9c9b4-9964-11e8-93de-55ad526b43bc.png)

1) The "ClinGen Curator Test Affiliation 1" is Published but my "Matt Wright" one is not published. Maybe good to show this by putting the purple Published icon after the "View Classification" link. @selinad do you agree?

2) @selinad do you think we could state the Classification here for each of these? These three are all different Classifications (Limited, Moderate, and Strong) but this is not known by the current view.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

Please review the suggested changes in the following new instance:
https://1528-jz-combo.demo.clinicalgenome.org

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

The following new instance is available for you to review the suggested changes in #1547:
https://1528-jz-combo-fixes.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen Your changes look great! Thank you. I do have a few comments... sorry!
1) Again, so that the GCI and VCI are the same and everyone knows what we are presenting to them... can you please add an "i" icon in the "All classifications for this record in the Gene Curation Interface (GCI)" table header whereby the mouseover text says:
 "Classifications marked as "Approved" may be viewed by any user within the interface; those marked "In Progress" or "Provisional are viewable only be the submitter"
This would make it the same as the VCI:
![screen shot 2018-09-23 at 5 58 18 pm](https://user-images.githubusercontent.com/15131169/45934995-f0a35d00-bf5a-11e8-8c82-eb75c160044c.png)
2) "My Classification" is on on two lines, whereas "Other Classifications" are on one line each. Maybe put "My Classification" on one line too, so that they all have the same format.
3) A minor point, but "Other Classifications" don't line up and so they are not easy to scan. Maybe look in future about having the fields vertically aligned. Not necessary for this release.
4) "My Classification" says "Provisioned/Approved Status", whereas "Other Classifications" says just "Status"... to keep all the same maybe just change them all to "Status"?

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

> "My Classification" is on on two lines, whereas "Other Classifications" are on one line each. Maybe put "My Classification" on one line too, so that they all have the same format. Also, we could add in the name of the curator or affiliation in the "My Affiliation" row so that all rows have the same information?

I actually thought about using just one line for "My Classification" but I was also concerned about a potential wrapping issues if the following _edge_ case happens:
![image](https://user-images.githubusercontent.com/6956310/45942357-f4ed6b80-bf96-11e8-91bf-05eabf46af95.png)

**Comment by wrightmw** [comment]
Looks great! Thanks @jimmyzhen

**Comment by jimmyzhen** [comment]
Included in the R22 release.
