### ISSUE TITLE
Display term name for phenotype when curator enters HPO term & copy this term name rather than ID for Copy function

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1585]
After a curator enters an HPO ID, return the term name (rather than the ID), on the form page and the View page.  

When using the 'Copy Phenotype' function, this term name should be copied and displayed (rather than the ID, or in addition),so curator can view which phenotype(s) to remove in the section to which the terms are copied.

( @ErinRIggs)

**Comment by courtneythaxton** [comment]
@wrightmw Input from the group would be good. 

I think the ID and the term name together would be the best to help with future AI, ML uses. If we take away the association of an HPO with a term then we lose utility. 

I could imagine something to the effect of 

**Presenting HPO:** HP:0001639 (hypertrophic cardiomyopathy), etc

**Comment by wrightmw** [comment]
@markmandell This is fully specified. We discussed this on the GCI WG today. The text shown above by @courtneythaxton is the format that was agreed.

**Comment by wrightmw** [comment]
Please confirm I have that right @courtneythaxton

**Comment by courtneythaxton** [comment]
@markmandell @wrightmw That is correct!

**Comment by markmandell** [comment]
@courtneythaxton @wrightmw 
Here is the instance for this ticket: https://1585-mm-displayhpoterms.demo.clinicalgenome.org/

**Comment by courtneythaxton** [comment]
Hi Mark,

I am adding@ErinRiggs and @jennygoldstein to review this ticket as well.

Courtney

**Comment by courtneythaxton** [comment]
Hi @markmandell 

I tried out this instance. I was not able to see the plain text in parentheses next to the HPO term, neither in the the "Edit Individual Info," the "Evidence Summary," or the "View individual Info" sections. See the image for the edit individual info tab with the HPO entries

I did the DICER1-progressive cerebello-cerebral atrophy  (MONDO:0016589) curation.

**Please let me know if I did something in error**
![Screen Shot 2019-09-16 at 12 55 13 PM](https://user-images.githubusercontent.com/32530005/64977395-4b774800-d881-11e9-8abc-0e3394be208b.png)

**Comment by markmandell** [comment]
Hi Courtney! The term names appear when copying down from Group -> Family/Individual or Family -> Individual

So when HPOs are entered from a Group, if the user wants to copy the HPOs for a Family associated with that group, upon click of the copy button, then the term names should append to the ids.

If you curated from Individual first, they wouldn't appear because there is no where to copy down from. Let me know if you would like to revisit the overall way this works. If it is agreed that we don't want to rely on the copy functionality to view the HPO terms, I can add a "Get HPO Terms" button that a user can click and then request the terms that way.

**Comment by courtneythaxton** [comment]
Hi @markmandell 

Thank you for the clarification, and for your work.

In thinking about your suggestion, I think that it might be nice to do a "get HPO terms" button. In general, the most used Case evidence is individual, so being able to see terms if there was no group or family would be useful.

@erinriggs @jennygoldstein @wrightmw What do you think?

**Comment by ErinRiggs** [comment]
Totally agree - the human readable terms need to be displayed regardless of whether or not they are ultimately copied.  If a "get HPO terms" button is the best way to achieve that, then let's go with that.

**Comment by markmandell** [comment]
Hi everyone! Just pushed the update to the instance with the "Get HPO Terms" button.
https://1585-mm-displayhpoterms.demo.clinicalgenome.org/

Let me know of any feedback! Users are still able to copy down the info from Group or Family, but  now it isn't reliant on that method to get append the terms to the id(s).

**Comment by ErinRiggs** [comment]
Thank you so much!  Adding HPOs numbers then retrieving the words worked well in the "Individual" section.  However, when I saved then tried to view the Evidence Summary, it looked like this (my case has the label "ere"):

[cid:4f0d5957-6ac9-4020-8f03-33e7d84e82be]
You can see there is a weird "note: term not found" added to the end of each of them.  Also, if possible, I'd prefer if the human readable term were first, and the HPO number were in parentheses, so like "Seizures (HP:0001250)."

Thanks,
Erin


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by markmandell** [comment]
Hi Erin,

Thank you for bringing that to my attention! I forgot to remove some previous code from the evidence summary where the terms are being requested as well.

In the case where the term is not found from OLS, is there an alternative note that you would recommend? For example, a successful retrieval would read "Seizures (HP:0001250)", but my first thought is "Term Not Found (HP:0001110)" would be inappropriate in this case, unless it looks fine to everyone else!

**Comment by courtneythaxton** [comment]
@markmandell 
Do you think there will be an instance where the use of an HPO ID will not retrieve the terminology or nomenclature? 

I do understand your point that if it happens it would be unfortunate, and we should have a plan. I"m not opposed to it stating "Term Not Found(HPO ID)" 

My next question is, that in these instances, are there any plans to "update" the HPO terms later through use of the Human Phenotyping Ontology API, or even the Monarch API ( I believe they also list the HPO IDs)? 
@wrightmw 
@ErinRiggs 
@jennygoldstein

**Comment by wrightmw** [comment]
@courtneythaxton We have to allow for the option within the interface logic, that for whatever reason a term is not found. The OLS may be down temporarily, for instance, or maybe the curator has typed in the wrong ID (in which case this would be a good error check).  I would advise curators to check the reason why a term cannot be returned. If it's because the OLS is down then perhaps they should try again later. But if a single term is not returning then perhaps they could look it up, and write it in themselves by overwriting the "Term Not Found"? 
As us automatically updating HPO terms later, we do have plans to implement automatic updates for APIs but this is a future feature and will not be ready for this ticket launch. Such automatic updates would include other changeable IDs and names, such as gene names, MONDO terms, etc...

**Comment by wrightmw** [comment]
This same functionality could be used in the VCI to complete this ticket: #1917

**Comment by wrightmw** [comment]
Kudos to @markmandell . This looks great. Looking forward to seeing it public in R32.

**Comment by cgpreston** [comment]
@markmandell this looks fantastic and I know it was a tricky issue to solve, great job!!

**Comment by wrightmw** [comment]
Released in R32
