### ISSUE TITLE
Change "Study type" Field (under Case-Control) to be Required

### ISSUE THREAD

**Issue by bryanwulf** [ClinGen/clincoded#1654]
To coincide with the format (SOP) of classifications published on ClinGen's public website (via the Data Exchange), the "Study type" field needs to be changed to a required field (or at least required in order to score the case-control evidence).

![image](https://user-images.githubusercontent.com/32915557/38889074-60f9f754-4232-11e8-83f4-4f0b69b14371.png)

**Comment by jimmyzhen** [comment]
@bryanwulf, please connect your #1709 PR to this ticket. I will go ahead

**Comment by selinad** [comment]
@bryanwulf this works in that the ability to score does not occur unless the study type field is selected.  I'm not sure how we missed testing this specific ticket, but would it be possible to add some text under the field title "* required to score this evidence".  Right now there is no feedback as to why score option doesn't appear.

**Comment by wrightmw** [comment]
@selinad @bryanwulf @jimmyzhen I don't remember ever testing this ticket. Eek! 
It definitely needs a "*" to mark it as required.
I wonder whether the correct workflow should be that scoring is still allowed (even when this is not selected) but when they click to Save they get the red warning box and warning text telling them that this is a required field. This is how we deal with required fields in other places?

Some explanatory text would be desirable for this release.  If we cannot add explanatory text in this release then I guess we will have to advise the curators when we send out the release note? Otherwise they will report this to us as a bug.

**Comment by jimmyzhen** [comment]
That's why I suggested we include this change in the next release ;)

**Comment by selinad** [comment]
@jimmyzhen my thinking was not to change behavior for this release, just to add a note as the error message etc. wasn't in there -- was not suggesting anything more complicated for R20.  It was to avoid confusion of there being no error and no way to score unless that filled out.
