### ISSUE TITLE
Change the PAK3-MONDO:0019181 GCI record to PAK3-MONDO:0020119

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1732]
A curator would like to change the MONDO ID (as per title) for this GDM: 0ed13f17-9636-4e84-b6cd-1ac51fdc5a8c

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw,

I have changed the disease from **MONDO:0019181** to **MONDO:0020119** from the **Gene-Disease Record** in question.

Because the record's classification also has a snapshot, so I have also changed the disease info (including MONDO ID, term, definition, etc.) that is embedded in the snapshot.

Please ask the curator to verify the changes. Thanks.
