### ISSUE TITLE
Display CIViC curated VHL variant evidence in the VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1769]
~150 VHL variants from CIViC are now available via API from the Baylor Evidence Registry. It is planned to access the evidence for these variants on the fly via the API for each of these variants for display in the relevant sections in the VCI.

**Comment by GenomeDeb** [comment]
The data available from Evidence registry is a SEPIO compliant JSON file. 

Should I specify which exact fields from that should be imported to the VCI?  

What matters is the following
1. evidence codes (criterion -> "label") in the JSON file 
2. the evidence statement ("comment" ) in the JSON file 
3. the associated PMIDs (traceableAuthorStatement) in the JSON file though I can't tell if every evidence code (like PM1) has a traceableAuthorStatement or if some traceableAuthorStatement are present without evidence codes (likely so, because people may add information about VHL but not know to add an evidence code like PM1 in the text). 
4. the calculation of pathogenicity that Ronak has for the variant via the Pathogenicity calculator. I am guessing thats "outcome" where the discription is "final call from reasoner software"  at the top of the JSON doc. 
 "outcome": {
    "@id": "https://loinc.org/LA6668-3",
    "id": "LN:LA6668-3",
    "type": "Significance",
    "label": "Pathogenic",
    "description": "Final assertion for the variant as generated by the reasoner software."

Right now I can't see where the information on the actual CIViC curator is being pulled in. We may want that too. 

All for now.

**Comment by wrightmw** [comment]
@GenomeDeb Welcome to GitHub! Love your username. Thanks making a start on this. We're super grateful for your input. 

Wr to your question, yes please do specify which exact fields from that file should be imported to the VCI?

**Comment by GenomeDeb** [comment]
Further thoughts. 

Will be a one time dump, or ongoing? I think it should be ongoing. 

Will this be for VHL only, or for any variant with germline information in CIViC? I think it should be for any variant with germline info in CIViC. 
I would want to distinguish between the interpretation from the VCI curator and that generated by CIViC. 

Ideally it would be like this: On the page with the ClinVar summary, I'd like to see that box from the Evidence registry summary too, showing the final pathogenicity calculated, the tags and perhaps the number of evidence items and PMIDs. 

When I go to an individual evidence code (like PM1 for example), then it would have the PMIDs/papers showing under that code, showing that they came from CIViC via Evidence Registry. I'd like to see the evidence statements from CIViC with the PMID and if there was an ACMG code from CIViC then to see what that evidence code was too. However, I wouldn't want the PM1 box to be auto filled with met etc, because I'd still want to evaluate it and do that. But their evidence code, the papers and evidence statement would be there.  

CIViC has discussed changing their evidence item structure so that users could tag the ACMG evidence code as a separate field, whereas currently that is only available for an assertion (which is a summary of information about evidence items.). I think they need to allow evidence code tagging at the Evidence Item point, then

**Comment by cgpreston** [comment]
LDH has launched, next step is to review specifications with CIViC team December 5, 2019

**Comment by wrightmw** [comment]
Will be addressed in #2177 as part of External Evidence Sources pipeline
