### ISSUE TITLE
Update "Save" button behavior on view-only pages (Case-Control and Proband Individual)

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1781]
The **Save** button on the Case-Control's view-only page should address the following 2 case scenarios:
1. When the user selects the **Study Type** but doesn't score the evidence. In this scenario, on the _view only_ Case-Control evidence page, clicking on the **Save** button does nothing. It gives poor user experience and we should display a message saying something like "A score is required to save" when the user clicks on the **Save** button.
2. When the user doesn't select the **Study Type**. In this scenario, IMHO, that **Save** button should be disabled since the user can't select a score anyway. And the message in the yellow box shall also suggest to the user to go back to the _edit_ evidence page if scoring is needed. I think, to the user, this is more intuitive.

This change request is referencing to https://github.com/ClinGen/clincoded/pull/1767#issuecomment-424062558 and https://github.com/ClinGen/clincoded/pull/1767#issuecomment-424066941

**Comment by bryanwulf** [comment]
Scenarios to simply disable the **Save** button (because data can't be changed):
1) Case-Control evidence without a **Study type**
![image](https://user-images.githubusercontent.com/32915557/60127049-2bcdf900-9744-11e9-8e2d-da135db34cd0.png)

2) Proband individual without variants
![image](https://user-images.githubusercontent.com/32915557/60127189-6fc0fe00-9744-11e9-95f4-b87aad54c41a.png)

Scenarios to display a warning message when **Save** button has been clicked:
1) Case-Control **Score** has not changed
![image](https://user-images.githubusercontent.com/32915557/60127446-14434000-9745-11e9-834a-eb5fb3177ade.png)

2) Proband individual status/scoring has not changed
![image](https://user-images.githubusercontent.com/32915557/60127595-6a17e800-9745-11e9-9780-6be400f6e193.png)

**Comment by gcheung-SF** [comment]
@wrightmw , @cgpreston , want to check with you if the following change is reasonable for the scenarios to display a warning message when Save button is clicked but no field has been changed.  Currently, user can save a score even no field has been changed as long as status/score is not set as "No Selection" which causes the data be saved and then redirect back to the gene-disease curation page.  With the new change, when Save button is clicked, a warning message is displayed and user stays at the view-only page.  User has to make a change in order to save data and redirect back to gene-disease curation page, or click on "luggage" icon to go back.  The change is for Case-Control, Proband Individual, and Experimental Data view-only pages.  I have the change on my local app if you want to take a look.  Thanks.

**Comment by gcheung-SF** [comment]
@wrightmw , @cgpreston , The fix is now on https://1781-gc-cc-ind-exp-save.demo.clinicalgenome.org/.  Please let me know if behavior needs to be changed.  Thanks.

**Comment by wrightmw** [comment]
@gcheung-SF Looks good! Thanks!
