### ISSUE TITLE
FDP - functional assay data

### ISSUE THREAD

**Issue by arturolp** [ClinGen/clincoded#1794]
Placeholder... waiting for input from Michael Iacocca

**Comment by arturolp** [comment]
Functional assay experimental data needs to be shown in this section of the VCI
<img width="1392" alt="screen shot 2018-11-13 at 12 27 57 pm" src="https://user-images.githubusercontent.com/691185/48441156-aa3ed300-e73f-11e8-81b9-89708f6ebda7.png">

**Comment by bryanwulf** [comment]
In terms of retrieving source data and saving it in a local DB (when necessary), our use of population data may be a helpful template. Mainly, the data is retrieved once when viewing a variant (e.g. starting a new variant curation) or interpretation (e.g. following a link under **My Variant Interpretations** on the dashboard) and saved (in a raw JSON format) when saving a relevant criterion evaluation.

To retrieve functional data, a request for linked data (for a given variant, using its Allele Registry ID) will be made to the Linked Data Hub (LDH). Here's an example (for CA058940) of the structure of the response (partially truncated for clarity):
[LDH-data-structure.json.txt](https://github.com/ClinGen/clincoded/files/3292456/LDH-data-structure.json.txt)

If a successful response includes an array of functional data impact statements (`data.ld.AlleleFunctionalImpactStatement`), then functional data exists for the variant (with each element representing an experiment). In order to retrieve the bits of functional data not provided by the LDH (materials, methods, etc.), each element should include an `entIri` field with a value representing a data request URL to the Functional Data Repository (FDR). Here's an example (for the first impact statement, 318131711) of the structure of the FDR's response (partially truncated for clarity):
[FDR-data-structure.json.txt](https://github.com/ClinGen/clincoded/files/3292539/FDR-data-structure.json.txt)

A successful response should include the rest of an experiment's functional data (at `data.ld`). Technical note: we may need to also retrieve an experiment's source article (assuming we have the PMID at `data.ld.Source.entId`)

All of the requested data will need to be pulled together into a single JSON object for temporary (while the user browses the variant/interpretation) and, potentially, permanent (saved to the DB when the user evaluates BS3 or PS3) storage. Technical note: the schema for our evaluation objects/documents has a placeholder for linking to "functional" objects/documents.

Here's the most current mockup of how the functional data could be presented within the **Experimental Studies** panel:
![image](https://user-images.githubusercontent.com/32915557/59544926-f4518800-8ecb-11e9-936a-dc88db35ad50.png)

The simplest layout to handle multiple articles, each with multiple experiments, would be to list them vertically. However, if there's another layout that's equally simple to read and understand, but reduces the amount of vertical space required, it would certainly be considered.

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FDP v2 - Individual Curation](https://trello.com/c/a2Z9ALJp/46-fdp-v2-individual-curation)

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FDP - V1 Bulk Functional Data Upload](https://trello.com/c/SBEdNS13/6-fdp-v1-bulk-upload)

**Comment by wrightmw** [comment]
Release 31
