### ISSUE TITLE
Enable approving and publishing GDM with more inheritance patterns than currently available

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1809]
Hi @jimmyzhen @wrightmw @erinriggs @marinadistefano @jennygoldstein

Currently the only gene-disease relationships (GDMs) allowed to be approved and published are those that have an inheritance categorized as AD, AR, X-linked. In cases where the gene has "No genetic evidence" the mode of inheritance will not necessarily be known, yet the GCI requires an AD, AR, X-linked, as an inheritance of "unknown" is not allowed for approval and publication. 

**_Can we come up with a plan to enable publication in these cases, in which the MOI (inheritance) is truly unknown?_** 

FYI, the FAO group needs to publish GDM for an upcoming publication that is being drafted and the currently cannot publish three of them due to this lack of knowing an MOI due to "no genetic evidence" of the gene is disease.

Furthermore, enabling the ability to score on semi dominance (in cases in which both AR and AD dominant inheritance represent a spectrum of disease severity for one disease would also be nice, and would work with the Lumping and splitting guidelines. 

Thanks
@courtneythaxton

**Comment by wrightmw** [comment]
@courtneythaxton thanks for creating this ticket. I think part of the issue here is that the website uses ontology for MOI, and unknown is not an option? @sgoehringer can you confirm this? Thanks.

**Comment by courtneythaxton** [comment]
Thanks @wrightmw . I definitely understand wanting to use ontologies, and this may be a question that we need to present to the ontology being used, so we can create these choices. Which ontological entity are we using for inheritance? Monarch?

**Comment by sgoehringer** [comment]
Yes, @wrightmw is correct about having it connected in the ontology and it doesn't seem that Monarch supports an unknown type.  Lets loop @tnavatar into the mix for him to comment.  We should be able to extend things (or seek for one to be created).  Tristan will better able to project downstream obstacles when it comes to the data modeling and data sharing.

**Comment by courtneythaxton** [comment]
Thanks @sgoehringer @wright and @tnavatar for taking a look into this !

**Comment by tnavatar** [comment]
We're using Human Phenotype Ontology for inheritance terms. We can incorporate other ontologies for terms like semi-dominant (or ask HPO to include it), but probably not for 'unknown inheritance'. For various reasons, ontologists are generally resistant to adding terms about lack of knowledge of a concept. One can always ask, but I'm guessing they would not be happy to add a concept for 'unknown mode of inheritance'

One possibility would be to accept submissions with no associated mode of inheritance (in an ontological sense, this is the best way to represent 'unknown'). Another possibility would be to invent a term for internal use in our own 'ontology' (we do this for some concepts already anyway). I would probably prefer the former but would be 

One question either way is how to go from 'unknown' to 'known' (when more evidence is discovered regarding an association, say). My understanding is that the gene, phenotype, and mode of inheritance are all fixed in a record in the GCI. Will there be a way to change the mode of inheritance in the GCI in order to accommodate this change when it occurs?

**Comment by courtneythaxton** [comment]
I might suggest that we ask for something like "undetermined mode of inheritance" as a possible nomenclature. 

We will create a ticket on HPO site, and I will link the issue ticket number.

@jimmyzhen @wrightmw @courtneythaxton @marinadistefano @erinriggs

**Comment by courtneythaxton** [comment]
HI all, I created tickets in HPO for undetermined mode of inheritance #4238 (https://github.com/obophenotype/human-phenotype-ontology/issues/4238)

and also added Semidominant inheritance, issue #4239 (https://github.com/obophenotype/human-phenotype-ontology/issues/4239)

**Comment by tnavatar** [comment]
I think that Peter's suggestion to use the higher-level term 'mode of inheritance' when the mode of inheritance is unknown would probably work best from a data representation perspective (certainly since Peter is far more an expert on his own ontology than I am). Downstream I'll need to consider the most appropriate way to override the label on the website, since I'm guessing that you'll want to display 'Unknown'  rather than 'Mode of Inheritance' there, but I'd rather get the incoming data right first.

When the curation is selected, usually the score appears in either the 'dominant' or 'recessive' scoring blocks, depending on the data received. I'm guessing that 'unknown' would be used only when there's no data to present in either category? What about semi-dominant? Would that be 'dominant' for scoring purposes (since the phenotype is at least detectable in partially affected individuals?

**Comment by ErinRiggs** [comment]
?I think what we discussed yesterday was:


-For "Unknown" MOI, typically there will be nothing scored in either block, and simply a free text description summarizing the curation (these are typically going to be disputed or refuted).  Marina, please correct me if I am wrong.


- For semi-dominant, we would want to have the ability to score in both the AD and AR scoring blocks (Courtney/Jenny, correct me if I am wrong).


-e


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by jennygoldstein** [comment]
That sounds good to me.


Jenny


________________________________

**Comment by tnavatar** [comment]
OK, I think the website will support that without a problem (@sgoehringer , please correct me if that's not the case). I think that the website would expect to see HP:0000005 in the case where no mode of inheritance is specified, and whatever term gets created to describe semi-dominant in the other case.

**Comment by sgoehringer** [comment]
The JSON message that is sent to the DX and used on the site is currently a text string like "Autosomal dominant inheritance (HP:0000006)”.  We parse this string and look for the (HP:0000006) to connect the HP term in the database but the report simply prints whatever the text string you send on the report page.  As long as a valid HP ID (HP:0000005) we should be good and the text string can be whatever the group want to display.

Does this help?

Scott



Scott Goehringer
t: 781-453-2960
On Twitter: @srgoehringer <https://twitter.com/srgoehringer>


IMPORTANT WARNING: The information in this message (and the documents attached to it, if any) is confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken, or omitted to be taken, in reliance on it is prohibited and may be unlawful. If you have received this message in error, please delete all electronic copies of this message (and the documents attached to it, if any), destroy any hard copies you may have created and notify me immediately by replying to this email. Thank you.

**Comment by courtneythaxton** [comment]
This sounds good to me, especially if there is no extraneous coding that needs to be done to change the text stream to what we would like displayed. 

We may want to add in the Gene curation SOP that the use of the HP:0000005 Mode of inheritance was our choice for MOI with undetermined etiology. That way the text is somewhere in print that we recognize that we are using a broad term and changing the textual definition. Just for transparency. Should we would consider adding a note or disclaimer anywhere else?

**Comment by ErinRiggs** [comment]
?Ok great.  Courtney, since it sounds like Peter's suggestion will work, would you mind just circling back with him on the original GitHub ticket and letting him know that we will go forward with that parent term?


Thanks!

Erin


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by courtneythaxton** [comment]
Done. Thank you all for your quick response to this!

Courtney

**Comment by courtneythaxton** [comment]
Update to all, @jimmyzhen @wrightmw @marinadistefano @ErinRiggs @jennygoldstein @sgoehringer @tnavatar 

The Semidominant MOI should become HP:0032113, on the HPO browser soon. I have message Peter Robinson of HPO to get this pushed. Eventually we will need this MOI enabled for curating and scoring in the GCI. The same for undetermined MOI.

I will create new tickets.

@courtneythaxton

**Comment by tnavatar** [comment]
Thanks for the update Courtney—I’ll make sure to pull the updated HPO data into the website when it’s available. I’ll look for an update on this ticket  or HPO #4239 to know that its ready to go.

Cheers,

—Tristan
