### ISSUE TITLE
All GDMs Page (UI)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#186]
Under tools, there is a link to view all GDMs (logged in curator + all other GDMs).  Currently, this goes to the database table (feel free to edit this terminology) and includes test data.  We need a UI page that displays all "real" GDMs (no programmer test data), regardless of curator or GDM status.

**Comment by forresttanaka** [comment]
@selinad @tsneddon @wrightmw 

Let me know if you want to see the same information as the dashboard shows (title, status, creation date) or if you wanted more.

**Comment by tsneddon** [comment]
@forresttanaka - please add creator, participants and date last edited.

**Comment by forresttanaka** [comment]
Attaching a Photoshop mockup. Hovering over a row darkens its background color, and clicking anywhere on a row takes you to Record Curation for that GDM. Clicking the G:D:M column header I guess would sort by Gene? I don’t have sorting on Participants since it didn’t make sense to me.

**Comment by wrightmw** [comment]
Looks great. We love the buttons and the overall layout.

Could you try putting extra spaces between the Gene symbol and the disease... I think it might read better?

Selina and I were thinking that the 'last edited' and the 'participants' columns should be switched so that the dates aren't right next to each other.

Cheers,
Matt & Selina

**Comment by tsneddon** [comment]
Looks great, although I might lobby to switch the Creator and Created columns so that the participants remain in the last column for easy viewing by eye... I don't mind either way!

**Comment by selinad** [comment]
How about:

Participants | Last Edited | Creator | Created

that would highlight the Participants, split the dates and maybe be the order of importance for the person viewing

Selina & Matt
@tsneddon we will wait for your feedback!

**Comment by forresttanaka** [comment]
Attaching a *very* early stage implementation, and a question: We would normally get to this page from the dashboard. Should there be a button somewhere to go to the dashboard, or just rely on the usual house icon?

**Comment by tsneddon** [comment]
@selinad - sure.

**Comment by forresttanaka** [comment]
Spun up a [new instance](https://186-ft-all-gdms-page-0ebd933-fytanaka.demo.clinicalgenome.org/gdm/) that visually and functionally should be pretty close.

##### Remaining known changes:

* Enable the dashboard link to this page.
* Put in a gap below the table when the table is taller than the browser window.
* When you’re not logged in, the page should display the “Not available” page. Right now it just shows an empty table because this uses the usual collections view (same URI it used when it displayed the old table) to avoid having to GET each GDM’s data. I’ve asked @kgliu0101 to look into this as well, as I didn’t see how to do this.

##### Questions:

* Should the status column of the table be sortable?
* Should we have a button to go back to the dashboard? When using this, I didn’t feel a need since the house button in the header is there and would do the same thing, but I might not be in the right position to judge.

##### Other notes

* The GDM column sorts by gene only.
* Filtering searches the gene and disease fields only.

![all-gdms](https://cloud.githubusercontent.com/assets/1181324/10734595/4b925f6c-7bc1-11e5-957c-ce2c94a2c739.png)

**Comment by forresttanaka** [comment]
I stopped the instance, but it’s still available. Just start it from the EC2 dashboard, or have me restart it.

**Comment by selinad** [comment]
Thanks, @forresttanaka - this looks great!  It sounds like we are going to hold for production, but I'd be happy to look at the instance (I'm sorry I didn't get a chance today).

In answer to your questions:
* I think it would be great if the status column were sortable.
* I don't think we need a Dashboard button - the Home button is up there, as you mention

Searching by gene and disease is great.  

Q: how would you get to page if not logged in?

**Comment by forresttanaka** [comment]
If you’re not logged in, you can still go to the URL directly (```/gdm```). I’ll spin up another instance later with sortable status. I implemented it already, but after I spun up the last one.

**Comment by forresttanaka** [comment]
[New instance](https://186-ft-all-gdms-page-1865f0d-fytanaka.demo.clinicalgenome.org) with the status column sortable, and the link from the dashboard enabled.

**Comment by wrightmw** [comment]
@forresttanaka Looks great! You've done a great job. I wonder whether curators might like to be able to search the 'Gene -Disease' column using either the Gene or the Disease? However I appreciate that the columns are sorted based on the first character and so this might not be a simple task. If @selinad and @tsneddon agree, then I guess this would be a ticket for a future build?

**Comment by forresttanaka** [comment]
You mean sorting by Gene _or_ Disease? Would have to think a bit on what the UI would look/work like. Maybe the little sorting icon after Gene and another after Disease in the header?

**Comment by wrightmw** [comment]
Yes, I mean sorting by Gene or Disease. I agree with you that putting the little sorting icon after Gene and another after Disease in the header would be a good way to represent this.

**Comment by forresttanaka** [comment]
OK, we’ll see what the others think. A bit tricky since the other columns control sorting by clicking anywhere in that column’s header, where this one would be by clicking right on the sorting icons. Probably fine, but something to think about.

**Comment by selinad** [comment]
Wow @forresttanaka - it really does look great!  

I see @wrightmw 's point, but we could wait and get feedback from users - the filter option allows one to find a disease or a gene.

The pink might be a bit strong - it seems much more drastic than the other icons in color.  Could it be an empty orange?  Then "in progress" has a dot in middle.  I would almost lean towards having one color for everything, except maybe the final.

e.g. - first 4 below are all one color (the dark gray or the orange)
* Created: empty circle
* In progress; dot in middle
* Provisional: half colored
* Draft; check mark
* Final: green check, as you have it.

I find the combination of colors and symbols hard to process.

Are you able to change the header blue to be consistent with the blue headers in the rest of the site, or is it set?

Otherwise, it's really fantastic!

**Comment by forresttanaka** [comment]
We’re holding off on this for now until after production gets released?

The one thing not yet done, and I have no idea if we can, is to go to the “Not available” page if you’re not logged in.

![screen shot 2015-10-28 at 15 32 37](https://cloud.githubusercontent.com/assets/1181324/10805189/25a2fca2-7d89-11e5-8f3a-e1f7b6e16141.png)

**Comment by selinad** [comment]
This is easier for me to process.  As long as it doesn't look to much like a Consumer Reports review for others!  I like it.  Thanks for changing out the blue in the header as well!

I'd also be OK with orange as the one color if people want it to be a bit more vibrant.

Thanks @forresttanaka !

**Comment by wrightmw** [comment]
@forresttanaka Looks great. @selinad I agree that it looks better without the mix of colors but all grey looks a bit washed out, they might stand out better with a splash of orange. Or maybe they'd look garish.

**Comment by selinad** [comment]
I could go with a 'splash of orange!'

**Comment by forresttanaka** [comment]
Just so you know, without looking carefully, I can’t really tell the difference between the orange and the green because that’s how my genes roll. But with the different icons, it should be OK.

![screen shot 2015-10-28 at 16 09 53](https://cloud.githubusercontent.com/assets/1181324/10805874/6b5b39ee-7d8e-11e5-936c-7699bc42b55c.png)

**Comment by wrightmw** [comment]
@forresttanaka Brilliant! @selinad I think the orange looks great.

**Comment by selinad** [comment]
Agreed!  (on both counts!)

**Comment by forresttanaka** [comment]
New instance that’s up to date with dev: http://186-ft-all-gdms-page-f8daec6-fytanaka.instance.clinicalgenome.org/

**Comment by forresttanaka** [comment]
Not entirely convinced I spun up the right version last time. This one definitely is:

http://186-ft-all-gdms-page-ea1d479-fytanaka.instance.clinicalgenome.org/

**Comment by kilodalton** [comment]
@forresttanaka: Filter only appears to work on gene and disease... is this expected? If so, The "Filter" text message should say "Filter by Gene or Disease". But I think people will want to also filter on mode, creator and participants . Can we add that in?

**Comment by forresttanaka** [comment]
@selinad @wrightmw Do you want what @kilodalton mentioned in the last comment?

**Comment by forresttanaka** [comment]
If this is wanted, I suggest making a new ticket for it. It went through lots of testing already without that request, and I’m on ENCODE right now.

**Comment by kilodalton** [comment]
@forresttanaka We'll make a new ticket

**Comment by kilodalton** [comment]
@selinad @wrightmw I can change "Filter" in the search box to "Filter by Gene or Disease" if you would like that and @forresttanaka doesn't have time to add that in.

**Comment by wrightmw** [comment]
I was just looking into this. I definitely think that users might want to be able to filter by "Gene or Disease"...currently is filters alphabetically so in effect it is filtering by the Gene name only.

**Comment by kilodalton** [comment]
@wrightmw It does filter by disease as well already. I was just suggesting a clarification in the "Filter" box (just changing the grey default text)

**Comment by wrightmw** [comment]
It's ok.. sorry for the confusion... I was talking about the sorting feature in the table. The Gene-Disease column can be sorted ascending or descending alphabetically, so in effect it is always sorting based on the Gene symbol but cannot be sorted by the Disease. @forresttanaka has already informed me that this would not be simple, so scratch that. 
Wrt to the filter, since they user can only filter by gene symbol or disease then I agree that it would be appropriate to have 'Filter by Gene or Disease' for the grey default text in the filter box.

**Comment by forresttanaka** [comment]
To be clear, sorting (not filtering) on Gene _or_ Disease wouldn’t technically be that difficult. Working out the UI for it might be.

**Comment by selinad** [comment]
@forresttanaka this instance looks great to me! (added a R3 ticket for how creator name displayed)

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
