### ISSUE TITLE
REVEL data "not found" in VCI

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1864]
ClinVar VariationID: 21134 should return data but is showing "Not Found" in the population tab.

**Comment by wrightmw** [comment]
Nor these: ClinVar IDs: 283323, 579061, 456382

**Comment by bryanwulf** [comment]
The VCI was failing to display REVEL data because there was a fatal error during the processing of data retrieved from MyVariant.info. This error was the result of a pair of column name changes by dbNSFP (from the December 8, 2018 update on https://sites.google.com/site/jpopgen/dbNSFP):
phyloP20way_mammalian to phyloP30way_mammalian
phastCons20way_mammalian to phastCons30way_mammalian

which MyVariant.info incorporated into their February 26, 2019 release (http://docs.myvariant.info/en/latest/doc/release_changes.html).

The code to process and display the modified columns was updated and both the test and production sites were patched.

**Comment by wrightmw** [comment]
Done! Thanks @bryanwulf
