### ISSUE TITLE
Use MANE transcripts for Variant titles

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1868]
Currently Variant titles are derived via the following formula:
1. ClinVar preferred title
2. If no 1. then title based the single canonical RefSeq transcript from Ensembl VEP
3. If no 2. then title based on GRCh38 genomic HGVS

This would change to incorporate the MANE transcripts:
1. ClinVar preferred title
2. If no 1. then title based on the RefSeq transcript MANE from CAR
2. If no 2. then title based the single canonical RefSeq transcript from Ensembl VEP
3. If no 3. then title based on GRCh38 genomic HGVS

**Comment by bryanwulf** [comment]
@wrightmw Is the following variant (CA321211) an example of one with a MANE transcript?
http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/by_canonicalid?canonicalid=CA321211

**Comment by wrightmw** [comment]
@bryanwulf Yes, that variant does have a MANE transcript.

**Comment by wrightmw** [comment]
Currently Variant titles are derived via the following formula:
1---- use "ClinVar preferred title" if present
2---- if there is no "ClinVar preferred title" then use title based on the "single canonical RefSeq transcript from Ensembl VEP"
3---- if there is no "ClinVar preferred title" and no "single canonical RefSeq transcript from Ensembl VEP", then then use title based on "GRCh38 genomic HGVS"

This would change to incorporate the MANE transcripts:
1---- use "ClinVar preferred title" if present
2---- if no "ClinVar preferred title" then use title based on the "RefSeq transcript MANE from CAR"
3---- if there is no "ClinVar preferred title" and no  "RefSeq transcript MANE from CAR" then use title based on the "single canonical RefSeq transcript from Ensembl VEP"
4---- if there is no "ClinVar preferred title" and no  "RefSeq transcript MANE from CAR" and no "single canonical RefSeq transcript from Ensembl VEP", then then use title based on GRCh38 genomic HGVS

**Comment by wrightmw** [comment]
@shaungc-su 
Where the "RefSeq transcript MANE from CAR" is applied for the title then the "MANE preferred transcript" is obtained from the CAR and this is used to transpose the variant title by including the "Gene" and "Amino-acid change" (note: the "Amino-acid change" will only be available for protein-coding regions and so this will not be available for all variants).

So, for instance the MANE transcript for the example above (variant: CA321211) returns NM_002496.4:c.64C>T as the "MANE preferred transcript" which should be transposed as:

NM_002496.4(Gene):c.64C>T (Amino-acid change)

which in this example is:
NM_002496.4(NDUFS8):c.64C>T (p.Pro22Ser)

**Comment by shaungc-su** [comment]
Some updates -

Made a quick confirm with Matt previously about the title and data sourcing logic. Below is for record & summary. Please feel free to provide any feedback.

### Variant Title format

 * When both gene name and protein effect information are available, the format will be `NM_002496.4(Gene):c.64C>T (Amino-acid change)`.
 * When gene name is unavailable, the format will be `NM_002496.4:c.64C>T (Amino-acid change)`.
 * When protein effect is unavailable, the format will be `NM_002496.4(Gene):c.64C>T`.
 * When both gene and protein effect not available, will fall back to hgvs format `NM_002496.4:c.64C>T`.

### Data Source

Targeting the use case where user presses the button "Add CA ID" for, e.g., a family evidence.
- (Curation) The variant CAR does not contain MANE information, so we are turning to 2 external data sources: Link Data Hub (ldh) and genomic CAR (`https://reg.genome.network/gene/<gene id>`), both of these contain MANE info. Reason to include genomic CAR is after talking with Sai, LDH is still in the process of filling up data. After trying [several sample variants](https://docs.google.com/spreadsheets/d/1Qg70hMGpb83B3ICji2ABJJ_O8P-QK6YPpPLqlMLSbGI/edit#gid=0), seems like many of them are not in LDH yet. Genomic CAR will help filling up the data gap; however, the extra fetching work will add more latency (worst case trying all variant's transcripts and fetching their gene). Will keep an eye on this and see if the wait time (user hitting the button "Retrieve from CAR") is acceptable.
- (Engineering) LDH's CORS is not working, so it's more preferable to make the request through our backend. Fortunately Howard's work #1794 covers this. After consulting Bryan, since that ticket is still under review, I introduced the relevant file changes, but not committing them to avoid file conflict, so the final PR for this ticket will not include the file change. For testing, I'll upload the relevant files to the test instance.

### Data storage

- Shadowing to a previous ticket #1676 done by Jimmy similar to this ticket.
- As #1676, we will store the preferred title of MANE transcript for this ticket, which contains info of transcript id, gene symbol, amino-acid change name and protein change.
- Since adding a nested field containing all MANE transcript-related information is not trivial in terms of schema change, I will follow the pattern of #1676 to just store the preferred title for now. In case other transcript info like `coordinates`, `geneNCBI_id`, etc has a use case, please let me know.

**Comment by wrightmw** [comment]
@shaungc-su 
Note: When gene name is unavailable, then there will also be no "Amino-acid change" so the format will be NM_002496.4:c.64C>T

**Comment by shaungc-su** [comment]
@wrightmw I see, will apply restriction to reflect this.

**Comment by wrightmw** [comment]
@shaungc-su maybe if there is no "Gene" then can be no MANE transcript so it would skip to option 4---- if there is no "ClinVar preferred title" and no "RefSeq transcript MANE from CAR" and no "single canonical RefSeq transcript from Ensembl VEP", then then use title based on GRCh38 genomic HGVS

**Comment by shaungc-su** [comment]
@wrightmw Just want to check in with you on the tooltips of the title, and see if we want make some changes here:

![Screen Shot 2019-12-09 at 4 45 10 PM](https://user-images.githubusercontent.com/57968339/70485286-5cf87680-1aa3-11ea-9cb8-37e1f8ec43b8.png)

As you can see, the tooltip describes the criteria of how preferred variant title is yield. Since we are incorporating MANE transcript in, I guess we might want to change the text?

**Comment by shaungc-su** [comment]
As mentioned in today's meeting, below is a benchmark of current LDH + Genomic AR approach.

LDH should be an optimal source for MANE, as it gives the MANE transcript for a variant w/o additional query; unfortunately, many variants can't be found in LDH yet, but we can expect LDH to fill up more data in the future. 

As a workaround, we use genomic AR where MANE info is also available. However, after querying CAR (variant AR), we have a list of Allele transcripts but we don't know which one is MANE. We extract the unique set of genes from the transcript list, and query each gene against genomic AR one by one. 

This raises concern about increased latency due to a linear amount of queries. Fortunately, after discussing with @wrightmw , there will only be a maximum of 4 genes associated with a variant, and the case of 4 genes is extremely rare. We can confidently conclude it should be a constant amount of queries (no more than 4).

But even if we know the worst case is 4 genes, how's the latency look like? Looking at the below screenshot, the overall elapsed time from clicking "Retrieve" button to the interface responding, is around 3 seconds. As you can see, even if we are doing 4 genomic AR queries, they are still a small portion of 250ms, versus the overall 3 seconds. 


![Screen Shot 2019-12-11 at 2 01 26 PM](https://user-images.githubusercontent.com/57968339/70665066-9c000680-1c20-11ea-8812-9a272481c89f.png)

The predominant factor of latency comes from the ensembl query (where canonical transcript info is retrieved). Latency can be dependent on current network condition, distance from the physical server location, the way the team host the server, server processing time, data size, etc.

Seems like the latency issue is little at this point, but Let me know what you think -- thanks!

**Comment by wrightmw** [comment]
@shaungc-su To clarify your point about "a maximum of 4 genes associated with a variant" written above. The CAR caps the number of genes returned at 2, so in all instances there will be either 0, 1, or 2 genes associated with a variant. There could outlier complex loci with more than 2 genes associated ... but the CAR caps at 2 genes, so maybe we should do the same?

**Comment by shaungc-su** [comment]
@wrightmw Indeed, what you said let me think of a question - MANE is at transcript level and is singular among other transcripts of that variant, but because of the way we do cross-query here - we locate a gene w/ MANE first, then try to go back to the transcript. But if the gene covers multiple variants, the MANE we found in genomic AR could be from another variant, so that result may not be what we want -- just my hypothesis, is that understanding correct? But then, the genomic AR data only has one MANE entry, the data structure does not accommodate a list, so that kind of contradicts my hypothesis and I'm not sure if I'm understanding it correctly.

I wonder how LDH handle this issue. Since they seem to be able to give a single MANE transcript for a variant.

Current:
- User input CA ID, then query CAR (variant AR)
- Query LDH by CA ID, if found a MANE transcript id (in form of hgvs prefix like `NM_001184727.2`) then we're cool
- Otherwise query genomic AR. Collect all genes in transcripts (from CAR). Query each gene and see if MANE exists. **As soon as we found a MANE-marked gene, we stop, and use `MANEPrefRefSeq.id`**, which looks like a hgvs prefix, e.g., `NM_001184727.2`.
- If we get the MANE transcript id (in form of hgvs prefix like `NM_001184727.2`), either from LDH or genomic AR, we go back to CAR transcripts, try to match their hgvs of the same prefix. **As soon as we found a transcript whose hgvs prefix matches the MANE transcript id, we stop and take that transcript info** to form a MANE-preferred title.

Change:
- User input CA ID, then query CAR (variant AR)
- Check gene amount first. If 0-1, then we proceed with current method, query LDH, and possibly genomic AR if LDH has no data.
- If got 2 or more genes in the CAR transcript list, we abort the MANE-transcript part and don't store `MANETranscriptTitle` for variant.

@wrightmw Does the change make sense to you?

**Comment by cgpreston** [comment]
Testing notes: 
* Testing title preference 1: Variant in ClinVar 
    * Choose any variant in ClinVar 
* Testing title preference 2: Testing Variants with no ClinVar title but do have a MANE Preferred transcript: 
   * CA501087, CA5404427, CA862193305
* Testing title preference 3: 
   * CA352139638
* Testing title preference 4: 
   * C862193305, CA913184818

**Comment by wrightmw** [comment]
Additionally, when testing preference 3... I used CAID: CA430030719, which is a non-coding RNA... and gave the following title:

![Screen Shot 2020-01-24 at 4 46 02 PM](https://user-images.githubusercontent.com/15131169/73113487-16cb6b00-3ec9-11ea-86f3-a716edabcb38.png)

@shaungc-su Where there is no protein data, such as in this example, then preferably this would be entirely absent in the title. E.g in this case the title would be:

NR_033979.2(HAGLR):n.3798T>A

But, I don't think this a showstopper for this ticket.

**Comment by shaungc-su** [comment]
@wrightmw 

I can confirm reproducing this problem of "undefined" in the amino acid change name.
After investigation, this is generated by the canonical transcript title. Indeed, as Christine mentioned this is a test case for preference 3 (no ClinvarVariantTitle, no MANETranscript, has canonicalTranscriptTitle).

As the fix is trivial I will fix it here. Once the updated test instance is ready I'll ping you in slack.

**Comment by wrightmw** [comment]
Followed testing steps and included CA430030719 as an ncRNA example. All worked. Great!

**Comment by cgpreston** [comment]
Tested on R32 release candidate with 3 examples, all look great!

**Comment by wrightmw** [comment]
Released in R32
