### ISSUE TITLE
Move interpretations from individuals to Phenylketonuria affiliation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#1878]
NM_000277.1(PAH):c.965C>G (p.Ala322Gly)
NM_000277.2(PAH):c.793T>G (p.Cys265Tyr)

**Comment by cgpreston** [comment]
@bryanwulf, Diane says they have >260 variants they'd like transferred. Is there a preferred dataset/format to make this easiest for the developers? 

Useful information: 
1. Format.
    1. Is google sheets or excel best?
1. Needed data:
    1. Interpretation identifications (what specifically?)
    1. Links in UI (useful?)
1. Would prioritization be useful? If so Diane can tier them (how many tiers should she make?)

**Comment by bryanwulf** [comment]
@cgpreston I think we would accept whatever data they can provide, but at a minimum, we probably need something that uniquely identifies the variant (title or ID, be it ClinVar or Allele Registry) and the interpretation (owner/creator or ID, for variants with multiple interpretations).

1) A Google Sheet or CSV (saved from Excel) should work.
2) URLs from UI would likely include useful IDs, but they're not necessary (read: don't spend additional time gathering them).
3) Prioritization (in any form) wouldn't hurt, but may not be necessary (it would depend on if we're able to make all the changes in one sitting or not).

**Comment by cgpreston** [comment]
@bryanwulf, thanks for this info!

**Comment by cgpreston** [comment]
@bryanwulf, from Diane: 

The variants that need to be transferred are listed on the second sheet in this google doc "Variants to transfer to PKU": https://docs.google.com/spreadsheets/d/1AQc9tnmTOxkzmirOe-FGKzjofo5jFy4njyuMd3tV9AM/edit#gid=964123244

This includes the following information: 
1. VCI user who "owns" the current curation
1. ClinVar variant title
1. ClinVar IDs and CAR IDs 

There are 3 variants highlighted in yellow that are the top priority. They would like all of them transferred and can provide more prioritization if needed. 

Is this sufficient for someone to start work on this ticket?

**Comment by bryanwulf** [comment]
@cgpreston I've moved the 3 highest priority variants:
https://curation.clinicalgenome.org/variant-central/?variant=59ef18d5-05af-4ff7-89b6-ec59575eb4c1
https://curation.clinicalgenome.org/variant-central/?variant=e013b9dc-b95a-4571-8fd9-5d95a054784e
https://curation.clinicalgenome.org/variant-central/?variant=a647a18d-a669-4c30-81c1-e183a60e97bf

I'm pondering alternatives to the current process because I'd like to avoid using it on the entire list provided by Diane. The 3 variants above required 45 unique updates, so we'd probably be looking at several thousand updates (for the full list).

In the meantime, if there are other high-priority variants to move, we can take care of them (in small batches) using the current process.

**Comment by cgpreston** [comment]
Thanks @bryanwulf! Maybe a good thing to discuss more at one of our meetings. I've asked Diane to prioritize a few more if possible.

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PAH interpretations move to affiliation](https://trello.com/c/mEepjUf7/16-pah-interpretations-move-to-affiliation)

**Comment by cgpreston** [comment]
Dependent upon completion of #2005

**Comment by cgpreston** [comment]
Update: 2/27: Most of the requested curations have been transferred. Diane will assess the remaining ones where there is a PAH entry and a personal entry and let us know what to do with those on a case-by-case basis. Closing this!
