### ISSUE TITLE
Remove variant curation from production

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#1904]
@bryanwulf, I accidentally initiate a variant curation in the production VCI, could you remove it from the database? Sorry, won't happen again!! 

The variant: 
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=1d4a2efd-e40d-456d-9048-e027e93683b2&interpretation=30dcaa5b-ae5d-4751-acae-ab1d1ece3b87

**Comment by bryanwulf** [comment]
As an immediate, but partial, fix, I've changed the status of the interpretation to "deleted".

**Comment by cgpreston** [comment]
Thanks @bryanwulf!

**Comment by larrybabb** [comment]
I did the same thing. so sorry. I didn't realize that it persisted indefinitely once you started a new variant curation.  I presumed there was a means to save, cancel or ultimately delete it if it hadn't been interpreted or published.

Can you mark this one as deleted too?
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=8862fefb-acd7-4945-bad2-89afaa4f0646&interpretation=34024948-6016-4414-892a-31758294ebb4

I will make sure to only view stuff in production and not open any curations of my own. I'll use test for that going forward.

**Comment by larrybabb** [comment]
Is there a feature request in the queue to be able to abort or delete a provisional interp? Seems like it would be a reasonable expectation of the app from a user's perspective.

**Comment by cgpreston** [comment]
@larrybabb, I think there's a historical reason for this behavior... @wrightmw is that right?

**Comment by larrybabb** [comment]
Does that historical reason prevent the ability to add this capability going forward?

**Comment by wrightmw** [comment]
@larrybabb Users can delete evidence they've added but more complex deletions, that potentially require edits behind the scenes in multiple locations, are currently only available via one of our devs doing them by hand.  We have thought about creating tools within the interfaces, that would allow users to do many of the edits that currently take time for our devs to complete.  For instance, Jimmy developed a tool that allows the ownership of GDMs to be switched from an individual to an affiliation. Christine and I (with our admin privileges) use this tool routinely to rapidly support user requests to change the ownership of GDMs. Tools such as this could be extended for use by coordinators so that they could make these edits themselves. Additionally, further admin tools could be created to allow Coordinators to resolve errors or issues... such as changing the MONDO ID, and deleting interpretations.

I've created a ticket for deleting interpretations so that we can capture the discussion and scope out the requirements for this: https://github.com/ClinGen/clincoded/issues/1981

**Comment by wrightmw** [comment]
@bryanwulf Can someone please mark Larry's entry as deleted?:
https://curation.clinicalgenome.org/variant-central/?edit=true&variant=8862fefb-acd7-4945-bad2-89afaa4f0646&interpretation=34024948-6016-4414-892a-31758294ebb4

**Comment by bryanwulf** [comment]
@wrightmw The status of Larry's interpretation has been set to "deleted".

**Comment by cgpreston** [comment]
Closing this as the immediate curations were set to deleted and the longer-term solution will be developed as part of #1908
