### ISSUE TITLE
Change segregation to be a sub-object in family.

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#192]
Segregation is specific for each family. It's not necessary to be separated as an independent object. Merge it into family will make data transferring easier for both back end and front end. In addition, variants should be a property in segregation.

**Comment by forresttanaka** [comment]
@kgliu0101 and I discussed this, and making some of these objects (like segregation and method) as separately-writable objects has really complicated things, and made writing them more prone to failure. Embedding them will make things a lot easier.

As a bit of trivia, Laurence once saw how some of our objects are set up, and asked, “Why are these separate objects instead of embedding them?” I had no coherent answer.

**Comment by forresttanaka** [comment]
I’ll need to hold https://github.com/ClinGen/clincoded/issues/7 until these is done, but I still have a fair amount to do on it — many visual, but also reorganizing things for the new schema changes.

**Comment by kgliu0101** [comment]
Since variant is no longer associated to family, it is necessary to save proband info in individual which is included in the family. A new property will be added in individual object for it.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
