### ISSUE TITLE
Implement Group Submit Results page

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#200]
From the PPT, the page to go to when clicking Submit on the Group Curation page.

**Comment by selinad** [comment]
![image](https://cloud.githubusercontent.com/assets/11320314/9143928/3651237e-3cfe-11e5-93c2-2d8e086d6b80.png)

**Comment by selinad** [comment]
Yes selection:
![image](https://cloud.githubusercontent.com/assets/11320314/9143985/9a466754-3cfe-11e5-9d3a-d9288fff2c22.png)

**Comment by selinad** [comment]
Hi @forresttanaka - looking great.

A few items:
* can you please change text in parentheses and after to say : "(e.g. presence of phenotypes, average age of onset, race, family ethnicity)" and/or any information about the segregation of phenotypes and/or variants)."
*  re our discussion - I think better to have yes/no drop down - make them really think about their answer to the question rather than apply options that may or may not make sense if they have failed to read the question.
* Looking at this, I think note that is at top should go just under the question.
* For NO: change instruction text to: "Any variant associated with an individual that is a member of a Group but not part of a Family is captured at the Individual level.  To associate a variant and/or information such as age, race, etc. with an individual in the Group, click "Add New Individuals for this Group." If you have previously created an entry for this Individual, return to the Gene-Disease record page to add this Individual to the newly created Group."
* For YES, add instruction text: "Any variant associated with a proband in a Family is captured at the Family level.  To associate segregation, variant or any other information for a family, click "Add New Family for this Group. If you have previously created an entry for this Family, return to the Gene-Disease record page to add this Family to the newly created Group."

**Comment by selinad** [comment]
One more thing - could View be a little more obvious?  Maybe a color?

Also, what do you think of it saying "View Submission" ?

**Comment by selinad** [comment]
@forresttanaka - for this page (after Submit Group info), how difficult would it be to have a box come up that holds the question "Do any of the probands or other individuals...."  It looks like text I might avoid reading - something to make it clearer it's a necessary part of continuing...

**Comment by selinad** [comment]
after talking to @forresttanaka - he will make a box for the "Do any of the probands...." question and then a second box (the gray one that already exists) will come up in answer to that

Also, he will add an Edit button after the View button to discourage people from going back (it looks like they have lost data when they do that).

**Comment by selinad** [comment]
@forresttanaka: when a user says Yes to Family info and goes to create a new one, could the resulting page show the same Group info that was on the Submit Group page, just about "Curate Family Information?"  I think we may have gittered about this

**Comment by forresttanaka** [comment]
![group-submit](https://cloud.githubusercontent.com/assets/1181324/9347021/fcfeb17a-45d8-11e5-85f7-3fcfdb9e41da.png)

**Comment by selinad** [comment]
This looks fantastic, @forresttanaka!
I can't see the "No" option, but my guess is it's all good - thanks for doing this - I think it makes it clearer.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
