### ISSUE TITLE
Tool to transfer Interpretations to an Affiliation

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2005]
We previously developed a tool that allowed Admin users to move Classifications across from individuals to affiliations in the GCI ( #1823 ). We require a similar tool to move Interpretations from individuals to affiliations in the VCI.

**Comment by wrightmw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PAH interpretations move to affiliation](https://trello.com/c/mEepjUf7/16-pah-interpretations-move-to-affiliation)

**Comment by cgpreston** [comment]
Could be just like the GCI tool, and input the following:
1. Individual user/owner ID 
1. Curation ID 
1. Affiliation ID

**Comment by gcheung-SF** [comment]
@wrightmw , @cgpreston , @bryanwulf ,
After transferring an interpretation that's saved as provisional , Christine pointed out that in the "Evaluation Summary" page, under "Saved Provisional and Approved Interpretation(s)" section, the "ClinGen Affiliation" for the provisional has the previous/old affiliation.  This data is from a snapshot that's stored when the evidence was saved as provisional.  The current gdm transfer has the same issue, the "ClinGen Affiliation" in the "Classification Matrix" has the previous affiliation name when the provisional or other action was done.  Not sure if the snapshots should also be updated to new affiliation.  And will updating causes problem when start sending action tracking to UNC streaming service since the affiliation will be different.

**Comment by wrightmw** [comment]
Looks good. A couple of improvements should be added in future prior to any plans to expand the use of this tool beyond the Stanford biocurators:
1) It would be good to store a timestamp and a record of what the ownership of the record changed from and to
2) It is possible to create multiple interpretations from the same affiliation for a single variant with this tool. For instance, if a single variant already has interpretations made by multiple affiliations (e.g. A and B affiliations)... then changing any of the interpretations to an existing affiliation with an interpretation will results in more than one interpretation for that affiliation ( e.g. if either A or B is changed to the other then you end up with two A or two B affiliations).

**Comment by wrightmw** [comment]
R31 release
