### ISSUE TITLE
Duplicated GDM issue

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2058]
As reported in #2056, a GDM in the GCI was duplicated. This issue needs to be investigated and fixed.

**Comment by gcheung-SF** [comment]
From my investigation, the problem mostly was not created because of bug(s) in our codes.  I could not reproduce the problem on live site.  But will look into codes.

Here are the cases on live site and my findings:

1. Reported in issue #2056, 2 copies of gdm
PHEX – X-linked hypophosphatemic rickets
 https://curation.clinicalgenome.org/curation-central/?gdm=f47f7517-0df7-48cc-8f39-7f3a5469d5fc&pmid=29505567
   "date_created": "2019-05-16T14:57:04.399547+00:00",
 https://curation.clinicalgenome.org/curation-central/?gdm=ffa2c008-601a-4f19-a65d-bfb3794ac756
   "date_created": "2019-05-16T14:57:09.435004+00:00",
Both gdms were created by same user in just seconds apart.  So may be user clicked the button once but no response so clicked again.  The second click created another copy of the gdm because the first one was still being created and was not found.  AWS warning was sent at 5-16-19 14:21:26 which might be related to the delay.

2. 4 copies of same gdm were created within 15 seconds
MED12 – MED12-related intellectual disability syndrome
X-linked inheritance
  https://curation.clinicalgenome.org/curation-central/?gdm=92c2ce8c-377c-487f-8442-bf07ee5c947c&pmid=26273451
    "date_created": "2018-03-23T17:07:08.736607+00:00",
  https://curation.clinicalgenome.org/curation-central/?gdm=736842a2-c87e-4518-a698-84f0b32945f9
    "date_created": "2018-03-23T17:07:12.439238+00:00",
  https://curation.clinicalgenome.org/curation-central/?gdm=5928eb0c-afe7-4693-8c14-fb3cc625281b
    "date_created": "2018-03-23T17:07:15.472253+00:00",
  https://curation.clinicalgenome.org/curation-central/?gdm=6a0bfef8-cc16-46b8-a8d9-e092bea20301
    "date_created": "2018-03-23T17:07:21.968372+00:00",
All 4 gdms were created by same user, 3 of them were not used.  Mostly the last 3 entries were added due to initial gdm was being created and not found.  R17 was released on that day, 3-23-2018, so may be related.

3. 3 copies of gdm; 2 were created within 2 minutes
RUNX1 – hereditary thrombocytopenia with normal platelets-hematological cancer predisposition syndrome
Autosomal dominant inheritance
  https://curation.clinicalgenome.org/curation-central/?gdm=0670215d-0d3f-4a88-bbf6-18cc1a6d9c06&pmid=11830488
    Creator:Xi Luo — 2018 Mar 16, 1:26 pm
  https://curation.clinicalgenome.org/curation-central/?gdm=139d2588-9fd8-4785-84ca-b3963f98ea0a
    Creator:Xi Luo (Hereditary Cancer) — 2018 Apr 19, 12:16 pm
    "date_created": 2018-04-19T19:16:39.163719+00:00
  https://curation.clinicalgenome.org/curation-central/?gdm=1b276bd7-5045-4df1-9c31-4d4c8dcdcd4a&pmid=25114263
    Creator:Xi Luo (Hereditary Cancer) — 2018 Apr 19, 12:18 pm
    "date_created": "2018-04-19T19:18:25.268357+00:00"
The older copy was created by same user back on 3-16-2018.  The two new ones were created on 4-19-18 mostly due to delay that the existing gdm was not found.  R18 was released on that day.

4. 2 copies of gdm, created by different user on different date
ACTG1 – Baraitser-winter syndrome 2
Autosomal dominant inheritance
MONDO:0013812
  https://curation.clinicalgenome.org/curation-central/?gdm=327a5efc-8fbb-4dd1-ad09-6914abba0e7f&pmid=27240540
    Creator:Rebecca Siegert (Hearing Loss) — 2019 Jan 07, 8:03 am
    "date_created": "2019-01-07T16:03:40.810337+00:00",
  https://curation.clinicalgenome.org/curation-central/?gdm=2235d4e4-5000-4b31-a560-87f5a42beda0
    Creator:Madeline Hughes (Hearing Loss) — 2018 Nov 15, 9:12 am
The older copy was created back in 2018.  The new one was created on 1-7-2019 when no special event was found.  Only AWS warnings were sent out at 1-8-2019 16:38:00.

5. 2 copies of gdm, created by different user on different date
TNNC1 – hypertrophic cardiomyopathy
Autosomal dominant inheritance
MONDO:0005045
  https://curation.clinicalgenome.org/curation-central/?gdm=87c15ba4-1efe-4970-8cad-edca6d57d3b2
    Creator:Bryce Seifert — 2016 Jan 29, 8:47 am
  https://curation.clinicalgenome.org/curation-central/?gdm=4b8d340f-2003-43ba-b08c-dc7e05907428
    Creator:Jen McGlaughon — 2017 Jan 10, 9:42 am
Not sure about this case since no related event was found.
