### ISSUE TITLE
Change of MonDO for gene HCN1

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2103]
The Epilepsy GCEP requests a change to the disease entity for the HCN1 gene curation: https://curation.clinicalgenome.org/curation-central/?gdm=8ad2a522-5c68-480b-b37e-7d3d228671ba&pmid=12890777

The current disease entity is undetermined early onset epileptic encephalopathy (MONDO:0018614).

**We would like it changed to Complex Neurodevelopmental Disorder (MONDO:0100038)** 

this change is required for publication of this gene-disease curation on the ClinGen website

**Comment by h-tong** [comment]
Hi, @courtneythaxton, I've changed the disease for the HCN1 curation. This typically involves changing the disease associated with each case-level piece of evidence as well (given that the disease in the evidence matches the disease for the gene). As I went through the evidence, I found in the 4th article down (PMID: 19344873), 3 individuals have the "intellectual disability" disease, so I was hesitant to change it. I just wanted to make you aware, so that you can change it in the UI if you wanted to.

Please let me know if there are any issues!

**Comment by courtneythaxton** [comment]
Thank you @h-tong for this information and correcting the record. I do sometime use a different MonDO ID then the one for the whole record. Especially in the cases of syndromes in which individuals could be diagnosed based on one phenotype that is part of the spectrum. I really appreciate you pointing out the cases and given me the opportunity to check them over. 

Take care,
@courtneythaxton

**Comment by cgpreston** [comment]
@courtneythaxton, @h-tong made the requested changes in the production GCI, can you check and confirm it meets your expectations?

**Comment by courtneythaxton** [comment]
@cgpreston @h-tong, I looked over this curation and it meets expectations. Thank you very much for making this adjustment!

**Comment by cgpreston** [comment]
Thanks @h-tong and @courtneythaxton!
