### ISSUE TITLE
Changes to landing page for user registration

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2109]
Requirements: 

1. Change the language of the "login" button in the top right of the VCI/GCI to say "Login/Sign Up"

2. Change the language of the grey bar to match the mockup in slide 3. https://docs.google.com/presentation/d/1JJV48K0lH7gAOi1YFZLM51wwzUQL-C7Z_XdMfc-Swvs/edit#slide=id.g7ab49814cb_0_5

3. Note that the demo and prd site have slight differences in the landing page (see @wrightmw's comment)

**Comment by wrightmw** [comment]
@cgpreston FYI.. the landing page you have on mockup slide 3 is from the test interface but the prod site will differ slightly because it needs to keep the link to the dev site:

![Screen Shot 2020-01-16 at 10 47 29 PM](https://user-images.githubusercontent.com/15131169/72590247-27b92280-38b2-11ea-8266-fcefd7a2f461.png)

**Comment by cgpreston** [comment]
Released in R33 5/7/2020
