### ISSUE TITLE
Backend time stamp and user id

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#214]
Encoded has a method in schema mixins.json that automatically save time stamp and creator's uuid when creating a new record. The mixins method will be adopted in Clincoded. Once done, existing properties "owner" and "dateTime" are not necessary in relevant schemas.

**Comment by forresttanaka** [comment]
I pushed changes for the Group Curation, Family Curation, Create Gene Disease, and Curation Central pages to use the submitted_by and date_created properties.

**Comment by forresttanaka** [comment]
New push, just to sort the Participants list by last name. It used to sort by email address, and then temporarily by nothing at all.

**Comment by mrmin123** [comment]
Pushed changes with updates to the Dashboard page to use the new submitted_by and date_created properties. I had to update some of the schemas to return the submitted_by.uuid to get this to work. Updated the db dumps to reflect this.

**Comment by forresttanaka** [comment]
* Group and Family creation and editing no longer set the owner and dateTime properties, instead letting the server set it on POST. No visible changes on these pages. Updates to these objects delete the submitted_by and date_created properties so that the objects write successfully.
* Curation Central now uses the object and session user property UUIDs to see if the currently selected annotation comes from the currently logged in user or not. That determines whether you can edit a group or family, or just view them.
* The status area on Curation Central now shows user names linked to their email addresses, rather than displaying their email addresses.

![screen shot 2015-08-14 at 13 49 51](https://cloud.githubusercontent.com/assets/1181324/9283803/5e3b7f28-428b-11e5-8bd1-e0a5cdc4b482.png)

**Comment by mrmin123** [comment]
* The /gdm/ page's data is used to generate the Article-GDM relations and find the user's created GDMs on the Dashboard
* Dashboard now uses the users' uuid, instead of email, to match ownership of objects
* Dashboard now uses `submitted_by.uuid` of objects for ownership matching and `date_created` for sorting
* Dashboard page now uses dot notation to access object properties whenever possible
* No visible change on Dashboard

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
