### ISSUE TITLE
Updating GDMs and data exchange snapshot issue

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/clincoded#2158]
Discovered with regards to the GRIA3 update #2070. 

Issue 1: (per @gcheung-SF) when we modify a record there is no updating of the snapshot/data exchange. 

Issue 2: There is a discrepancy between the evidence summary and the rest of the curation. 

![image002](https://user-images.githubusercontent.com/46766411/76537501-18320200-643b-11ea-8ee6-77631721cf4e.png)
![image004](https://user-images.githubusercontent.com/46766411/76537531-22ec9700-643b-11ea-92d3-bec061a8d11d.png)

Comments from curators: 
Stanford team/website team: I believe this a record for which we asked Stanford to change the disease entity at one point in time.  It looks like that disease entity was correctly changed in most places in the GCI EXCEPT for the evidence summary.  It also looks like the website is pulling the disease information from the evidence summary, so this may be why the website is showing the incorrect disease entity (should be "Complex Neurodevelopmental Disorder").  That is one issue that we need to address.

The other issue, and what we can't figure out, however, is where the website is pulling its date.  The correct date that we want displayed is November 6, 2019.  The GCI is showing a publish date of 9/12/19, and the website is showing a different date altogether (9/9/19).  Even if something happened on the data entry end, and the person accidentally put 9/12/19 instead of 11/6/19, the GCI and the website should still show the same date, correct (9/12/19)?

Also, on the evidence summary page, it says it is in progress.  The website says it was curated for X-Linked Syndromic ID in September 2019. GRIA3 was recurated for Complex Neurodevelopmental Disorder MONDO:0100038 and was approved on November 6, 2019. It should be pulling in that information instead of X-linked Syndromic ID and no evidence.

**Comment by cgpreston** [comment]
@wrightmw @gcheung-SF , this is the status of the GRIA3 issue, I think we need to have a bit more discussion and also see if these issues are widespread.

**Comment by gcheung-SF** [comment]
https://asjira.stanford.edu/jira/browse/CLINGEN-73

**Comment by gcheung-SF** [comment]
1. The disease was changed in https://github.com/ClinGen/clincoded/issues/2070, the snapshots were not updated. I think that's by design that we don't update/change what has been done/recorded. Because this's the data that got sent to Data Exchange already. The change was made around Nov 20, 2019.

2. The data gets displayed in the evidence summary is from a snapshot.
For example, the latest snapshot - https://curation.clinicalgenome.org/snapshots/c2cc6bb0-c12a-4b8b-8d3c-cc5601108df1/
The data in resourceParent - gdm - disease still has: "diseaseId": "MONDO_0020119" and "term": "X-linked syndromic intellectual disability"
               "last_modified": "2017-11-13T17:41:12.912021+00:00",
                "@id": "/diseases/0cb732e1-c142-466e-9089-35e43b28f110/",
                "diseaseId": "MONDO_0020119",
So the disease gets displayed on evidence summaries is still the old disease.

Then evidence summaries have "In progress" status when it should be "Approved"/"Provisional" is also because data in the snapshots.
In the snapshots, there are two provisionalClassifications associated with affiliation 10006 (Intellectual Disability and Autism).
    https://curation.clinicalgenome.org/provisional/95335f63-1d23-4d2c-9fbb-2af31f8816c1/ <- has different data
    https://curation.clinicalgenome.org/provisional/25f94660-0a8d-4f3a-8f6c-dde1b38a8ab/ <- has correct data
And the first classification is used to display status in the evidence summaries.

Looking into https://curation.clinicalgenome.org/provisional/95335f63-1d23-4d2c-9fbb-2af31f8816c1, it was last modified by Christine.
"classificationStatus": "In progress",
"affiliation": "10006",
"last_modified": "2019-05-02T17:47:40.386834+00:00",
modified_by Christine Preston
"publishClassification": false,

But when looking into the gdm, https://curation.clinicalgenome.org/gdm/3dc1c298-c98b-442d-8488-47fa8eebf689/
only the correct classification is included.

Tried on test site, but cannot find a way to remove that extra classification.

3. From the last snapshot, the publish date is 9-12-2019 since that's the publish snapshot was created. And this timestamp was set when the classification was published. But the previous approved/published version was published on 9-9-2019. So may be the last publish data was not sent successfully to Data Exchange or somehow not received by Data Exchange.

**Comment by cgpreston** [comment]
GDM has been updated by curators and the MONDO is now correct. Communicate with users about the need to go through this process when updating MONDO IDs.
