### ISSUE TITLE
Change source of MANE data to Ensembl API

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#2176]
In order current MANE data, we will switch to obtaining this directly from the originating source via the Ensembl API.

**Comment by cgpreston** [comment]
Relates to #1868  and #2126

**Comment by cgpreston** [comment]
@shaungc-su : we have a new issue identified with the MAP2K2 gene, ensembl is indicating 2 canonical transcripts for the gene: https://rest.ensembl.org/vep/human/hgvs/19:g.4099279G%3EA?content-type=application/json&hgvs=1&protein=1&xref_refseq=1&ExAC=1&MaxEntScan=1&GeneSplicer=1&Conservation=1&numbers=1&domains=1&canonical=1&merged=1

Ideally we would do the following: 
1. Check for multiple canonical transcripts 
2. Indicate ALL transcripts as canonical on the Basic Information RefSeq Transcript chart 
3. IF: only one of the canonical transcripts is a "NM" then use that as the canonical transcript for the variant title logic
4. IF: multiple of the canonical transcripts are a "NM", then move to the variant title logic that uses the genomic coordinates. 

@wrightmw

**Comment by shaungc-su** [comment]
Hi @cgpreston , thanks for the detail explanation! I'll include this multi-canonical transcripts case into the implementation. One follow up question:
- In your point 4, if there're multiple different canonical transcripts start with `NM`, which one should we use for variant title selection logic?

Also recently when looking at Ensembl's data, I have a few questions as below:


1. I'm currently using `hgvs=1&protein=1&xref_refseq=1&ExAC=1&MaxEntScan=1&GeneSplicer=1&Conservation=1&numbers=1&domains=1&mane=1&canonical=1&merged=1`, which adds `mane=1` to the existing parameters for canonical, so that the result includes both MANE and canonical and we only need to make one request on Ensembl API (since wait time is 2~4 seconds per request for Ensembl API). Does the additional `mane` parameter make sense (any concerns like including it may interfere with other parameters)?
1. Variant ClinvarId `550731` has only one gene associated, but I found two ensembl transcripts marked as MANE. How do we decide which one to pick as MANE for our system?


```
{
          "consequence_terms": [
            "downstream_gene_variant"
          ],
          "gene_id": "ENSG00000117450",
          "distance": 2235,
          "protein_id": "ENSP00000361152",
          "used_ref": "TCAGGTGTGTGCATA",
          "gene_symbol": "PRDX1",
          "refseq_transcript_ids": [
            "NM_181697.3"
          ],
          "transcript_id": "ENST00000319248",
          "mane": "NM_181697.3",
          "genesplicer": "loss/donor/45508812-45508811/Medium/5.084220,gain/acceptor/45508809-45508808/Medium/11.111633",
          "variant_allele": "-",
          "source": "Ensembl",
          "impact": "MODIFIER",
          "gene_symbol_source": "HGNC",
          "strand": -1,
          "biotype": "protein_coding",
          "given_ref": "TCAGGTGTGTGCATA",
          "hgnc_id": "HGNC:9352"
}
```

```
{
          "transcript_id": "ENST00000401061",
          "hgvsp": "ENSP00000383840.4:p.Ser146_Ile150del",
          "mane": "NM_015506.3",
          "refseq_transcript_ids": [
            "NM_015506.3"
          ],
          "protein_id": "ENSP00000383840",
          "protein_end": 150,
          "hgvsc": "ENST00000401061.9:c.436_450del",
          "used_ref": "TCAGGTGTGTGCATA",
          "gene_symbol": "MMACHC",
          "consequence_terms": [
            "inframe_deletion"
          ],
          "exon": "4/4",
          "cdna_start": 469,
          "gene_id": "ENSG00000132763",
          "hgnc_id": "HGNC:24525",
          "cds_start": 436,
          "cds_end": 450,
          "strand": 1,
          "domains": [
            {
              "name": "3sby",
              "db": "ENSP_mappings"
            },
            {
              "name": "3sby",
              "db": "ENSP_mappings"
            },
            {
              "db": "ENSP_mappings",
              "name": "3sbz"
            },
            {
              "name": "3sc0",
              "db": "ENSP_mappings"
            },
            {
              "name": "3som",
              "db": "ENSP_mappings"
            },
            {
              "db": "ENSP_mappings",
              "name": "3som"
            },
            {
              "name": "3som",
              "db": "ENSP_mappings"
            },
            {
              "name": "3som",
              "db": "ENSP_mappings"
            },
            {
              "db": "ENSP_mappings",
              "name": "3som"
            },
            {
              "name": "3som",
              "db": "ENSP_mappings"
            },
            {
              "name": "3som",
              "db": "ENSP_mappings"
            },
            {
              "db": "ENSP_mappings",
              "name": "3som"
            },
            {
              "db": "ENSP_mappings",
              "name": "3som"
            },
            {
              "name": "3som",
              "db": "ENSP_mappings"
            },
            {
              "db": "ENSP_mappings",
              "name": "3som"
            },
            {
              "db": "ENSP_mappings",
              "name": "3som"
            },
            {
              "db": "ENSP_mappings",
              "name": "3som"
            },
            {
              "db": "ENSP_mappings",
              "name": "3som"
            },
            {
              "name": "3som",
              "db": "ENSP_mappings"
            },
            {
              "name": "3som",
              "db": "ENSP_mappings"
            },
            {
              "name": "5uos",
              "db": "ENSP_mappings"
            },
            {
              "db": "Pfam",
              "name": "PF16690"
            },
            {
              "name": "PTHR31457",
              "db": "PANTHER"
            },
            {
              "name": "cd12959",
              "db": "CDD"
            }
          ],
          "biotype": "protein_coding",
          "canonical": 1,
          "given_ref": "TCAGGTGTGTGCATA",
          "codons": "TCAGGTGTGTGCATA/-",
          "impact": "MODERATE",
          "gene_symbol_source": "HGNC",
          "amino_acids": "SGVCI/-",
          "variant_allele": "-",
          "genesplicer": "loss/donor/45508806-45508807/Medium/5.084220",
          "protein_start": 146,
          "source": "Ensembl",
          "cdna_end": 483
}
```

3. If multiple genes associated with a variant, we don't try to get canonical nor MANE transcript, is that correct?
4. The existing get-canonical implementation filters ensemble transcripts by requiring 
`hgvsc` exists (because it's used for the transcript id and nucleotide change) and `source=RefSeq`. Is the `source=RefSeq` filter correct to apply for canonical transcript?
5. For canonical transcripts, is it generally ok to use `hgvsc` for transcript id and nucleotide change? 
6. For MANE transcript, is it generally ok to use second half of `hgvsc` for nucleotide change, and second half of `hgvsp` for amino acid change name?

Apologies for many questions in once! But they'll be really helpful for ensuring that the canonical and MANE transcripts we select from Ensembl are the desired one(s). Thanks a lot!

**Comment by cgpreston** [comment]
@shaungc-su: 

if there are 2 canonical transcripts with "NM" and there is no ClinVar title or MANE transcript then please use the genomic coordinates to name the variant title. 

For the multiple genes.... @wrightmw, do you have suggestions? For the title I would suggest we use the genomic coordinates to name the variant, but add a warning icon with a hoverover that indicates that the variant maps to multiple protein coding genes? 

I'm not sure about the rest of your questions, we may need to schedule a quick meeting to discuss further.

**Comment by wrightmw** [comment]
@cgpreston We already have the caveat that if multiple genes are returned then we skip to using genomic coordinates.

**Comment by wrightmw** [comment]
R33 release.
