### ISSUE TITLE
UI Postgres Search for real-time lookups (e.g. recently created/edited items)

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#224]
During times the UI relies on up-to-date object references, use Postgres instead of Elasticsearch searches to prevent the UI from missing new objects and connections between them.

**Comment by kilodalton** [comment]
Explanation: Since there is always a lag when an item is added or modified in Elasticsearch, Postgres will always be the "gold standard" as to the state of the database. For instance in encoded,  Elasticsearch indexing may be milliseconds or minutes behind Postgres depending on how may records need to be (re)indexed when something is changed. Since at times we need to check for "uniqueness" before creating a new record, we can't rely entirely on Elasticsearch for lookups.

**Comment by forresttanaka** [comment]
For now, I think https://github.com/ClinGen/clincoded/issues/280 takes care of this by having the Record Curation page always load from Postgres, and not use Elasticsearch. A more formal study of the most optimal way to handle this should be done, particularly on whether other parts of the interface need this treatment as well.
