### ISSUE TITLE
date_created field changes on edit

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#246]
Noticed this while updating the Dashboard to support Groups and Families. The date_created field of the annotation and group objects change when adding a new related Family/Group, and the date_created field of the family and group objects change when they are edited. The desired behavior is that the date_created field does not change after initialization of the object.

Before (family count: 1):
![image](https://cloud.githubusercontent.com/assets/4326866/9365270/7e145a12-4665-11e5-9e38-a37f252fda76.png)

After (family count: 2):
![image](https://cloud.githubusercontent.com/assets/4326866/9365280/8ea7d2aa-4665-11e5-9ed0-831ba1afb46c.png)

Note that the date_created of both the annotation object and group object changed when the family was added (count increased); from 17:33:52 to 17:38:26.

**Comment by selinad** [comment]
Thanks, @mrmin123 - this was on my list of things to ask as the behavior seemed different from what I expected, so I am glad you brought it up.  You are saying that the date associated with a group or family, etc. should always be its creation date, correct?

**Comment by mrmin123** [comment]
@selinad Yes, that should be the case. If we track modification dates/change history that would be done in a different field.

**Comment by forresttanaka** [comment]
Discussed with @mrmin123 and @kgliu0101. The front-end needs to maintain date_created across updates, so I’ll make a new branch to do that. The @kgliu0101 will also add a last_modified property to various objects.

**Comment by forresttanaka** [comment]
* In addition to the object flattening routines for annotations, groups, and families, this adds a routine for flattening GDMs.
* Curation central loads fleshed-out GDM objects, and uses the new object-flattening routines to make them suitable for writing.
* Object flattening is now done in a way that the front-end code no longer needs to change if the back-end adds calculated properties. Changes to the schema might still require front-end changes, as is natural.
* Object flattening now makes sure date_created is copied over so that it gets maintained over the life of an object in the DB.
* Merged in @kgliu0101 changes to the back end to provide a ```last_modified``` property in several objects. This property tracks the time the object was last modified.

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
