### ISSUE TITLE
PMID scroll bar - see if it can adjust to window length

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#248]
It would be great if the PMID scroll bar could adjust to be the same size as the browser window. On a big enough monitor it is short and makes for more scrolling.

**Comment by kilodalton** [comment]
As an add-on to this: 
When a user adds a new PMID, if the newly added PMID would be scrolled off the scrolling window (e.g. PMID in scroll window appended to a long list of PMID and the first author's last name places the article below the viewable window), new PMID should be selected *and* scrollbar adjusted so that new PMID is  viewable (viewable+selected) in scroll window.

For instance on this GDM I added a bunch of articles then pmid 5000000.

Author name is Ota and is not visible as selected on the left:

![image](https://cloud.githubusercontent.com/assets/1878194/10741292/30830e10-7be4-11e5-8586-4901d9d47e47.png)

The result is that the "shortcut" back to the article is not visible in the navigation on the left which is not ideal.

Another PMID for testing 20929870 (first author last name = Zheng)
