### ISSUE TITLE
Associate Individuals, Families, and Groups

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#257]
Implement the capability to associate an existing family with an existing group, and an individual with a family and/or a group. At the moment, we may implement this as a modal with a scrolling list of groups to associate with the family.

When displaying families and individuals in the curation palette, digging through groups and families may show the same families and individuals more than once. This needs to be taken care of when displaying the curation palette.

**Comment by forresttanaka** [comment]
Likely not for 0.5, but will look into this.

**Comment by forresttanaka** [comment]
The technical part of this is straightforward, but the UI implementation will probably take some time. Moving to 1.0

**Comment by kilodalton** [comment]
This was a pain point for a curator so we need to address it.  (copying info from recent duplicated ticket here) 

--Group association: Amend UI or create admin interface to associate individual/family with a group after individual/family is created. 

--Family association:  Amend UI or create admin interface to associate individual with a family after individual is created. 

Methods for disassociation of individual/family from group and disassociation of individual from family should also be created.

**Comment by mrmin123** [comment]
I'm working on this right now and it's inherently similar to the Delete object functionality, but I'm aiming to offset most of the functionality to the backend. This was suggested in a previous Cherry Lab developers meeting, and the reasoning is that currently the delete functionality does all the work on the browser. This means that if the user quickly closes the tab/window (or is disconnected from the internet) shortly after initiating the delete action, because all the work is handled on the browser it's possible that not all objects might be properly tagged as deleted. Offloading this work to the backend would protect against this.

The concept is similar to reassociating objects, and there would be some code overlap with the delete functionality, and setting this up would make adding future backend processes easier, so I'm investing the time to do it this way now.

**Comment by mrmin123** [comment]
Since we're shifting gears I'm putting this on hold and leaving this note:

The work of shifting some of the larger processes to the backend has been done in `src/clincoded/backend_processes.py`. `traverse()`, `traverse_action()`, `reassociate()`, and `reassociate_action()` are for the most part implemented. `put_object()` still needs work.

* Accessing the URI for `traverse()` will call `traverse_action()` and return a valid tree of the target object and its children.
* Accessing the (convoluted) URI for `reassociate()` will call `reassociate_action()`, which will modify the target object's old parent and new parent, and then call `put_object()`. At the moment, the first `put_object()` call fails, incurring a Permission Denied, and the second `put_object()` call never happens. The first `put_object()` is successful if the function's request's `body` is not defined, but the second call still does not occur. The rendering of the subrequest might need to be disabled?

**Comment by wrightmw** [comment]
Resolved
