### ISSUE TITLE
Page Titles

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#287]
The title tag of every page is “ClinGen” and it should reflect what the title is in the curator_page.json data.

React officially doesn’t work outside the `<body>` tag, so we have to be a little bit out of bounds here, which ENCODE has done forever.

I think this should be done for 0.5, but I won’t argue if it gets kicked out.

**Comment by kilodalton** [comment]
@selinad Since we still open some windows in new tabs, this will actually be pretty helpful to users to keep track of various open windows.  Can you compile a list of "Page", "URL",  "Title"s for us? The title should still contain “ClinGen “ as in “ClinGen - Edit Group” or  “ClinGen - View Group”  or “ClinGen - View Group [name]” or “ClinGen - View Group [abbreviated name if it's a long group name]” so that ClinGen still always displays in tab/titles etc….similar to Google Calendar title/tabs retaining the Google prefix. 

I do not believe this can make it in for 0.5 but could be an early 0.5.1.

If we go with  "[abbreviated name if it's a long name]" options above, we should decide in advance how many characters to truncate_add ellipses  "ClinGen - View Group Whatever-1990-my..." . Simpler to go with "ClinGen - View Group" but less meaningful.

**Comment by forresttanaka** [comment]
When we forked from encoded, we pulled in a simple utility to truncate strings to the last space before a parameterized character limit, and adds an ellipsis. This avoids the “Dolly Parton - Life is Like a Butt” situation (a photo went viral a few months ago that showed a car stereo that didn’t care about word breaks when truncating, and was trying to display “Dolly Parton - Life is Like a Butterfly”).
