### ISSUE TITLE
Re-enable Persona login system in UI

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#30]
Enable the same Persona login system as ENCODED.

**Comment by kilodalton** [comment]
@forresttanaka We already have an open ticket for login... #2 . Persona login was working  (after #22 got merged in) before the recent UI changes got merged it that removed it, Changing the title of this ticket to reflect the is more about adding the login/out links just for UI since I know login was working. I left #2 open because roles is still in progress. Possibly one of the tickets should be closed?

**Comment by forresttanaka** [comment]
Ah, wasn’t aware of that. My feeling now is to leave this as a UI ticket for login, though it seems kind of funny because I’m just hacking it in there so you have it, and was planning on making a more finished version for #29 which has a lot of UI updates but won’t be done until probably Monday. What do you think @kilodalton?

**Comment by kilodalton** [comment]
Before login: 

![image](https://cloud.githubusercontent.com/assets/1878194/8258825/fed72eb4-166c-11e5-84cd-9a8d65520c17.png)


After login:

![image](https://cloud.githubusercontent.com/assets/1878194/8258840/1ddb937c-166d-11e5-8554-3223fd8b35ce.png)

After logout:

![image](https://cloud.githubusercontent.com/assets/1878194/8258849/2f931414-166d-11e5-9f6b-3b5a2bf5f0c0.png)


@forresttanaka Perfect!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
