### ISSUE TITLE
Blank middle section in GDM with PMID(s) added - default to first paper in record

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#316]
When there are PMIDs that have been curated, and a curator comes into record and there is a blank middle (for instance, when a GDM combo is entered and it exists and the curator selects "Curate") - have it display by default the abstract for the first paper in the record (i.e. one on the top of the left hand scroll bar).

**Comment by mrmin123** [comment]
Progress is on the [316_gdm_default_pmid](https://github.com/ClinGen/clincoded/tree/316_gdm_default_pmid) branch. Issue should be addressed, but needs testing.

**Comment by mrmin123** [comment]
@selinad @wrightmw test instance here: http://316-gdm-default-pmid-68289d6-minchoi.instance.clinicalgenome.org/

I've made an example GDM with a number of PMIDs here: http://316-gdm-default-pmid-68289d6-minchoi.instance.clinicalgenome.org/curation-central/?gdm=b91ccef3-2062-4db5-a49c-82dbe637ef9c

Loading that GDM with that URL (no PMID selected) should automatically forward you so that PMID 312313 is selected.

**Comment by selinad** [comment]
This looks great!  Tried from dashboard coming in and from another curator account coming in....thx!

**Comment by wrightmw** [comment]
I already responded on Slack, but thought I should add to the ticket. Looks great. Works well.

**Comment by selinad** [comment]
This looks good re my QA testing

**Comment by wrightmw** [comment]
QA testing: this works well.

**Comment by kilodalton** [comment]
Included in last release (R3). Nice job and thanks for your hard work.
