### ISSUE TITLE
Change View link for families for assessments

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#345]
Currently, families in the curation palette have a View link where the family can be viewed and assessed. Change this link to say “View/Assess.”

**Comment by mrmin123** [comment]
Family link changes to 'View/Assess' when it has segregation info (thus making it assessable):
![image](https://cloud.githubusercontent.com/assets/4326866/10593743/071736dc-767b-11e5-9921-f12180e5f8ff.png)

Also made Experimental Data item links to 'View/Assess', since they're all assessable by default:
![image](https://cloud.githubusercontent.com/assets/4326866/10593765/350c55fe-767b-11e5-9fbb-44cf23516f37.png)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production.
