### ISSUE TITLE
Change background/text color or add boxing to differentiate non-selected PMIDs

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#409]
In a record the selected PMID (in the left hand scroll bar) and its associated abstract (in the central panel) have a white background. The non-selected PMIDs (in the left hand scroll bar) have a light gray background and so it appears that these have been highlighted. 
It needs to be more obvious that the non-selected PMIDs have not been selected. Options discussed include:
- making the non-selected PMIDs a darker gray
- graying out the text
- boxing the selected PMID and associated abstract to more clearly differentiate it from the non-selected PMIDs

**Comment by selinad** [comment]
This would be high value for R3 if possible

**Comment by jimmyzhen** [comment]
@wrightmw I took a stab at styling the selected PMID panel as well as the non-selected ones. I did try to add a border around the associated abstract/citation, but I thought it was a bit too much and so I only applied couple of subtle styling to the "Abstract" header and horizontal rule above it. Let me know what you think. Thanks.

![image](https://cloud.githubusercontent.com/assets/6956310/12459936/1b47e9e2-bf66-11e5-814e-cf6cf3d74b8c.png)

**Comment by wrightmw** [comment]
@jimmyzhen I like the idea, the box does stand make the selected citation stand out ... however, I think it would stand out even more if additionally the other articles were greyed out slightly. @selinad  What do you think?

**Comment by selinad** [comment]
I like the new styling!

I think we need to make it visually clear that this citation box = this abstract.  Is there a way to visually connect the selected citation box with the cisplayed abstract?  e.g. background coloring, same colored box around abstract panel, etc.

**Comment by jimmyzhen** [comment]
@wrightmw @selinad I will try again.

**Comment by jimmyzhen** [comment]
@selinad @wrightmw Any thoughts on the version below?

![image](https://cloud.githubusercontent.com/assets/6956310/12468455/b8e9eda8-bf98-11e5-9b46-ba3361d1dd26.png)

**Comment by selinad** [comment]
Wow - I like the creative thinking on this!

However, I think there might be too many blue bars (variant, pubmed, abstract, Add PMIDs, highlighted PMID). Another thing is that the unselected PMID appears to be floating between entries at first glance

I'm not sure the selected PMID on the left needs to have a blue PMID bar....the box around it makes it obvious on its own.

Also - currently, the blue bars are all links, if I recall (Add PMID, PuMed link, variants) - are the new ones links? (Abstract, highlighted PMID) - if not, I think it may be confusing wrt expressing same functionality.

I just saw I never registered / answered @wrightmw's comment (sorry!) - I do think graying out non-selected a bit more might go a long ways...

**Comment by jimmyzhen** [comment]
@selinad I've gone back to the previous version and made some visual tweaks. Let me what you think.

![screen shot 2016-01-20 at 6 28 07 pm](https://cloud.githubusercontent.com/assets/6956310/12469794/b60bb07a-bfa3-11e5-89e9-eea365ed11de.png)

**Comment by wrightmw** [comment]
I like it!

**Comment by jimmyzhen** [comment]
@wrightmw @selinad I've spun up an EC2 instance for your review:
https://409-jz-highlight-selected-pmid-898e532-jzhen.demo.clinicalgenome.org/curation-central/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&pmid=8078586

Please let me know whether it's a go or no go. Thanks.

**Comment by wrightmw** [comment]
@jimmyzhen Great work on this! I was slightly confused with this instance that it went directly to the GDM but I was able to go back to the dashboard. 
The scroll bar for the citations limits how many citations you can view in the window. You can only see 3 or 4 citations and these are listed alphabetically by first author, so when I added "Zaima et al" (PMID: 19711971) to GDM that already had four citations then the new citation did not appear in the window. It would be better if when you add a new PMID then the scroll bar automatically hovers over the newly added citation.

**Comment by selinad** [comment]
@jimmyzhen you have done an amazing job of getting something up quickly and I like a lot of things about it!

The blue border on the PMID is great and I like the graying out of non-selected PMIDs.  Also love the styling of the PMID boxes in the left column.

A couple of quick thoughts - is the gray border around the PMIDs on the left column the same color as the gray border on the right (for Groups,etc.)?  It looks lighter, but it may be an optical illusion.  If not, I wouldn't mind seeing them the same gray, just to distinguish it from the white of the selected a bit more...

I prefer Black text for Abstract, although I can see you were trying to relate the abstract and selected PMID on left with the blue.

This may be too difficult, but could you put the blue border around the entirety of the middle section?   Not certain I like this, but here's a thought (excuse the blue not being exact).  Would be better if citation in middle section aligned with top of Add New PMID's...
![try1-pmidbox](https://cloud.githubusercontent.com/assets/11320314/12493882/364e801c-c03c-11e5-995c-6ace11f67b59.png)

@wrightmw - what do you think?  Too much?

**Comment by selinad** [comment]
Here it is with no right hand blue line on PMID box:

![try2-pmidboxes](https://cloud.githubusercontent.com/assets/11320314/12493933/7cd73c36-c03c-11e5-8b85-516d6b296bd2.png)

**Comment by wrightmw** [comment]
@selinad Funny you should say that, I suggested the blue box around the entire publication to Jimmy yesterday. We weren't sure whether it would be too much on the page, however I like it on your mock ups. I think it would be really nice to see how this would look... it certainly makes it very clear which citation you are looking at.

**Comment by selinad** [comment]
Great *ights think alike! (alight?)

**Comment by jimmyzhen** [comment]
@selinad @wrightmw 

1. The gray border around the non-selected PMIDs on the left column is the same color as the gray border on the far right column. It looks lighter because of its opacity (the graying out look). I have just made it slightly darker and hopefully it is now more distinguishable.
2. I have reverted the styling previously applied to the "Abstract" heading.
3. A blue border has also been applied to the center column, except that the citation is not exactly aligned with the top of the blue "Add New PMID(s)" button.

![image](https://cloud.githubusercontent.com/assets/6956310/12562672/4a24052c-c35b-11e5-8fce-2fd763150610.png)

**Comment by selinad** [comment]
Thanks for doing all of this so quickly, @jimmyzhen !

@wrightmw and I went over to @jimmyzhen 's desk to provide feedback.
Here were the 3 thoughts (for documentation)
* make the background behind the PMID boxes darker - same as background color behind boxes in evidence section
* have the blue border around abstract section be identical to blue around PMID wrt shadowing
* when moving a cursor over an unselected item - instead of having a blue border (making it possible that both selected and unselected have blue border), have the unselected PMID box with the cursor over it have a dark gray border.

Additionally, @jimmyzhen will look into anchoring left PMID scroll area to a PMID box that was just added  (since the abstract for that will be displayed upon addition) to see how much time it will take

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

Along with the approved thicker blue border on the selected PMID and its corresponding abstract, I have implemented the functionality to display the selected PMID in the far-left column when a new PMID is added.

Below are also the expected behavior in other use cases: 
1. Refreshing the page will show the selected PMID even when it was scrolled off the bounding viewable area.
2. From the Dashboard page, clicking on a given PMID from the "Your Recent History" list will show the selected PMID in the far-left column on the subsequent GDM page.

The implemented changes can be reviewed at:
https://409-jz-highlight-selected-pmid-363a23d-jzhen.demo.clinicalgenome.org

Let me know if you have any questions. Thanks.

**Comment by selinad** [comment]
This is fantastic!  I've tried getting back to the GDM from a few pages, and it looks like everything shows up in the correct spot.

One quick question - sometimes it seems like adding puts the new one on the "top" position in the left scroll bar (not on top, but positioned so it is at top of scroll), and sometimes middle or down - never off, which is great.  Was wondering what dictates this.

Thanks for the great work @jimmyzhen So much clearer as to which paper one is on.

**Comment by jimmyzhen** [comment]
@selinad When adding a new PMID, the selected PMID should be generally scrolled to the top of the scrollable area, except when the newly added PMID is at the bottom of the list (e.g. author name starting with "Z") and the scroll bar has reached the bottom of the scrollable area. And when a newly added PMID is second to the last, it will potentially appear at somewhere in the middle of the scrollable area.

**Comment by wrightmw** [comment]
@selinad If you need a paper with author starting with 'Z' for testing... there is PMID:19711971

**Comment by selinad** [comment]
Makes perfect sense - thanks, @jimmyzhen.  And thanks for the Z paper, @wrightmw - that worked perfectly as well.  

Super nice!

**Comment by wrightmw** [comment]
@jimmyzhen This looks great! I love the blue boxes around the abstract and article and the scroll bar now moves to the added publication, regardless if it is way down the alphabet.

**Comment by wrightmw** [comment]
This all looks good to me!

**Comment by selinad** [comment]
love this - all great!

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
