### ISSUE TITLE
Review drop downs for molecular interaction and make needed changes

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#419]
We need to add some more interaction Method choices (e.g. yeast 2-hybrid) for Experimental interactions. Also, choices for genetic interactions.  Review these drop-down selections AND decide whether Method and Type of Interactions are dependent on one another wrt to the dropdown.

**Comment by tsneddon** [comment]
Discussed and decided to add the following to the "Method by which interaction detected: *" dropdown:
* synthetic genetic analysis (MI:0441)
* two hybrid (MI:0018)

**Comment by kilodalton** [comment]
@selinad @wrightmw  Can you confirm whether or not there are additional items that need to be added here?

**Comment by wrightmw** [comment]
Please just add the two in the ticket for now.  We won’t be adding any more items until we’ve consulted further with the curators.

**Comment by kilodalton** [comment]
@selinad @wrightmw  

Is it Ok to just add those to the end of the list (i.e. does the the order need to change in any way)?

This is the existing list (for reference):
coimmunoprecipitation (M:0019)
pull down (M:0096)
affinity chromatography technology (M:0004)
protein cross-linking with a bifunctional reagent (M0031)
comigration in gel electrophoresis (M:0807)
x-ray crystallography (MI:0114)
electron microscopy (MI:0040)

**Comment by wrightmw** [comment]
@selinad Was there a request for this specific order based on likely frequency in papers? If not, then I would suggest sorting alphabetically or based on the MI number.

**Comment by wrightmw** [comment]
Oh dear, those have typos in. They should all begin with MI: not just M:

**Comment by wrightmw** [comment]
So, let's go with alphabetical then :-)

**Comment by wrightmw** [comment]
FYI: MIs are searchable on the EBI Ontology Lookup Server (e.g. http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=MI&termId=MI:0019 NB: this is very slow!).

**Comment by kilodalton** [comment]
@wrightmw Can you please check that the dropdowns in Experimental->Protein Interactions->Method by which interaction detected are correct now (and possibly add a few of the ones that were previously wrong and the new ones):

Note: Instance uses a copy of the production db and has limited curator access:
https://419-kd-addmolecularinteractions.demo.clinicalgenome.org



Previously incorrect:
pull down (M:0096)
affinity chromatography technology (M:0004)
protein cross-linking with a bifunctional reagent (M0031)
comigration in gel electrophoresis (M:0807)

New: 
synthetic genetic analysis (MI:0441)
two hybrid (MI:0018)


And display in the new order:

New order:
"affinity chromatography technology (MI:0004)",
"coimmunoprecipitation (MI:0019)",
"comigration in gel electrophoresis (MI:0807)",
"electron microscopy (MI:0040)",
"protein cross-linking with a bifunctional reagent (MI:0031)",
"pull down (MI:0096)",
"synthetic genetic analysis (MI:0441)",
"two hybrid (MI:0018)",
"x-ray crystallography (MI:0114)"


**NOTE** When this is in PRODUCTION, the production experimental/2dd87c34-3fbf-4795-8b49-a3f9fb100f63 needs to be updated (i.e. after R2 brought up) because it has the incorrect MI style associated with it:
`"experimentalInteractionDetection": "protein cross-linking with a bifunctional reagent (M0031)"`

**Comment by wrightmw** [comment]
Sure. Looking at it now :-)

**Comment by wrightmw** [comment]
@kilodalton I've checked all of the terms and MI numbers...all present and correct. Great! Thank you.

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
