### ISSUE TITLE
Cannot close modals on IE11

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#442]
Add New PMID(s) modal and Add/Change OMIM ID do not close when pressing 'Cancel' on Win7+IE11

**Comment by jimmyzhen** [comment]
According to Microsoft's documentation, there is no support for the "detail" property on the event object in IE11:
https://msdn.microsoft.com/en-us/library/ms535863(v=vs.85).aspx

Since Microsoft and other major browsers support the "type" property on the event object, is there a reason not to this property to detect the "click" event instead of counting the number of clicks (see below)?
```
if (e.detail >= 1){
            this.props.closeModal();
        }
```

**Comment by kilodalton** [comment]
There is some relevant (extensive) info regarding this modal functioning in tickets #144 (bug: Return closes PMID/OMIM modal) and PR #270 to resolve this.

One proposed solution was to use a screenX hack:
`if (e.detail >= 1 || e.screenX >= 0) {`

Other reasonable solutions that make the modal work correctly on Chrome+Firefox+Safari+IE are fine.

**Comment by kilodalton** [comment]
Tested on:
Win 7
--Chrome 
--IE

Win 10
--Chrome 
--IE

Works as expected.

**Comment by kilodalton** [comment]
Included in last release (R4). Nice job and thanks for your hard work.
