### ISSUE TITLE
Inactivate (a.k.a. "delete") record

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#453]
Establish system (front+backend) for suppresses display and inclusion of "inactive" records (i.e. do not delete...we must still *preserve the record* but do not display)

Useful information to retain when we change to inactive status:
status: active/inactive/"deleted" (or whatever we decide)
datetime_inactivated
user_that_inactivated_item

**Comment by mrmin123** [comment]
After updating the schemas and authorization rules, I've managed to get it so that a non-admin user is able to add and edit objects. Once an object they've added has a `status` of 'deleted', however, the non-admin user is not able to access the page (they get a 403, so this error page will have to change), while an admin user still can access it.

Things that still need to be done:
* Clean up user authorizations
* Find a way to convert all existing curators to a non-admin group
* Make it so that a non-admin user can set the `status`; you currently need to be an admin to do this
* Implement into UI (personal reminder: needs to update parent object to not include link to target object, on top of changing the `status` of target object)

Once all of this is complete it basically mimics an object 'deletion' to a non-admin user.

**Comment by mrmin123** [comment]
@selinad @wrightmw Please see instance http://453-delete-items-8517bd6-minchoi.instance.clinicalgenome.org/

When you Edit a Group/Family/Individual/ExperimentalData object you will see a new button in the lower-left of the form that says 'Delete'. Pressing this button will make a confirmation modal pop up, where if you press 'Confirm Delete' it should 'delete' the object and send you back to curation central.

I've done a rough test and I think it's working, but please let me know if you find anything buggy or of any other desired changes.

**Comment by selinad** [comment]
Hi @mrmin123 - looking great!  This will be a huge plus!

A few items:
* Please move Delete button over closer to Cancel and Save, but leave more space between Delete and Cancel:   D     C  S
* If you can easily go red with the Delete button, that is preferred
* On the pop up to confirm delete action, please switch the order of the buttons to "Cancel" on left, "Confirm" on right.  
* On pop-up, please make "Confirm Delete" be either the orange or red you use for Delete on the page...

So far, all delete actions are working...

**Comment by selinad** [comment]
Problem.  If I enter say experimental data and assess and then Matt assesses, I can delete that experimental data - I'm thinking we can't allow Delete of something someone else has assessed...?

**Comment by mrmin123** [comment]
I'll work on those cosmetic changes. Did the message in the modal look OK? It's very generic...

As for the deletion of assessed objects, I completely forgot about that detail. I'll work on a fix tomorrow.

**Comment by selinad** [comment]
Thanks, @mrmin123 - I'm wondering if we did not effectively communicate the assessment issue to you...that may be on us.

**Comment by mrmin123** [comment]
@selinad The assessment issue is when someone has assessed an item it should not be deletable, yes? If so, yes, I'll work on a fix tomorrow (today). If I'm missing another detail (I may have missed a finer point or two in the chat...), please let me know. Thanks!

**Comment by mrmin123** [comment]
Quick preview of red dialog box + button:
![image](https://cloud.githubusercontent.com/assets/4326866/11586832/73a97f80-9a2a-11e5-8763-fd90f1eaef06.png)

**Comment by mrmin123** [comment]
@selinad if an item has been assessed, would you prefer:

1. the Delete button to just not be there
2. the Delete button to be visible and clickable with the 'Confirm Delete' button in the popup not being clickable (or visible) with the message saying that you can't delete because someone has assessed it
3. the Delete button to be visible but grayed out, with maybe hover text saying that you can't delete because someone has assessed it?

**Comment by selinad** [comment]
Nice!  I like it.

**Comment by selinad** [comment]
Hi @mrmin123 

The delete button should behave as follows:

* If no one else has assessed the evidence other than the curator who entered the evidence, Delete should be allowed (whether or not that curator has assessed)
* If a 2nd curator has assessed that evidence, Delete cannot be allowed.  
* What follows is that if the 2nd curator changes their assessment to Not Assessed, then Delete can be allowed again for the original curator (who entered the evidence).
* @forresttanaka correct me if I am wrong, but this seems to be the same as how the ability to edit information works.

With respect to your 3 options (thank you), I prefer the third...but @wrightmw can weigh in....

I have meetings until noon today so won't be available until after that - wanted to get you some info sooner than later..

Thanks!
Seilna

**Comment by wrightmw** [comment]
@mrmin123 Thanks. Looks great! I would also prefer option 3... I think that a grayed out box with accompanying hover text would be absolutely clear to curators what is going on.

**Comment by mrmin123** [comment]
Please see http://453-delete-items-badd5fa-minchoi.instance.clinicalgenome.org/ (should be up in about 20 minutes from now). If another user has assessed an Experimental Data or Family object, the Delete button should be displayed but disabled, with a hover text explaining the reason why it's disabled. The Delete button's color and position has also been moved, as well as the color of the Modal.

**Comment by wrightmw** [comment]
I only seem to be able to log on as wrightmw@stanford.edu and not my other two new user names, so I can't currently delete my own edits as a third party

**Comment by selinad** [comment]
@mrmin123 - It looks like the variant associated with Individual remains associated with Family (at least one variant) after individual deleted - this should be removed so that edit family page does not show it and the palette does not show it…

If there were 2 variants associated with an Individual that was part of family, both would need to be removed.

**Comment by selinad** [comment]
Here's what the *ights have tested:

* Delete Individual
* Delete Family
* Delete Group
* Inability to delete on Family that 2nd or 3rd curator has assessed 
* Inability to delete on Expermental that 2nd curator has assessed
* Delete Individual that is part of Family
* Delete Family that is part of Group
* Delete Group that has Family and Individual
* Delete Family that has Individual

All behave as expected - nice! (with exception of the above issue I entered)
Can anyone think of anything else?

nice job!

**Comment by mrmin123** [comment]
New instance with fixed family/individual variant behavior: http://453-delete-items-bc58f4d-minchoi.instance.clinicalgenome.org/

**Comment by mrmin123** [comment]
Updated modal messages:
Group:
![image](https://cloud.githubusercontent.com/assets/4326866/11643545/7c0c7b88-9cf9-11e5-992c-6ae9da7bb8cf.png)

Family:
![image](https://cloud.githubusercontent.com/assets/4326866/11643552/8b88a58c-9cf9-11e5-8687-7896a8b015d0.png)

Individual and Experimental Data:
![image](https://cloud.githubusercontent.com/assets/4326866/11643563/9aac851a-9cf9-11e5-876d-bf36c713e14f.png)

**Comment by selinad** [comment]
@mrmin123 These all look great to me - thx!

**Comment by kilodalton** [comment]
Another great release (R2). Nice job and thanks for your hard work.
