### ISSUE TITLE
Variants list not accessible in production

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#576]
Must test using a copy of production db:

On viewing URL/variants in production:
Uncaught TypeError: Cannot read property '@type' of undefined

**Comment by kgliu0101** [comment]
With the change in schema at ticket #559, this problem is solved. I used dev branch and current product data to create a new instance at https://dev-fe04cd0-kangliu.demo.clinicalgenome.org/ All variants can be viewed at url ../variants.
<img width="996" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/12740105/ddba1af0-c924-11e5-93b4-a33b23cc8ae4.png">

**Comment by selinad** [comment]
Thanks @kgliu0101 - looks good.  Is there a way to show the ClinVar VariationID field in the table?  We may want to plan ahead for the ClinVar preferred name as well?  Apologies if I am missing the point!

**Comment by kgliu0101** [comment]
@selinad It's the ClinVar variant id to cause the problem. To show it automatically, we need either to write a new-version schema or manually to edit current product data.

**Comment by selinad** [comment]
@jimmyzhen -- please review -- thank you!
