### ISSUE TITLE
Owner/Creator in palette

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#601]
Multiple people have noticed that occasionally the curator name underneath items in the curation palette on the right in the GDM seems to change or is incorrect

--needs evaluation to identify the conditions to reproduce the problem
--please check if either the object in palette _and_ check if the object’s assessment object gets incorrect creator info stored (in db), or if it is just UI display that is returning the wrong param (like last person to assess rather than owner).
--needs discussion about whose name should be show as entering a variant

**Comment by mrmin123** [comment]
The curation palette displays the `submitted_by` field in the object, which is changed every time the object is updated. If I remember correctly, in previous discussions we talked about adding a new field to these objects to contain the link to the original submitter which would not change no matter who updates it.

**Comment by selinad** [comment]
I tested curation-test yesterday and it did not change the name - kept name of creator.  I can try again...

**Comment by kilodalton** [comment]
I think we should have a modified_by field that maintains a list of modification objects that each contain user uuids and modification date

**Comment by selinad** [comment]
Also observed that the person who enters a variant for first time is the "owner" of that record, and it doesn't even need to be added to same record.

Here, Matt's name appears but he is not even active in my record:
![screen shot 2016-02-10 at 3 08 01 pm](https://cloud.githubusercontent.com/assets/11320314/12965190/269432e8-d009-11e5-955b-ad405abbe2e4.png)

**Comment by kilodalton** [comment]
@selinad a variant is not attached to a particular gdm currently in our system. Maybe we should suppress the "owner/creator"  display for now if that data needs to be re-worked

**Comment by selinad** [comment]
Here is a Family object in curation-test where Matt and Min have assessed, but I am still listed on palette
![screen shot 2016-02-10 at 3 33 11 pm]

(https://cloud.githubusercontent.com/assets/11320314/12965537/c7d3eb4c-d00b-11e5-8197-aa733638a535.png)

For a variant, I see in test that it shows whoever first entered it into database.

**Comment by mrmin123** [comment]
@selinad Is it possible that you changed your assessment on the Family object after Matt and I assessed on it? That would switch its ownership back to you...

I agree with @kilodalton that maybe the owner/creator fields should be disabled for now... Site-wide we're using the `submitted_by` value to populate this, and by design the `submitted_by` value changes to whoever made the last edit to it (because they're 'submitting' the new version of the object).

Adding the proposed `modified_by` field would require schema changes and further testing that we don't have time to do at this stage of the cycle.

In regards to Variants, that raises an interesting point on how to resolve whose name to display as the owner/creator. Currently the display shows Matt's name because he was the original creator of the variant, so his name is embedded in the `modified_by` field, which would result his name being shown whenever that variant is added in the future. Another approach for the owner/creator field might be to take the `submitted_by` field from the parent Family/Individual/Experimental Data object, but this would be incorrect if another user edited an object originally created by someone else and adds a variant. Going by the proposed `modified_by` field of the parent object would also be tricky if the original creator of the object added the variant, but another user comes in and edits it but without modifying the variant. Also questionable if the variant is referenced by multiple objects in the GDM, all created by different people.

**Comment by selinad** [comment]
excellent point- I could have, even though I did it to test just this.  Does someone want to assess on it again?

https://curation-test.clinicalgenome.org/families/cf0181a0-fdfa-4507-86f3-d82221d8601f/?gdm=7f9988fa-16d9-11e5-ba73-60f81dc5b05a

**Comment by mrmin123** [comment]
@selinad Assessed on it. I think its ownership remained on you, however, which is odd... Does the ownership switching also happen on Family objects in the new RC, or is it just experimental data/variants?

**Comment by selinad** [comment]
Thx @mrmin123 

Can you assess on this one?
https://curation-r4rc1.demo.clinicalgenome.org/families/917078a1-d117-4d74-983d-6eaf53e69506/?gdm=7c9f3091-f49b-4f62-a37b-366339690e5a

**Comment by selinad** [comment]
Behaves properly - maybe it was due to the indexing issue yesterday, so it is behaving as expected?

**Comment by mrmin123** [comment]
OK, I just ran it on a localhost `dev` instance and couldn't reproduce with my two accounts. Maybe it was an indexing issue, like you said?

**Comment by selinad** [comment]
I'm thinking yes - have never noticed that before now...is there a way to tell - maybe just a few more tries?
