### ISSUE TITLE
Fix variant text in "Associated Variants" so that it doesn't wrap to the next line.

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#606]
See issue explained in #581

**Comment by kilodalton** [comment]
From #581:

![image](https://cloud.githubusercontent.com/assets/1878194/12969413/feee5b0c-d034-11e5-8330-b3287eb25d4c.png)

**Comment by mrmin123** [comment]
I changed it so that the text cutoff is done via CSS instead of via JS, and applied it to both the palette and the record header:

Record header:
![image](https://cloud.githubusercontent.com/assets/4326866/13130682/d42ec8b4-d59a-11e5-81ec-5ea2f5a3f5ed.png)

Palette:
![image](https://cloud.githubusercontent.com/assets/4326866/13130695/e54a1662-d59a-11e5-8a3d-09846fe40379.png)

**Comment by wrightmw** [comment]
@mrmin123 Looks good to me.

**Comment by selinad** [comment]
Me too.  @mrmin123 - is there room for the sticky when it appears? thx!

**Comment by mrmin123** [comment]
@selinad Yep!: 
![image](https://cloud.githubusercontent.com/assets/4326866/13154395/96723f72-d62d-11e5-839a-13b5e51ae80a.png)

**Comment by wrightmw** [comment]
@mrmin123 Great!

**Comment by selinad** [comment]
Nice :+1: 

Thanks @mrmin123 !

**Comment by wrightmw** [comment]
Looks good

**Comment by selinad** [comment]
Woot!  Looking good.

**Comment by kilodalton** [comment]
Included in last release (R5). Nice job and thanks for your hard work.
