### ISSUE TITLE
Fix overhanging labels on curation palette

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#638]
Long labels for Individual (and I assume others) overhang on curation palette.  

![](https://cloud.githubusercontent.com/assets/11320314/13831949/be6f8d64-eb94-11e5-8d2f-86438fe33661.png)

**Comment by mrmin123** [comment]
The same fix made for Variant titles in the Curation Palette can be made here: 413fb96

The best route to go is probably to rename the `.variant-title-ellipsis` class to something more generic, then applying it to the `h5` tags for the titles in `curator.js`, mimicking what was done for Variants: https://github.com/ClinGen/clincoded/blob/dev/src/clincoded/static/components/curator.js#L829

**Comment by mrmin123** [comment]
Also needs to be extended to Associations:
![image](https://cloud.githubusercontent.com/assets/4326866/13860486/c8f17fc0-ec45-11e5-83d3-9c48dc538fa6.png)
![image](https://cloud.githubusercontent.com/assets/4326866/13860487/cd27bd0c-ec45-11e5-8df6-e774c9de5bbd.png)

**Comment by mrmin123** [comment]
@selinad @wrightmw 
Ellipsis everywhere...: http://638-mc-curation-palette-labels-ec8da25-minchoi.instance.clinicalgenome.org/

Please note that I changed the text color of the Variants in the Curation Palette to Black to make it consistent with the other text. Hovering over the black text w/ dotted underline displays the full text in a popup. If you want this to change just let me know!

![image](https://cloud.githubusercontent.com/assets/4326866/13864208/e3302c80-ec5c-11e5-9e3e-93f38d798037.png)
![image](https://cloud.githubusercontent.com/assets/4326866/13864215/ec20dcb8-ec5c-11e5-83a8-da3d63a20e66.png)

Variant Header still works properly, as well (confirming due to overlapping CSS changes):
![image](https://cloud.githubusercontent.com/assets/4326866/13864243/2360fd34-ec5d-11e5-9a26-7c4223b7851f.png)

**Comment by wrightmw** [comment]
This looks great @mrmin123 , as we discussed my only issue is with curators being able to add very long labels. I've created a separate ticket for this, see #640 .

**Comment by mrmin123** [comment]
Fixed also on Dashboard, just in case:

Previously:
![image](https://cloud.githubusercontent.com/assets/4326866/13864976/868e1184-ec63-11e5-9fdf-6cacff760e5a.png)

Fixed:
![image](https://cloud.githubusercontent.com/assets/4326866/13864965/6e937754-ec63-11e5-9b70-55ce0c64689d.png)

**Comment by wrightmw** [comment]
@mrmin123 Good thinking. Looks great.

**Comment by selinad** [comment]
Nice!  Thanks for thinking about other places this will be a problem.  I think setting a limit will be fine (trying to catch up, but saw that question somewhere)...

**Comment by selinad** [comment]
p.s. I think the black text for the variant name is appropriate....

**Comment by wrightmw** [comment]
Looks good to me.

**Comment by selinad** [comment]
thumbs up!  Looks good.

**Comment by kilodalton** [comment]
Included in last release (R6). Nice job and thanks for your hard work.
