### ISSUE TITLE
The edit form of Group/Family Method does not retain pre-existing data

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#645]
**Steps to reproduce the bug:**
1. Add a new PMID on the **Curation Central** page.
2. Click on the blue bar of Group in the far-right column to proceed to the **Group Curation** page.
3. Fill out the necessary form information, **AND** particularly the **Group - Method** section. 
4. Submit the form and create an associated family curation prior to returning to the Curation Central page.
5. On the **Family Curation** page, fill out the necessary form information, **AND** particularly the **Family - Method** section. 
6. Submit the form and return to the Curation Central page. Click on the **View** link in the Group curation panel, and verify the previously filled data being present on the subsequent View page.
7. Return to the Curation Central page. Click on the **Edit** link in the Group curation panel, and verify the previously filled data being absent on the subsequent Edit form.
8. Repeat the above verification for the Family curation data.

The bug in question is also reproducible on the curation-test site:
https://curation-test.clinicalgenome.org/group-curation/?editsc&gdm=ef9a6fa1-16d9-11e5-9918-60f81dc5b05a&evidence=06492f29-568d-4257-b6ec-799203a3593d&group=50f09e1d-5f00-4a9f-8928-57cc5975b341
https://curation-test.clinicalgenome.org/family-curation/?editsc&gdm=ef9a6fa1-16d9-11e5-9918-60f81dc5b05a&evidence=06492f29-568d-4257-b6ec-799203a3593d&family=a805015a-5cb6-472e-b0ba-357563e1bf02

**Comment by mrmin123** [comment]
This also happens with SOME fields in the Individual form:

* Country of Origin
* All fields in Methods section, excluding Description of Previous Testing and Description of genotyping method (the freetext boxes)

**Comment by jimmyzhen** [comment]
The bug appears to be the result of missing _"value"_ attributes in the **<option>** tags in the method.js file. For example, currently the **<option>** tag in the code is `<option>Exome sequencing</option>` instead of `<option value="Exome sequencing">Exome sequencing</option>`.

After I added the _"value"_ attributes to all the **<option>** tags in the method.js file, the pre-existing form data is now present in the Group/Family - Method forms.

I recall that I had to tackle similar bugs in other parts of the site during the React 14 upgrade. Unfortunately this form group did not get on my radar.

**Comment by jimmyzhen** [comment]
The missing data for the Country of Origin appears to be caused by the same issue. Currently the code to render the country dropdown is:
`return <option key={country_code.code}>{country_code.name}</option>;`

After I changed it to the following:
`return <option key={country_code.code} value={country_code.name}>{country_code.name}</option>;`

The country selection is retained in the edit form.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have spun up an instance for verifying the fixes in addressing the reported problems in this ticket:
https://645-jz-edit-form-missing-data-bf3712b-jzhen.demo.clinicalgenome.org

Please let me know if you have any questions. Thank you.

**Comment by selinad** [comment]
Hi @jimmyzhen - this looks great!  I filled out all possible items in G, F and I and edit (and view) pages all looked good.

One thing - thought I should look at experimental and came across this difference in edit and view pages: - the empty field (cell-culture type/line) is something that would show if engineered equivalent picked instead of animal model.  Would it be easy to suppress?  If so, let me know if I should make another ticket.  The opposite is true if one picks engineered equivalent (it shows empty animal model field).

Thanks!
Selina

![screen shot 2016-03-29 at 11 27 47 am](https://cloud.githubusercontent.com/assets/11320314/14119111/796618c0-f5a1-11e5-9ed5-4af97e88396e.png)

![screen shot 2016-03-29 at 11 28 00 am](https://cloud.githubusercontent.com/assets/11320314/14119123/7f997052-f5a1-11e5-8e6d-8b073a5dfd5a.png)

**Comment by jimmyzhen** [comment]
Hi @selinad,

It should be a simple fix, so I don't think we need a new ticket for that.

Would you want me to spin up a new instance for your to review after the fix?

**Comment by selinad** [comment]
Hi @jimmyzhen - thanks! If you see that it works correctly, I don't think an instance is needed.  I can come check it out on your local machine if you like.

**Comment by selinad** [comment]
Hi @jimmyzhen - all your changes look great.  

One thing I noticed - seems somewhat familiar.  On the View page for a group, there is an additional field that is not on the Edit page:  "Additional Information about Group Method"  - not quite sure whether this was lost to Edit somehow....the equivlaent is on the Family Edit page.  Can you tell why that field is not on the Edit page for a Group?

thx!
Selina

**Comment by wrightmw** [comment]
@jimmyzhen I concur that the changes look great.  Good spot @selinad ... consistency is our watchword :-)

**Comment by kilodalton** [comment]
@selinad @wrightmw Regarding "Additional Information about Group Method”:
I posed a question about this display item you are asking about on April 6 to both curators but did not get a response: 
> curators: question: I noticed that on the view page for a Group we show "Additional Information about Group Method” but we actually only capture that additional method info for Family (it is explicitly in the methods.js that it is for Family only). Should we be capturing that info also for Groups (on creation and edit)? 
note that it is been this way since August, but I noticed in the course of testing a PR
In other words, is there any reason not to add this field for create/edit pages for Group Methods?
Individual does not collect info for the "additional info for the method” field, but then correctly does not show "Additional Information about [Individual] Method”  on the view page```

This should be addressed in a separate ticket, however

**Comment by selinad** [comment]
Hi @kilodalton - maybe that's why it sounds familiar.  I'm sorry we did not respond (did we miss it on github?).  

We can check with the gene curation group as to what they want.  I'll do that and make a ticket according to what they say.  It is not a problem for this release to leave it as is.

thx,
Selina

**Comment by kilodalton** [comment]
Included in last release (R6). Nice job and thanks for your hard work.
