### ISSUE TITLE
Create Variant Selection Page for the Variant Curation Interface

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#669]
We need to create a Variant Selection Page (VSP) for the Variant Curation Interface (VCI). This will be the landing page for curators to specify the variant they are looking at. It will contain two modals: 1) 'ClinVar modal' for searching ClinVar for the ClinVar Preferred title #668  ; 2)''CAR modal' for searching for the canonical allele data for a variant in the ClinGen Allele Registry (CAR) #670  .

**Comment by wrightmw** [comment]
![vsp](https://cloud.githubusercontent.com/assets/15131169/14957131/6ac1ffc6-1038-11e6-97eb-2b153b2d9fa1.png)

**Comment by mrmin123** [comment]
What I have so far for the ClinVar variant ID selection:

![image](https://cloud.githubusercontent.com/assets/4326866/15087669/d488f440-139f-11e6-89f1-9c55b91cd5b5.png)

**Comment by selinad** [comment]
Looking good, @mrmin123 !

I'm gonna say that I think I will like it better without the grayed out menu bar and the search instructions, but that's me.  I'd prefer a title that indicates one is looking at results...

Will you add in the button to return to the original page where one makes a selection?

**Comment by wrightmw** [comment]
@mrmin123 Looks great! What about changing the 'Clear Variation ID' to 'Cancel Variant Selection' which keeps it consistent with the other buttons?

**Comment by mrmin123** [comment]
@selinad @wrightmw I'll make it so that the directions and the dropdown disappear when variation data is fetched and displayed. Since the displayed elements from pre-fetch and post-fetch are completely different and might seem as if the user is changing pages, I'll make the button say 'Cancel Variant Selection' as Matt has suggested.

**Comment by mrmin123** [comment]
(Personal) note for convenience: this ticket is heavily connected to #668 and #670

**Comment by mrmin123** [comment]
Stalled on #670 for now so going back to work on the UI elements.

**Comment by selinad** [comment]
Addition:

When returning ClinVar information, please store returned rsID in the database.
When returning CA ID, please store:
* returned CA ID
* any returned rsID
* GRCh37 NC_ (HGVS)
* GRCh38 NC_ (HGVS)

Please let the *ights know if you have any questions. thx!

**Comment by kgliu0101** [comment]
Related schema change is in ticket #676

**Comment by selinad** [comment]
Most up-to-date wireframe is in Asana under "Wireframes" - files is "search-select-variant-details-2.pptx"

**Comment by selinad** [comment]
Hi @jimmyzhen - an update after our call with the variant curation team today.

Can you return not only the ClinVar preferred title in the modal window, but also all the other stuff that was going to display on the page after saving it? (i.e. the other HGVS representations).  That way, if it's not correct, the user can just edit in the modal window and not have to go back and edit the variant from the page.  Let me know if that doesn't make sense.

Also, they had a preferred order for sorting and displaying - I can catch you up on it as I am not sure it is easy....

Let me know if you need me to change the mockup.

Thanks!

**Comment by mrmin123** [comment]
@selinad (you pinged the wrong person but) this is doable.

The sorting of the HGVS representations is another discussion... I briefly talked about this with @wrightmw and we chose to go ahead with the order it's listed in the JSON/XML response we get, while promoting the `NC` codes, but if this needs to change it can. I would almost recommend making this a separate ticket, however.

**Comment by selinad** [comment]
Ugh - sorry about that.  Doing everything too quickly this week.

Sounds good re sorting - let's hold off on that.  Not needed for the first phase and we can make a ticket.

thanks @mrmin123 !

**Comment by mrmin123** [comment]
@selinad @wrightmw 

Instance up here:
http://669-mc-select-variant-page-ba49b0d-minchoi.instance.clinicalgenome.org/

This instance has #675 (link to select variant page from Dashboard), #668 (ClinVar modal), and #669 (CAR modal). You should be able to get to the select variant page from the dashboard (first link under Tools), set whether you want to query ClinVar or the CAR, open the correct modal, and return the information. Upon closing the modal, a new variant object should be created within our database with the variant information (ClinVar ID, ClinVar Preferred Title, CAR ID, HGVS terms, dbSNPIDs; all if applicable).

Caveats/to-dos:
* Wording for everything can still be revised. I might have missed the wording in the modals, especially, so that's one thing to check
* No forwarding to @jimmyzhen's VCI hub as of yet (will be passing variant UUID)
* As discussed in Monday's meeting, querying the CAR should subsequently query ClinVar if the CAR returns a ClinVar ID. This is not yet implemented (to be done in a separate ticket)

Let me know if I'm missing anything.

**Comment by selinad** [comment]
Hi @mrmin123 it's so fun to have something to "interface" with!  Really nice job.

Here are some comments walking through:

**On Instruction section**
- could we add a space between the numbered steps?
- Here is correct link for ClinVar (step 2): http://www.ncbi.nlm.nih.gov/clinvar/ 
- Here is test link for CAR (step 3): http://reg.test.genome.network/site/registry (this is test interface - we should ask them for best one)
- I'm thinking steps 4 and 5 should maybe be indented as a. and b. under step 3. -  @wrightmw what do you think?
- Current step 5 - reword to: "If ClinGen Allele Registry does not find a ClinVar ID, register the variant to return a CA ID and then select "ClinGen Allele Registry ID (CA ID)" from the pull-down and enter the CA ID."

**Menu Bar**

- Should we have something on the menu bar next to "Select Variant by ID type" (e.g. No Selection, or whatever matches our usual terminology?) 
- Should probably be able to go back to No Selection (if that is usual protocol)


**ClinVar VariationID selection**

- Picky - left justify Add ClinVar ID with the menu bar

**ClinVar Variant modal**

- We can now change the text a bit in the blue box as they are displaying the VariationID on the page now.  Change to: "You must enter a ClinVar VariationID.  The VariationID can be found in the light blue box on a variant page - example: 139214)."
- Can "Save" actually turn in to "View Variant" and take them to @jimmyzhen 's evidence hub, or does it need to behave like it does in Gene Curation since it is shared?  Asking as the next steps seem slightly redundant.
- If Ihave canceled and then entered at CA ID instead of ClinVar I think the CA ID still showing, which would be a bug...or are you returning CA ID for a ClinVar entry? Actually, maybe you are displaying it if it is already in the database because it has been entered! Is that correct?  That would be good.


**CAR Variant selection**
Change text to "Add CA ID" (on button)
Can you left justify button (see above)


**CAR Variant Modal**

- Update text: "You must enter a ClinGen Allele Registry (CAR) ID (CA ID).  This CA ID is returned when you register an allele with the CAR (example: CA139214)."  
- The "example" link will need to go to the CAR URL (not quite sure how to provide that URL given the searching on the CAR - can you get it for CA139214?
- When I typed in CA139214, I returned what I think is the ClinVar preferred title - is there more info to return? (maybe you are working on this with Piotr)
- Same as above - let's discuss what "Save" button Can/Should do..

Great work!
-S

**Comment by mrmin123** [comment]
@selinad Above items with ✅ have been taken care of. My own brief comments are in *italics* after the checkmark. Regarding the other items:

**Menu Bar**

* We can add something (maybe 'Select', which is used in the create GDM page?) In the create GDM page, you cannot move back to 'Select', however. It seems pointless to let the user go back to the 'Select'/'No selection' item since then the user wouldn't be able to do anything else...

**Add/Edit Button positioning**

* I'm not sure what you mean by left justify... you mean to the far left side of the panel? I should note that this button is (programmatically) the same button as the 'Edit ClinVar/CA ID' buttons... wherever I move this, the Edit button moves with it.

**Save button behavior**

* We can definitely make the user be forwarded when they hit 'Save' in the modal, but that will require additional work since that's not a behavior we want in other places (GCI curation pages) and I'd have to code in allowances for that. I'm also leaning towards having the data be returned to the somewhat-redundant select variant page because in the future we might show the different interpretations that exist for that variant at this page? (I'm going off the wireframe here... correct me if that's outdated/if I'm wrong)

**Comment by wrightmw** [comment]
1) Yes, I think points 4 and 5 should be indented as a) and b) because they are the two potential outcomes of doing point 3.

**Comment by wrightmw** [comment]
2) I agree that the "Add ClinVar ID" button should be left-justified in line with menu. However, I would also left-justify the "Edit ClinVar ID" and "Edit CA ID" buttons.

**Comment by wrightmw** [comment]
3) I agree that when a curator has retrieved the correct ClinVar ID in the VSP modal, they should be able to "Select Variant" which will forward them directly to the Variant Evidence Hub... see ticket #681

**Comment by wrightmw** [comment]
4) In the CAR modal:
- change "Enter CAR ID*" text to "Enter CA ID*"
- change button text from "Retrieve from CAR" to "Retrieve from ClinGen Allele Registry"
- change descriptive text to start with  "You must enter a ClinGen Allele Registry ID (CA ID). This CA ID is returned..."

**Comment by wrightmw** [comment]
5) In the CAR modal after retrieving results. The ClinVar Preferred Title will not be available if the variant is not in ClinVar... in such instances then currently the title field in the our CAR modal will be blank. The CAR shows the CA ID as the title when there is no associated ClinVar entry.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
