### ISSUE TITLE
Static header for the Variant Curation Hub pages

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#671]
There will be a static header present at the top of all the Variant Curation Hub pages. The specifications for this header are currently under review by the Small Variant Curation Working Group.

**Comment by jimmyzhen** [comment]
The screenshot below shows what I have implemented so far for the Variant Curation Hub:
![image](https://cloud.githubusercontent.com/assets/6956310/15088474/64c0aa36-13a9-11e6-8ed3-78f1eacd968a.png)

The tabs are functional and just need some styling to match the overall theme.

At this point, the variant data that I can extract from the existing variant data model are somewhat limited and thus a number of fields are displaying "unknown" instead of the expected values.

**Comment by selinad** [comment]
Wow!  You guys are really moving this along!

Looking great, @jimmyzhen !

We will probably have some changes for your to the gray bar.

One thing - could we put in headers for each column in the gray bar - e.g. ( @wrightmw can comment):
* Variant Information
* Associated Gene Information
* Evidence History

Steven is working on what they want in gray bar area, so leaving it as is for now is great - I'll try again to get this info from him.  Otherwise, @wrightmw and I can clean it up.

The "Creator" for this part may not be appropriate - we might need that only when someone starts an interpretation.

Also, the number of tabs and the exact wording might change - need to check with Steven on this as well.  You guys are already ahead of the ball!  I'll work on this on Monday.

-S

**Comment by jimmyzhen** [comment]
Hi @selinad,

What I have so far is quite rough and thus further changes/modifications are expected. Feel free to let me know when there are additional change requests aside from adding headers for the top gray bar.

**Comment by selinad** [comment]
Will do,  @wrightmw and I will sit down Monday AM and take a hard look at this and what comes next.  We should have something by Monday afternoon. thx!

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

The headers have been added as shown below:
![image](https://cloud.githubusercontent.com/assets/6956310/15089261/98e68fa0-13b4-11e6-9923-822c1598e7b8.png)

**Comment by selinad** [comment]
Thanks @jimmyzhen !

On first look, my eye is drawn to the first row in the light gray row rather than the "header" row, which is darker gray and seems like it belongs to the variant title.  Could it stay within the light gray and maybe be a bigger font - or, maybe there is another way to distinguish.  (e.g. it is in light gray box, but there is white border line?).  Not sure, but right now it seems to get a bit lost... I'll think some more.   Whatever we do, keeping it simple to program is important

Thanks!
Selina

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

I have updated the style of the headers of the gray boxes atop, as well as the tabs:
![image](https://cloud.githubusercontent.com/assets/6956310/15190427/ae172f98-1764-11e6-9e53-2fa9a0bd4e92.png)

Let me know if you have any questions.

**Comment by wrightmw** [comment]
I think the curators did not want to see the basic IDs in the header. e.g. ClinVar VariationID, CA ID, dbSNP ID should be moved to the Basic Information tab. @selinad do you concur?

**Comment by selinad** [comment]
My impression was that - however, I think we should do what we think best as we don't have specs from them.  Maybe we provide links from the words - e.g.

ClinVar
ClinGen Allele Registry
dbSNP

Then, for gene - e.g.

SMAD3 [NCBI] [HGNC] [UniProt] [GeneCards]

Disease
disease name [OMIM]
disease name [Orphanet]

**Comment by wrightmw** [comment]
@selinad I like your thinking with respect to providing links to the main resources. How about going back to something you had in a previous iteration that I liked. Having the links permanently under the header for curators to link out to. Then the static banner is not a mixture of links and information, the links are separate.  
I also think that if there is a disease associated then it will already be displayed in the below the ClinVar preferred title, so it would be repetition to display it in the static banner. I'm thinking we just display the transcript info, status/creator/edit dates, and interpretations in the static banner. See below for example:
![variant curation interface header](https://cloud.githubusercontent.com/assets/15131169/15192962/88132caa-1770-11e6-86ed-115f18733fba.jpg)
I'm totally open to changing any bit of this :-)

**Comment by selinad** [comment]
The links I had previously were to the resource as a whole - the ones I was talking about would be specific to the variant.

For instance, the diseases would be all diseases known to be associated with the variant (via OMIM, Orphanet, etc.) - NOT the disease being interpreted.  This page is the evidence pool page, so there is not necessarily a disease yet.

For now, it might be good if you and I work out the header, @wrightmw and you and @jimmyzhen work on what info to pull back for the basic info and how to do it?

**Comment by wrightmw** [comment]
@jimmyzhen We need to add the IDs to the links in the static bar. 
ClinVar VariationID:#
ClinGen Allele Registry CA:# (if this field is null then do not show)
dbSNP rs#

**Comment by wrightmw** [comment]
Replace Edit with "Currently editing" on current interpretation; remove View option

**Comment by jimmyzhen** [comment]
@selinad, the dbSNP LinkOut bug can be added to this ticket for me to fix.

**Comment by selinad** [comment]
Is it what @wrightmw reported above?

**Comment by jimmyzhen** [comment]
@selinad Yes, it is.

**Comment by jimmyzhen** [comment]
@selinad, we just discussed this issue in the meeting and have decided to create a new ticket for it:
https://github.com/ClinGen/clincoded/issues/779

**Comment by selinad** [comment]
Thanks, @jimmyzhen - I updated the spreadsheet

**Comment by wrightmw** [comment]
Static header is there, as expected

**Comment by selinad** [comment]
Looking good!  There and remains throuhout!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
