### ISSUE TITLE
Update variant data source handling for CAR

### ISSUE THREAD

**Issue by mrmin123** [ClinGen/clincoded#682]
If the CAR responds with a ClinVar variation ID, the page should silently ping ClinVar in the background to obtain information from them.

~~edit: Also needs better handling of erroneous responses from the CAR~~ (#684)

**Comment by mrmin123** [comment]
Testing CA IDs (for personal reference):

CA004123, CA009941 (in CAR, in ClinVar; has ref genome)
CA033442, CA001400 (in CAR, not in ClinVar; has ref genome)
CA091413 (in CAR, not in ClinVar, no ref genome)
CA999999 (not in CAR, not in ClinVar; 404)

**Comment by mrmin123** [comment]
@selinad @wrightmw Instance up at http://682-mc-car-parsing-fdf84e0-minchoi.instance.clinicalgenome.org/

I used the above CA IDs above to test.

* The first set of CA IDs should return ClinVar information, and when saved, the resulting variant object should have the ClinVar information as well as the CA ID, and have the NC hgvs term saved under its proper reference genome
* The second set of CA IDs should return CAR information, and when saved, the resulting variant object should have the CAR information (including CA ID) and have the NC hgvs term saved under its proper reference genome
* The third set of CA ID should return CAR information w/ no preferred title, and when saved, the resulting variant object should have the CAR information (including CA ID), but no NC hgvs term
* The fourth set of CA ID should return an error under the input field saying that the CA ID does not exist

Please note that this instance has the fix for #684, as well as the un-ticketed action item of parsing in reference genome information from the CAR

**Comment by selinad** [comment]
HI @mrmin123 - looking good!  Here are a few comments:

- If I select either ClinVar or CAR from the pull-down, I can't get back to Select on the drop down
- "ClinGen Allele Registry" link for step 3. doesn't go to the CAR - do you need URL?  I believe it might be: http://reg.genome.network/site/cg-registry, but could check.  My permissions don't work here, but it does ask for a login, which is why I think it is production.
- "ClinGen Allele Registry" link for steps 3a and 3b go to test - I think we can change to production?
- On ClinVar modal, let's say "Select "View Evidence" below to see the evidence for this variant if it is the correct variant, otherwise...." (note that "Variant" should not be capitalized after the word "this" and I changed "Press" to "Select").  @wrightmw I like "View Evidence" better than "View Variant" - what do you think?
- Should we change "You must enter a ClinVar VariationID.." to "Enter a ClinVar VariationID...."?  It looks like an error with the "you must," especially since it appears if I delete a number.
- I registered this allele: CA501026 - when I retrieve it in our interface, it interface does not bring back the genomic allele: CM000669.2:g.155803019G>T (only the transcript allele) - sorry, I can't remember whether there is a reason for this.  And, @wrightmw, it does not bring back GRCh37 (can't remember....did you write them about this?)
- An allele in ClinVar looks good when entered through the CAR modal.  

Nice work!

**Comment by mrmin123** [comment]
Hi @selinad and @wrightmw 

* For the first point, not being able to go back to the Select in the dropdown is consistent with the rest of the site
* For the last point, CA501026 does not have an NC value associated with the GRCh38 genomic allele. At the moment we are removing all CM values. Should we use CM as a fallback if no NC value exists?

Also, the previous example CA ID for the modal did not exist, so I switched it to CA003323. If you have another CA ID you'd prefer, please let me know.

I've also switched over all CAR URLs to production.

**Comment by selinad** [comment]
Thanks, @mrmin123.

If the pull-down is consistent, that's good - obviously, it has not bothered me before.

We are going to talk to Baylor about the CM's and NC's today, so we can provide a clearer example after that.

That allele looks good (CA003323).  Thanks!

**Comment by mrmin123** [comment]
@selinad @wrightmw New instance: http://682-mc-car-parsing-f991667-3.instance.clinicalgenome.org/

**Comment by selinad** [comment]
Hi @mrmin123 thanks on the instance.

Picky detail - interface says "If ClinGen Allele Registry does not find a ClinVar ID, register the variant to return a CA ID and then select "ClinGen Allele Registry ID (CA ID)" ", but the pull down says  "ClinGen Allele Registry ID."  Let's have the pull-down say the same thing: 

"ClinGen Allele Registry ID (CA ID)"

If I add a new CA ID that has a CM and an NM, it only returns the NM, not the CM….sorry, I can’t remember whether this is expected.  See NM_025137.3:c.118C>A = CA501011

**Comment by mrmin123** [comment]
@selinad Fixed the dropdown and the URL.

**Comment by selinad** [comment]
great - thx @mrmin123

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
