### ISSUE TITLE
Population Tab on Variant Curation Evidence Hub pages

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/clincoded#683]
There will be a tab on the Variant Curation Evidence Hub pages that will show the allele frequency (and other associated fields) in specific populations. These population frequency data are generated by GO-ESP (ESP), ExAC, and 1,000Genomes (1KG). The ACMG guidelines only require ESP, ExAC and 1KG as a minimum and so for the MVP we will only be supplying these, but future iterations will no doubt include additional data sources that provide allele frequency data for other specific populations. We are looking into potentially downloading the ESP, ExAC and 1KG data we require all in one go via the Variant Effect Predictor (VEP), however if this is not possible then we will have to source from each of these sources separately.

**Comment by wrightmw** [comment]
Sample output of ESP on their website (http://evs.gs.washington.edu/EVS/), example is for rs3092995:
![screen shot 2016-05-19 at 3 37 10 pm](https://cloud.githubusercontent.com/assets/15131169/15411834/a79ebd4c-1dd7-11e6-8f57-c3ae72247841.png)

Variant Pos: The SNV location on the chromosome (NCBI 37 or hg19) is based. 
rs ID: dbSNP reference SNP identifier (if available)
Alleles: The alleles are listed in the HGVS variant notation, for the ESP project, it always refers to a change from a reference allele to an alternate allele.
EA Allele: The observed allele counts for the listed alleles in European American population 
AA Allele: The observed allele counts for the listed alleles in African American population
All Allele: The observed allele counts for the listed alleles in all populations
EA Genotype: The observed genotype counts for the listed genotypes in European American (EA) population
AA Genotype: The observed genotype counts for the listed genotypes in African American (AA) population
All Genotype: The observed genotype counts for the listed genotypes in all populations

**Comment by wrightmw** [comment]
Sample output of ExAC on their website (http://exac.broadinstitute.org/variant/17-41197659-G-C), example is for rs3092995:
![screen shot 2016-05-19 at 3 50 29 pm](https://cloud.githubusercontent.com/assets/15131169/15412086/b53f1fee-1dd9-11e6-8cfa-d9e4fa6e7f9e.png)

**Comment by wrightmw** [comment]
Note: 1KG provides allele frequencies for African (AFR), American (AMR), East Asian (EAS), European (EUR), South Asian (SAS), and all (ALL) populations. They also provide some sub-population data.
![screen shot 2016-05-19 at 4 07 27 pm](https://cloud.githubusercontent.com/assets/15131169/15412370/d67d3252-1ddb-11e6-8296-d3afc18c49d5.png)

Sample output of 1KG on their website (http://browser.1000genomes.org/Homo_sapiens/Variation/Population?r=17:41197159-41198159;v=rs3092995;vdb=variation;vf=2302546), example is for rs3092995:

**Comment by wrightmw** [comment]
The variant curation working group has generated two tables to show how these data could be represented in the Population Tab:
![screen shot 2016-05-27 at 3 12 33 pm](https://cloud.githubusercontent.com/assets/15131169/15622670/e7e46f34-241f-11e6-9ed2-5b681da0d368.png)
The table on the LHS is the ExAC data. The RHS one is the ESP and 1KG data.
- they have the population with the largest frequency highlighted and the other populations greyed out, this feature is not essential for the MVP
- they provide both counts and frequency data for each population
- they include a Y/N column on whether the data for each specific population should be added to the summary, in the MVP we will probably not provide this option. Instead the whole set of population data will be saved as a blob
Note to devs: when they say 'WT" they are referring to "wild-type" which means the allelle found in the reference genome. This is also known as the "reference allele" in other sources.

**Comment by selinad** [comment]
Specifications for information curators would like to see on Population tab.  We can discuss. Will also include wireframe shortly.

**1000G** (http://browser.1000genomes.org/Homo_sapiens/Variation/Population?r=17:41197159-41198159;v=rs3092995;vdb=variation;vf=2302546)

1. "Allele: frequency (count)" for each of these populations
- ALL
- AFR
- AMR
- EAS
- EUR
- SAS

2. "Genotype: frequency (count)" for each of these populations
- ALL
- AFR
- AMR
- EAS
- EUR
- SAS

3. NHLBI Exome Sequencing Project - "Allele: frequency (count)"
- ESP6500: African_American
- ESP6500: European_American

**ESP** (http://evs.gs.washington.edu/EVS/; rs3092995)

1. Variant GRCh37 Pos
2. rs ID
3. Alleles
4. EA Allele (#)
5. AA Allele (#)
6. All Allele (#)
7. EA Genotype (#)
8. AA Genotype (#)
9. All Genotype (#)
10. Avg. Sample Read Depth


**ExAC** (http://exac.broadinstitute.org/variant/17-41197659-G-C)

1. Constraint score (this found in downloadable file)
2. Allele Count
3. Allele Number
4. Number of Homozygotes
5. Number of Hemizygotes
6. Allele Frequency
7. Depth coverage (for All Individuals) - click on Genotype Quality Metrics to see this data; if variant is absent from ExAC, also want coverage (see if downloadable file has this)
8. Filter Status (e.g. PASS)

**Comment by selinad** [comment]
Hi @jimmyzhen - I've uploaded the newest version of the Population tab to Asana (Population-tab_6-3-2016).  This is our clearest vision of what the curators want and was vetted with the task team on our last call.  @kgliu0101 I added in the missing 'met/not met' component and some other context.  Please use this file for the latest and let @wrightmw and me know if you have any questions.

Thanks!
Selina

**Comment by jimmyzhen** [comment]
@selinad, @wrightmw, I notice that the Allele Frequency for the "Other" population appears to be missing from myvariant.info data, in addition to "Filter Status" and "Median Coverage" that we already know.

**Comment by selinad** [comment]
Thanks @jimmyzhen - we can ask them today if this is something they use

**Comment by wrightmw** [comment]
@jimmyzhen: Are you sure it just isn’t nil for the example you are looking at? In the examples I have looked at the “other” data is there, e.g. see http://myvariant.info/v1/variant/chrX:g.101909103T%3EC , can you provide a link for an example where the “other” data is missing? Thanks.

**Comment by jimmyzhen** [comment]
@wrightmw Here is the example: http://myvariant.info/v1/variant/chr7:g.107423522C%3EG

In the example you provided above, the Allele Frequency for "Other" population appears to be missing as well. Below is where it is expected to be found:
```
exac: {
ac: 2,
adj_ac: 1,
adj_af: 0.0000114,
af: 0.00001647,
afr_ac: 0,
afr_af: 0,
amr_ac: 0,
amr_af: 0,
eas_ac: 0,
eas_af: 0,
fin_ac: 0,
fin_af: 0,
nfe_ac: 1,
nfe_af: 0.00002084,
sas_ac: 0,
sas_af: 0
}
```

Please let me know if I am looking at the wrong place. Thanks.

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw, @kilodalton, @kgliu0101, @mrmin123,

So far for the Population tab UI, I have done the following:
1) Pulling data from myvariant.info to populate the **Allele Count**, **Allele Number**, **Number of Homozygotes** columns for all populations in the ExAc table.
2) Pulling data from VEP to populate the **Allele Frequency** column for all populations in the ExAC table. This is implemented in such way because the ExAC allele frequency data is not always present in the myvariant.info API response for certain variants, even though frequency data is present at ExAC and in the VEP API response. See table below for reference and compare the presence/absence of `{dbnsfp: {exac: {...}}}` in the myvariant.info responses.

| Datasource | Missing allele frequency in myvariant.info | Has allele frequency in myvariant.info |
|---|---|---|
| myvariant.info  | http://myvariant.info/v1/variant/chr15:g.67358465C%3ET | http://myvariant.info/v1/variant/chr7:g.107423522C%3EG |
| VEP | http://rest.ensembl.org/vep/human/id/rs144374592?content-type=application/json | http://rest.ensembl.org/vep/human/id/rs386833446?content-type=application/json |
| ExAC | http://exac.broadinstitute.org/variant/15-67358465-C-T | http://exac.broadinstitute.org/variant/7-107423522-C-G |

3) Pulling data from VEP to populate the **Allele Frequency (count)** and **Genotype Frequency (count)** columns for all populations in the 1000G table (e.g. http://rest.ensembl.org/variation/human/rs1801133?content-type=application/json;pops=1;population_genotypes=1).
4) Pulling data from myvariant.info to populate the **Allele Count** and **Genotype Count** columns for all populations in the ESP table. Because the ESP allele and genotype data is not always present in the myvariant.info API responses for certain variants, we have decided to display a message in the table similar to "Variant information can not be found. Please see [[link]](url)" when ESP data is unavailable. See table below to compare the presence/absence of `{evs: {...}}` in the myvariant.info responses.

| Missing ESP data in myvariant.info | Has ESP data in myvariant.info |
|---|---|
| http://myvariant.info/v1/variant/chr7:g.107423522C%3EG, http://myvariant.info/v1/variant/chr7:g.107423741C%3ET | http://myvariant.info/v1/variant/chr15:g.67358465C%3ET |

What I have not implemented:
1) The supposedly pre-populated fields in the **Highest Minor Allele Frequency** section on the Population tab.
2) Replace the dashes (e.g. "--") with gray boxes for fields that are not present in the API responses.

Known issues:
1) Neither myvariant.info nor VEP has the ExAC "Filter Status" and "Median Coverage" data in their responses.

Please feel free to ask me any questions in this regard.

**Comment by jimmyzhen** [comment]
With my latest committed changes, the tables can be populated with variant data as the following:
![image](https://cloud.githubusercontent.com/assets/6956310/16068044/425f923a-3277-11e6-854f-ca69bdb9320a.png)

I derived at the data sets above by using the "139214" ClinVar variation id from the variant selection interface.

**Comment by selinad** [comment]
@jimmyzhen thank you so much - this is really great!

A few things:
* You wrote: "Please see [link]"" - confused on where this is supposed to go?
* Will # Hemizygotes display for variants on X chromosome?
* Instead of "(See ESP data)," for instance, we may want to indicate that the users will go to ESP itself for the variant.  Maybe "View variant in ESP" - I guess that they will go to the page that could be about an rsID rather than a specific variant?, but that's still OK....
* For ESP since using myvariant.info, you are including rsID because it exists in addition to specific change, correct?  Maybe put the relevant IDs below the ESP header somehow, not in same bar?
* What are plans for getting missing fields (status, coverage), constrain score....?  These seem like critical fields...

Great work - thank you!

Selina

**Comment by wrightmw** [comment]
@selinad @jimmyzhen @kgliu0101 
The curators say that they would like to see the following Constraint Scores:
- pLI - the probability of being loss-of-function intolerant (intolerant of both heterozygous and homozygous LOF variants)
- pRec - the probability of being intolerant of homozygous, but not heterozygous LOF variants
- pNull - the probability of being tolerant of both heterozygous and homozygous LOF variants

These data are only available via a file downloaded directly from ExAC: ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1/functional_gene_constraint/fordist_cleaned_exac_r03_march16_z_pli_rec_null_data.txt

Note: pLI, pRec and pNull scores are gene-specific and so the same scores will be associated with all the variants found in each gene

**Comment by kgliu0101** [comment]
@wrightmw Are these 3 scores required for the first version of VCI?

**Comment by selinad** [comment]
They do need the constraint scores in order to evaluate, so I would say yes....

**Comment by kgliu0101** [comment]
Are they a part of  population data?

**Comment by selinad** [comment]
yes, it is point 1. under the ExAC info, but we have further information that they would like to capture all 3 values.

**Comment by jimmyzhen** [comment]
@wrightmw, @selinad,

How often does the ExAC file (ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1/functional_gene_constraint/fordist_cleaned_exac_r03_march16_z_pli_rec_null_data.txt) on the FTP site get updated? Thanks.

**Comment by wrightmw** [comment]
ExAC do not have a regular release cycle. They make updates as and when they release new data. Usually several months apart. ExAC only started adding Constraint Scores to their site earlier this year (March 2016)... this file has not been updated since then. Steven Harrison told us that ExAC are planning to add gene region constraint scores soon and so this Constraint Scores file will most likely be updated when that happens. You could ask them in their GitHub when/if they plan to update this file:

https://github.com/konradjk/exac_browser/issues

**Comment by wrightmw** [comment]
@jimmyzhen When testing @mrmin123 's highest MAF functionality, I came across an error one of the examples I tested.  For ClinVar VariationID:9760, the output shows the AA Allele Count (A: 10) from ESP, but in 1000G this is missing for the 'ESP6500: African American' data:
![screen shot 2016-07-05 at 4 28 57 pm](https://cloud.githubusercontent.com/assets/15131169/16603124/98b2b8a8-42ce-11e6-80a7-73506e429e49.png)

![screen shot 2016-07-05 at 4 31 03 pm](https://cloud.githubusercontent.com/assets/15131169/16603127/9cf32e0c-42ce-11e6-8120-c635a536ef63.png)

**Comment by wrightmw** [comment]
@jimmyzhen When testing @mrmin123 's highest MAF functionality, I came across an error one of the examples I tested.  For ClinVar VariationID:9760, the output shows the EA Allele Count (A: 10) from ESP, but in 1000G this is missing for the 'ESP6500: European American' data:
![screen shot 2016-07-05 at 4 28 57 pm](https://cloud.githubusercontent.com/assets/15131169/16603232/584ffdb0-42cf-11e6-8532-1d426f0a9217.png)
![screen shot 2016-07-05 at 4 31 03 pm](https://cloud.githubusercontent.com/assets/15131169/16603234/5a0ff326-42cf-11e6-9d82-ef451547e5c6.png)

**Comment by mrmin123** [comment]
@wrightmw I'll work on the above issue as it's relevant to my code.

**Comment by jimmyzhen** [comment]
Hi @wrightmw,

The following is the data returned from the API call:
http://rest.ensembl.org/variation/human/rs104894955?content-type=application/json;pops=1;population_genotypes=1

The data does not appear to be complete.

**Comment by mrmin123** [comment]
@jimmyzhen @wrightmw the data is there:
```
5:Object
   allele:"A"
   allele_count:"10"
   frequency:"0.00148633"
   population:"ESP6500:European_American"
6:Object
   allele:"G"
   allele_count:"6718"
   frequency:"0.998514"
   population:"ESP6500:European_American"
```

but the `minor_allele` field of the object is null:

```
minor_allele:null
```

This `minor_allele` field is used to ascertain which allele to display, but it's missing. I'll have to come up with another way to determine the minor allele if it's blank...

**Comment by mrmin123** [comment]
Sorry, I guess @jimmyzhen is technically correct in that the data is incomplete since the `minor_allele` field is empty. That said, my proposed fix is to take the `allele` information from the `population` subobject if the `alt` allele field is empty after the initial parse, if the `allele` value does not equal the `ref` allele. Going to test this with some extra ClinVar IDs, but speak up if you know that this method won't work right off the bat.

Screenshot showing current proposed fix:
![image](https://cloud.githubusercontent.com/assets/4326866/16603598/19b38c04-42d2-11e6-817c-3bb57f829f26.png)

**Comment by wrightmw** [comment]
@mrmin123 The proposed fix looks good to me.

**Comment by wrightmw** [comment]
Still looks good to me

**Comment by selinad** [comment]
Works nicely.  That was a super catch, @wrightmw .  Thanks for fixing @mrmin123 , @jimmyzhen

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
