### ISSUE TITLE
VCI Interpretation form component (re-usable)

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#690]
Creation of a re-usable UI component that could be used on any tab in the VCI that would hold the forms associated with interpretation.

Component requirements:
--Should be able to be imported into any VCI tab
--Holds form data
--Saves (in a configurable way) the data associated with that part of the interpretation.
--Displays only when in interpretation mode

**Comment by mrmin123** [comment]
Implemented (branch 690_mc_interp_form):

* (Temporary) Fake data to mimic results from external sources
* (Temporary) Button to change fake data to mimic updated results from external sources
* Modify `CurationInterpretationForm` so it can be used anywhere, not just the population tab
  * `CurationInterpretationForm` is now a wrapper for the specific criteria-specific forms
  * Criteria-specific form, form section title, variant UUID, (external) data, and function to update the form on update of external data (optional) can be passed to `CurationInterpretationForm` class
  * `CurationInterpretationForm` itself handles the display of all these items, updating of its own `state` upon updated `props`, rendering and modification of the `Save` button, and actually saving the evaluation  to the db
* The criteria-specific form code, along with the function for updating the form on update of external data, are implemented in the parent tab page (`basic_info.js`, `population.js`, etc)

Screenshot showing current functionality:
![image](https://cloud.githubusercontent.com/assets/4326866/15792869/e4670ec8-2994-11e6-857b-10fd3c12ea36.png)

**Comment by mrmin123** [comment]
Implemented as of time of writing:

* Create/edit evaluation object on save
* Edit interpretation object on save, if necessarily
* 'Save' button's `submitBusy` works properly
* Forms load previously saved data, if it exists

**Comment by mrmin123** [comment]
Update:

* Form values do not flicker back to original value on save (props issue, along with controlling when to call the form update function)
* Identified potential workaround for tabs reseting: see #704

**Comment by mrmin123** [comment]
Some updated parameters after speaking with @selinad:

* Multiple evaluations (criteria code) will need to be tied to single Save buttons
* A tab can have multiple data sets (external or otherwise) that must be saved independently of each other, or perhaps grouped, depending on criteria code/evaluation sets (see above item)
  * When multiple evaluations are tied to a single Save button, they will all draw on the same data set, which will be independent of other criteria codes and their data sets on the same tab

**Comment by mrmin123** [comment]
I don't think I'm going to work on this any further today but outlining a general game plan for the next week..:

* Figure out a way for `submitForm` to distinguish and create multiple evaluation objects dynamically; more than one evaluations can be tied to a single Save button, and they must all have their own evaluation objects
* The basic structure of `submitForm`'s submit action can remain but a few additional things need to happen to make this work with the above changes in function:
  * Find multiple `existingEvaluationUuid`s, not just one
  * Create/update multiple evaluation objects, not just one (utilize `Promise.all` - maybe expand `rest.js` while I'm at it)
  * Update evaluation object with multiple evaluation UUIDs, not just one
* Long-standing item: submit action also needs create the 'snapshot' object as need be, and update the evaluation object as needed

**Comment by mrmin123** [comment]
@selinad @wrightmw Demo instance: http://690-mc-interp-form-b1215a3-minchoi.instance.clinicalgenome.org/

It's not perfect, but it's at a point where I'd like to merge in the code.

Caveats:

* None of these forms are real
* External data is being displayed, but not saved (additional code needed)
* Some form updating/button handling logic is not implemented, since we don't really know how they should work

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
