### ISSUE TITLE
Edit schema computational to specify data properties

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#710]
First version computational data fields have been specified in Computational-tab_PRELIMINARY.pptx in https://app.asana.com/0/113496453225967/113496453225969. Following that, it's necessary to create relevant data properties in the schema file, to add functions for relationship control and generated test file with data specified.

**Comment by wrightmw** [comment]
This tab links to the computatonal tab UI ticket #718

**Comment by wrightmw** [comment]
@kgliu0101 
Thanks for showing me your schema for the computational data. 
This is a minor point, and I'm not sure whether it really matters (since I assume what you have written will never be public?), however the algorithms are not written correctly.
- Phylop should be PhyloP
- sift should be SIFT  (you do have LRT in caps, so having SIFT as 'sift' seems inconsistent)
- MaxEnScan should be MaxEntScan

**Comment by kilodalton** [comment]
@wrightmw Thanks for catching these items. For maximum clarity we want to represent the data as correctly as possible. Both internally and because our code is open source and because our API will expose data to other groups later

@kgliu0101 Please make the changes @wrightmw has asked for

**Comment by kgliu0101** [comment]
@wrightmw I will follow your new requirements to re-write the schema file. Will show you once I have a draft.

**Comment by wrightmw** [comment]
@jimmyzhen  Can check this to see if it can be closed?
