### ISSUE TITLE
Calculate CI information on Population tab (within an Interpretation)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#737]
When a curator has started an interpretation, the ability to add a desired CI value and to calculate lower and upper CI values will appear on the Population tab ( #683)  

The same information will appear as in #736, but with the additional ability to select a desired CI and have lower and upper CI values returned.

### Highest Minor Allele Frequency:
Population: (e.g. African)
Number Variant Alleles: (e.g. 12)
Total Number Alleles Tested: (e.g. 3450)
Source: (e.g. ExAC)
Allele Frequency: (e.g. .0210)

Select Desired CI: [allow to enter numerical value]
CI - lower: [return this value]
CI - upper: [return this value]

After Desired CI entered, could this trigger calculation of lower and upper CI values?  The spreadsheet for this is in Asana (Confidence_interval_calculator_SH.xlsx) - you will need to plug in the number of events (Number Variant Alleles) and the sample size (Total Number Alleles Tested) and then you will see the CI lower and upper values appear (as a range).

Use the "a proportion or odds" tab in the excel spreadsheet (the others are for means).

**Comment by mrmin123** [comment]
@selinad reminder that I need you to ping (insert person's name here) for clarification on the CI calculation. Thanks!

**Comment by selinad** [comment]
Right.  Thank you @mrmin123 and sorry about that - writing Steven now!

**Comment by selinad** [comment]
@mrmin123  - Here's the answer: Use “The estimated population proportion is” only.  Thanks for your patience!

**Comment by mrmin123** [comment]
OK, thanks.

Some information extracted from spreadsheet so I don't have to stare at pink-purple:

```
xp: enter number of events in sample
np: enter sample size/number of subjects
Clp: required confidence interval (default: 95)
Result:

estimated population proportion: =IF(OR(ISBLANK(xp),ISBLANK(np)),"",pp)
CI low: = IF(OR(ISBLANK(xp),ISBLANK(np),ISBLANK(CIp)),"",(2*np*pp + zp^2 - zp * SQRT(zp^2 + 4*np*pp*qp)) / (2*(np + zp^2)))
CL high: =IF(OR(ISBLANK(xp),ISBLANK(np),ISBLANK(CIp)),"",(2*np*pp + zp^2 + zp * SQRT(zp^2 + 4*np*pp*qp)) / (2*(np + zp^2)))
```

**Comment by mrmin123** [comment]
NORMSINV implementation in JS:
http://stackoverflow.com/a/8843728

**Comment by mrmin123** [comment]
```javascript
// user inputs: xp, np, CIp
zp = -NormSInv((1 - CIp / 100) / 2); // use above function
pp = xp / np;
qp = 1 - pp;
CI_low = 2 * np * pp + (zp * zp) - zp * Math.sqrt((zp * zp) + (4 * np * pp * qp)) / (2 * (np + (zp * zp)));
CI_high = 2 * np * pp + (zp * zp) + zp * Math.sqrt((zp * zp) + (4 * np * pp * qp)) / (2 * np + (zp * zp)));
```

**Comment by mrmin123** [comment]
![image](https://cloud.githubusercontent.com/assets/4326866/16751326/60fdb886-478d-11e6-816f-e2d60dba3536.png)

**Comment by mrmin123** [comment]
Behavior:

* CI fields only show up when interpretation is added
* CI lower and upper values update when desired CI is changed
* Clearing the the desired CI field or putting in bad characters will default the value to 95 on clicking away
* Desired CI values are saved on evaluation form saving, and is pre-filled with saved value on re-loading the interpretation

**Comment by mrmin123** [comment]
@selinad @wrightmw 
instance up at http://737-mc-calculate-ci-2374fe1-minchoi.instance.clinicalgenome.org/

Also contains fixes for #788

**Comment by selinad** [comment]
Great @mrmin123 !  I will test tonight after dinner, asap.

**Comment by selinad** [comment]
Wow @mrmin123 - you've done a great job of implementing this!

I am trying to see if the calculation is working correctly.  Here's Highest MAF:
<img width="692" alt="screen shot 2016-07-11 at 9 06 00 pm" src="https://cloud.githubusercontent.com/assets/11320314/16754844/c39bf390-47ab-11e6-8cdd-63356c37a44c.png">


Here's what I get in the excel spreadsheet:
<img width="946" alt="screen shot 2016-07-11 at 9 07 49 pm" src="https://cloud.githubusercontent.com/assets/11320314/16754858/ded3bf30-47ab-11e6-846f-0a51bb624902.png">

maybe I'm confused but the value calculated in the interface is different from the spreadsheet - let me know if I did something wrong.

**Comment by selinad** [comment]
A couple of other things:
- Could the Highest MAF section go above the evaluation?  (sorry I didn't catch this earlier).
- This could be for a different ticket, but are we putting 1000G as the source for ESP data that comes from it?  Maybe so....I only became a bit confused as it made me want to look at the 1000G table and that was empty...we could put "ESP (from 1000G)" (or something like that).  ESP is the provider, it's just displayed on the 1000G site.

p.s. I'll test a few more CI's (different alleles)

**Comment by mrmin123** [comment]
@selinad: calculations are correct. The Excel is rounding off at 4 digits, while the webpage is going to 5, is the reason for the discrepancy. If you increase the number of digits in Excel you'll find the same value.

* Highest MAF section can go above evaluation.
* Right now we're saying that 1000G's ESP data comes from 1000G... much to @wrightmw 's chagrin. I can implement 'ESP (from 1000G)' for the ESP data from 1000G.... or should I just boot it to ESP? Since it's technically ESP data? The only reason why 1000G is showing up is either 1. if the frequencies are the same, because 1000G is calculated first, it takes precedence over ESP, or 2. because of the way rounding is handled, 1000G's ESP might be seen as being larger than our calculated values for ESP... except that shouldn't happen much either now because of the fact we're rounding everything ourselves. Maybe I should just make ESP's MAF take precedence over 1000G's?

**Comment by mrmin123** [comment]
@selinad 
MAF above evaluation:
![image](https://cloud.githubusercontent.com/assets/4326866/16756034/12dfde98-47b7-11e6-8ae6-238d575183cf.png)

Also in above, MAF displays ESP when ESP and ESP from 1000G matches. Screencap of data tables further down the page:
![image](https://cloud.githubusercontent.com/assets/4326866/16756051/3991e018-47b7-11e6-88dc-e83fbe77c235.png)

**Comment by selinad** [comment]
Ah - makes sense - thanks, @mrmin123!  

If you could implement "ESP (from 1000 Genomes)" or "(provided by 1000 Genomes) for the ESP data from 1000G, that would be great (unless @wrightmw has better text).  

Shouldn't population NOT have the ESP on it - ie. just the population w/o the source?:
Population: European American
Source: ESP (provided by 1000 Genomes)

I think we should keep the order the same and use 1000G first, at least unless they tell us otherwise as that's how it was specified (I think).

**Comment by selinad** [comment]
Thanks re Highest MAF section going above evaluations - I think that will be more intuitive.

**Comment by selinad** [comment]
Wow - that was fast - I was thanking you work agreeing to put it first and now I see you have done it already - much better, thank you!

@wrightmw do you have opinion about using ESP from ESP when there is no 1000 Genomes data? Actually, maybe it makes sense any time ESP is the highest....

**Comment by mrmin123** [comment]
@selinad @wrightmw does it ever happen that 1000G would have ESP data, but ESP themselves would not have it?

I can still implement it so that if 1000G's ESP data is the highest it says 'ESP (provided by 1000 Genomes)', but if the above does not occur, this would only act as a fallback in case that the resource we get ESP data from is down, while the resource we get 1000G data is up...

**Comment by mrmin123** [comment]
#### Example 1 - ESP and ESP from 1000G tie; highest MAF section shows 'ESP' as source:
![image](https://cloud.githubusercontent.com/assets/4326866/16756612/2565d80c-47bb-11e6-8ff8-ed54527f3ffb.png)
![image](https://cloud.githubusercontent.com/assets/4326866/16756619/2f33ed88-47bb-11e6-8170-31448b18d6c3.png)

#### Example 2 - same variant, but I deliberately broke it so that we don't get ESP data:
![image](https://cloud.githubusercontent.com/assets/4326866/16756678/a57aa4dc-47bb-11e6-9818-2dc87056fe99.png)
![image](https://cloud.githubusercontent.com/assets/4326866/16756692/bd5aad40-47bb-11e6-80a8-553a1fd9eb53.png)

#### Example 3 - say 1000 Genome if it's actually 1000 Genome:
![image](https://cloud.githubusercontent.com/assets/4326866/16756719/e2eb896c-47bb-11e6-9b20-40e475dd3310.png)

**Comment by wrightmw** [comment]
@selinad @mrmin123 

- In answer to your question, since 1000G are just importing ESP data there should be no instance where 1000G would have ESP data, but ESP themselves would not have it.

- If ESP and 1000G tie on ESP data then I feel that we should definitely show ESP since they are the originating source

- It's ok to still implement it so that if 1000G's ESP data is the highest it says 'ESP (provided by 1000 Genomes)'...but if this occurs it will only be due to rounding up on decimal places

**Comment by selinad** [comment]
Hi @wrightmw thanks so much for the very clear answers. I agree with how you broke it down.

Additionally, it looks like 1000G and ESP are pulled in via the same API, so the same allele representation is used to query them... meaning 1000G data for ESP should exist when ESP itself has it and v.v., I think...

**Comment by mrmin123** [comment]
@selinad @wrightmw I think the above implementation has it the way you guys want.. does that sound right?

**Comment by wrightmw** [comment]
@mrmin123 Yes, your implementation looks good to me

**Comment by selinad** [comment]
This looks great, @mrmin123 - thanks!

One question for @wrightmw : should we say ESP6500 on the population or just "European American?"

**Comment by mrmin123** [comment]
@selinad @wrightmw On that note, please specify if you want the label for the ESP values in the 1000 Genomes table to change, as well... right now it's just mirroring the value shown in the table, but this can be changed.

**Comment by selinad** [comment]
Are you talking about the ESP6500?  I would vote for removing it as it doesn't seem consistent with how we handle other Populations, but I will wait for @wrightmw to weigh in...

**Comment by mrmin123** [comment]
Yes, was talking about the ESP6500 in the label. That said, it does seem nice to have it in the 1000 Genomes table since it kind of differentiates the sources and their naming nomenclature (AFR, AMR, EAS, etc vs African American, European American...).

**Comment by selinad** [comment]
yes, absolutely agree 👍

**Comment by wrightmw** [comment]
I agree with the above.

**Comment by selinad** [comment]
This works soooo nicely - they will be thrilled.  Thx for working out all the math :P

**Comment by wrightmw** [comment]
Pop-tab fantastic!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
