### ISSUE TITLE
search page

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#74]
As of #47, min has the elasticsearch back on (pending tests).  However the url /search/ fails because it's customized to ENCODE specific data for faceted search.    This is all in search.js

I am not assigning 0.5 or 1.0 to this because I am not 100% that we need it for any outstanding interfaces, and it's probably a fair amount of work.  At a minimum /search/ with no args should be disabled.

**Comment by mrmin123** [comment]
Please note that changing the doc_types variable in search.py also made the page functional despite search.js still referencing the encoded data. Both locations should probably be updated to keep things consistent.

**Comment by kilodalton** [comment]
This issue, as described, was addressed by @mrmin123 in #47 (re-enable elasticsearch) in PR #75. Closing issue.

From @mrmin123:
"Not directly related but tangential so I went and attempted to address #60 and #74 as well (the fix for these are related). Replaced ENCODE-related objects with ClinGen ones. List of objects that show up and their naming needs review, however."

@forresttanaka If you think this issue should be re-opened to address the existing search page display please re-open it.
