### ISSUE TITLE
Can't load interpretations/evaluations pages

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#744]
Upon testing PR 735

http://localhost:6543/evaluations/

`collection.js:195Uncaught TypeError: Cannot read property '@type' of undefined`

http://localhost:6543/interpretations/

`collection.js:195Uncaught TypeError: Cannot read property '@type' of undefined`

**Comment by kgliu0101** [comment]
This bug is fixed by replacing columns property "variant.represent" with "variant.variant_identifier" in schema files `interpretation.json`, `evaluation.json`, `population.json` and `computational.json` in dir `src/clincoded/schemas/`. Test instance is at: [https://744-kl-load-interpretation-3dc26c2-kangliu.demo.clinicalgenome.org](https://744-kl-load-interpretation-3dc26c2-kangliu.demo.clinicalgenome.org)

**Comment by kgliu0101** [comment]
In addition, a couple of errors are found in class Interpretation in file `src/clincoded/types/__init__.py`.
1. Type of calculated properties "Evaluations" and "Provisionals" should be "number".
2. Calculated properties "Transcripts" and "Proteins" are no longer necessary and should be removed.

Related codes will be edited in this ticket.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
