### ISSUE TITLE
Add modal to associate & edit Orphanet ID with an Interpretation

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#770]
Add modal for adding Orphanet ID to an Interpretation once "Associate Disease" button hit.

Add "Edit Associated Disease" button to interpretation if disease has already been associated (let me know if this should go in different ticket)

"Associate Disease" version of modal will allow curator to enter ORPHA ID (like in creating GDM) and validate ORPHA ID.  Will also allow user to change entered ORPHA ID by editing in the box, even to point there is no ID left.  

"Edit Associated Disease" version of modal will be same except that it will show warning that removing disease has implications in this version of interface.

**Comment by selinad** [comment]
HI @jimmyzhen 
When I click Associate with disease, modal pops up. If I enter ORPHA84 and click OK, nothing seems to happen.  If I then hit Cancel and return to record, the association has been made - seems like modal doesn't know to close down.  Edit Disease button appears, tho.

**Comment by selinad** [comment]
Also, when I hit Edit Disease, no existing ORPHA ID shows...and changing it in the window gives same problem with OK doing nothing.  However, when I cancel, the disease does not change (is not edited from original).

**Comment by selinad** [comment]
twice now, when I have hit either "Associate ..." or "Edit disease," this has happened (i.e. lose much of the static bar, looks like I am out of Interpretation...):
![screen shot 2016-07-11 at 12 05 12 pm](https://cloud.githubusercontent.com/assets/11320314/16743129/cf103700-475f-11e6-8c7b-7befa7667c6c.png)

**Comment by mrmin123** [comment]
@jimmyzhen @selinad while visiting the issue where opening the modal would clear the url bar, I also fixed the issue of the blank VCI post-disease association. I also made it so that adding or editing the disease of an interpretation properly updates the subtitle in the title bar by revising the `updateInterpretationObj()` method in `index` page and implementing a props update chain in the child pages.

Screencaps:
![image](https://cloud.githubusercontent.com/assets/4326866/16759040/d88e3740-47c9-11e6-959d-0ba44fd1448a.png)

![image](https://cloud.githubusercontent.com/assets/4326866/16759056/ed7fa878-47c9-11e6-9e54-b45925d31998.png)
*note: the 'Associate Disease' button is not renamed to 'Edit Disease'... should be easy to change now I think, with the props update chain in place.*

![image](https://cloud.githubusercontent.com/assets/4326866/16759089/1b31f5aa-47ca-11e6-84d0-f00fbb8d62f0.png)
* note: the ORPHA## below the title in the grey bar updates in real time, but the one under 'My Variants' do not. We need to revisit this, probably in a separate ticket, as I believe it requires updating either the `updateInterpretationObj()` method or adding a separate method to update and pass down the updated `variant` object.

**Comment by selinad** [comment]
Thanks @mrmin123 !  

Sorry if I missed it - is there a reason it displays the OPRHA ID rather than the disease term in the gray bar and in the history?

**Comment by mrmin123** [comment]
@selinad That's just the way @jimmyzhen had it wired up at the moment.

**Comment by jimmyzhen** [comment]
@selinad, @mrmin123, I thought I configured the subtitle to use the disease term currently. But I can look into it and find out what the culprit is.

**Comment by selinad** [comment]
Thanks @mrmin123 and @jimmyzhen !  Jimmy's original instance showed the terms....I remember as I tried Fanconi Anemia and Achondroplasia (minus any misspellings!).

**Comment by jimmyzhen** [comment]
@selinad @wrightmw @kilodalton The new instance is up for this ticket:
https://759-jz-761-770-combo-b8f6377-jzhen.demo.clinicalgenome.org/

**Comment by wrightmw** [comment]
@jimmyzhen Great! I cannot replicate the errors, they appear fixed to me.  I have associated diseases with an interpretations and successfully changed the disease several times.

**Comment by selinad** [comment]
Hi @jimmyzhen I ended up on CV VariationID 11111 - when I was in evidence hub (https://759-jz-761-770-combo-b8f6377-jzhen.demo.clinicalgenome.org/variant-central/?variant=d5e809fa-707f-46bc-8598-0611cb562cd8) and clicked on Start New Interpretation I received a Not Found error in this instance...

![screen shot 2016-07-13 at 10 49 07 pm](https://cloud.githubusercontent.com/assets/11320314/16829298/1143a66e-494c-11e6-84d2-c56a726e7079.png)

This is kind of an oddball variant, but for the record (not sure if associated with this instance)

**Comment by selinad** [comment]
HI @jimmyzhen I am getting an error when I go back to a variant and get the "Continue Interpretation" button - when I click on it I get an error (404):

https://759-jz-761-770-combo-b8f6377-jzhen.demo.clinicalgenome.org/variant-central/?variant=cd18b157-ad65-4d03-a331-86a098807184

**Comment by jimmyzhen** [comment]
@selinad The wrapping of the criteria bar is new to me as well. I noticed it after I merged the latest `dev` into my branch. The seemingly larger font-size (than I noticed before) in the codes and the yellow vertical bar on the right are potentially the culprits in the behavior. I can address it in a separate ticket tomorrow.

**Comment by selinad** [comment]
thx @jimmyzhen :)

**Comment by jimmyzhen** [comment]
@selinad @wrightmw Regarding the oddball variants (e.g. https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=11111), they can certainly cause the page rendering to fail since we currently don't have rigorous checking on every node's presence in the XML response coming back from ClinVar. And we are dependent on various bits and pieces of data in the Eutils response to do various things. We may not have enough time to improve it in this release, but we will address it in the days following the test release.

**Comment by wrightmw** [comment]
@selinad @jimmyzhen http://www.ncbi.nlm.nih.gov/clinvar/variation/11111/  This variant has no genomic location in the entry. It is just registered as a 4bp deletion in TAZ at Xq28, so there is no information that could be downloaded for this variant. If there are no genomic locations, i.e. no NC HGVS term like in this example then we could just provide a note saying there is no known genomic location for the variant provided by ClinVar.

**Comment by wrightmw** [comment]
Obviously not for the test release.

**Comment by selinad** [comment]
Sounds good, @wrightmw

**Comment by jimmyzhen** [comment]
In regards to the other reporting by Selina (e.g. https://github.com/ClinGen/clincoded/issues/770#issuecomment-232564266), the culprit is the molecular consequence in the ClinVar variant data not mapped to the primary transcript:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&rettype=variation&id=5557

While these variant data problems are not directly related to the changes in ticket, they are causing page rendering failures and we shall have a separate ticket to implement rigorous data validation when parsing the API responses.

**Comment by jimmyzhen** [comment]
@wrightmw In the ClinVar ID "11111" case, would you think it's better to alert the user about the "concerns" of the variant on the selection page even before the user gets to the evidence hub and finds out the spotty data display? Currently the 3 tabs are heavily dependent on data from external API calls...

**Comment by wrightmw** [comment]
@jimmyzhen Yes, you are probably right. If the Curator enters a VariationID for a ClinVar entry that has no genomic NCs then we tell the curator that the variant they have entered has no genomic data and so will return no data.

**Comment by selinad** [comment]
I like that, @jimmyzhen - we can do that for ClinVar and CA IDs when info is returned on the modal (I think we only put the warning on the top of the evidence page right now, not on the return within the modal).  Should I make separate ticket for R7alpha2?

**Comment by jimmyzhen** [comment]
@selinad A separate ticket for this in R7alpha2 sounds good. Thank you.

**Comment by selinad** [comment]
works well - did not experience aforementioned errors!

**Comment by wrightmw** [comment]
Looks good!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
