### ISSUE TITLE
Add Bustamante data (REVEL, CFTR, MYH7) to Computational/Predictive tab

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#772]
Once API available and info is specified, add REVEL data

**Comment by jimmyzhen** [comment]
This ticket will also address https://github.com/ClinGen/clincoded/issues/796.

**Comment by jimmyzhen** [comment]
The integration of Bustamante data has been implemented and is working as expected:
![image](https://cloud.githubusercontent.com/assets/6956310/16858687/831ab278-49dd-11e6-98d8-0665dc45aaf5.png)

The screen shot above shows data returned from: https://predictvar.bustamante-lab.net/variant/position/3/71019907/A/

Furthermore, since the API response has no CFTR data, the CFTR table row is not rendered (in addressing #796).

**Comment by selinad** [comment]
this is FANTASTIC!!!!  Thank you, @jimmyzhen, for working hard on this and coordinating with Koni. 👍  :-)

**Comment by wrightmw** [comment]
Oh my! I'm so pleased we managed to show REVEL.

**Comment by wrightmw** [comment]
👍

**Comment by selinad** [comment]
@wrightmw and @kilodalton - thank you both for your hard work on this as well!  Super!

**Comment by wrightmw** [comment]
Looks good

**Comment by wrightmw** [comment]
MYH7 data is yet to be included and so now has separate ticket #829

**Comment by selinad** [comment]
Super job!  Very nice to be able to have this show on the screen this AM!

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
