### ISSUE TITLE
Variant Genomic Context Links in static header

### ISSUE THREAD

**Issue by kilodalton** [ClinGen/clincoded#780]
Fix linkouts... use code from footer

**Comment by kgliu0101** [comment]
@selinad and @wrightmw 

Genomic context links in header are set as:
![screen shot 2016-07-12 at 11 47 56 am](https://cloud.githubusercontent.com/assets/9206696/16791436/d7664178-4873-11e6-923a-11ad448b8755.png)

Only ClinVar variants have UCSC links and Variation Viewer links. Any variant with GRCh38 can has Ensembl link.

Test instance is at [https://780-kl-genomiccontext-links-58c3786-kangliu.demo.clinicalgenome.org](https://780-kl-genomiccontext-links-58c3786-kangliu.demo.clinicalgenome.org)

**Comment by wrightmw** [comment]
@kgliu0101 That instance link does not work for me:
![screen shot 2016-07-12 at 9 17 27 pm](https://cloud.githubusercontent.com/assets/15131169/16791674/2c216ede-4876-11e6-8612-383a5799a278.png)

**Comment by wrightmw** [comment]
@kgliu0101 Why do only ClinVar variants have UCSC links and Variation Viewer links?

**Comment by selinad** [comment]
Thx @kgliu0101 - would you mind spelling out how you made the links?  (i.e. what we should expect) Here's an example of a ClinVar variant with only an Ensembl link although it does have a GRCh37 NC_ in CLinVar:

<img width="846" alt="screen shot 2016-07-12 at 9 40 16 pm" src="https://cloud.githubusercontent.com/assets/11320314/16792047/836b57ba-4879-11e6-8cfe-13693979fd31.png">

Are you linking to the gene page for the browser?

Thanks!
-Selina

**Comment by kilodalton** [comment]
@selinad @wrightmw Jimmy did the original logic for the links and possibly can chime in here. @jimmyzhen 

Kang is supposed to be fixing the links at the top based on that logic.

**Comment by wrightmw** [comment]
@kgliu0101 You are linking to the Ensembl Gene page (e.g. http://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000012048) but there are other ways to link, e.g. to location (http://www.ensembl.org/Homo_sapiens/Location/View?db=core;r=17:43099781-43099791) or using rsid (http://www.ensembl.org/Homo_sapiens/Variation/Explore?r=17:43099286-43100286;v=rs397509273;vdb=variation;vf=59391062)

**Comment by selinad** [comment]
yeah - I think we didn't clearly define this anywhere.  I was thinking the links would go to genomic location as well.

**Comment by kgliu0101** [comment]
The instance above is terminated. I am going to create a new one. Will let you know soon.

**Comment by kgliu0101** [comment]
@selinad and @wrightmw Please test the instance [https://780-kl-genomiccontext-links-1df8e78-kangliu.demo.clinicalgenome.org](https://780-kl-genomiccontext-links-1df8e78-kangliu.demo.clinicalgenome.org) for Genomic context links.

The Ensembl link is changed as Matt suggested above (rsid). Since it uses dbSNP id, it should work for both GRCh38 and GRCh37 if we can get relevant dbSNP id from either ClinVar or CAR.

**Comment by selinad** [comment]
Thanks, @kgliu0101 !

It would be great to understand what you are doing for each link.  I realize we have not defined this well for you.

For the UCSC link, it looks like you are linking to 1 bp, a very zoomed in version.  I'd like to propose that we link to a 60 bp section with the affected base pair in the middle - this can then be used on the repetitive region.  @wrightmw do you agree?  Since it is about the variant and not the gene, I was thinking it would be good to see the general region and curators can always zoom out.

For the Variation Viewer, are you linking via transcript?  Or maybe gene?  If so, it would be better to have it search a similar section as the UCSC browser...again, I will wait for @wrightmw 's opinion on this.

Linking to the rsID for Ensembl seems like a good idea - I land on the "variant" tab instead of the "location" tab - is there a way to land on the latter?

These links and the links at the bottom of the Basic Info page will be the same, correct?  One thing I just thought of on both these links and those at bottom on Basic Info page - can there be a pipe {|} between GRCh37 and GRCh38 links rather than a "-"?  I think a pipe will better convey the idea they are separate links.

So far everything I've tested is bringing in info, which is great!  Will test some more.

**Comment by kgliu0101** [comment]
@selinad Links to UCSC and Variation Viewer are same as the ones at bottom of basic info tab. Link to Ensembl is different. It was changed to use rs id yesterday. Once you and Matt have a final decision, I will edit codes for both links in header and links in basic info tab.

**Comment by selinad** [comment]
@kgliu0101 thx.  @wrightmw and I will specify it better for you.

**Comment by selinad** [comment]
Here's what @wrightmw and I decided:

There are 3 places where we link to browsers:
- in static bar (this ticket)
- at bottom of Basic Info page
- on Computational tab for the "Molecular Consequence: In-frame indel" (same as "Repetitive Regions, the older name)

For all 3 of these, we would like the links to go to the region +/- 30 nt of the variant location, so it would be a region of 60 nt.  @wrightmw is going to come by and talk to @kgliu0101 about how to do this.  Note: if we can't do this easily for Ensembl, we will stick with rsIDs as currently exists.

After that, we could put it in other locations ( @kilodalton please let me know how you would like me to handle specifying that on github - i.e. new tickets, add to existing, etc.).

**Comment by kgliu0101** [comment]
@selinad and @wrightmw A new instance is created at [https://780-kl-genomiccontext-links-90799e1-kangliu.demo.clinicalgenome.org](https://780-kl-genomiccontext-links-90799e1-kangliu.demo.clinicalgenome.org) for testing genomic context links in static header. Once passed your test, they can be copied to basic info and computational tabs.

**Comment by kilodalton** [comment]
@selinad Let's just do the Header links here... please add changes for other places in a separate ticket. Can that happen in R7alpha2?

**Comment by wrightmw** [comment]
@kgliu0101 @kilodalton These links look good to me.  They can be extended to the footer in the basic info tab and "Molecular Consequence: In-frame indel" in the Predictors tab :-)

**Comment by kgliu0101** [comment]
@selinad, @wrightmw and @kilodalton, I agree that we finish this ticket as is and copy those links to basic info tab and computational tab in a new ticket.

**Comment by kilodalton** [comment]
@wrightmw Yes, I am trying to get as much code as possible in tonight. Additions/changes to other pieces can be made afterward.  If you or @selinad can make a separate ticket that would be great if the header is fine here.

**Comment by selinad** [comment]
HI @kilodalton - I can make another ticket, but I am confused as to whether it would go in for R7alpha1?

**Comment by selinad** [comment]
To confirm - these links already exist at bottom of basic info, but are not correct.

**Comment by kgliu0101** [comment]
If no longer needed, I am going to terminate the test instance above.

**Comment by selinad** [comment]
I am just getting back on after my bday bash ;-) - if @wrightmw thought it was ok, that's good.

**Comment by wrightmw** [comment]
Yes, links all still good

**Comment by selinad** [comment]
Indeed. Good to go.

**Comment by kilodalton** [comment]
Included in last release (R7alpha1). Nice job and thanks for your hard work.
