### ISSUE TITLE
Display curator name with Interpretation on history (under My Interpretations)

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#839]
Display the curator's name under My Interpretations, much like we do for gene curation - and match gene curation styling?

![screen shot 2016-07-18 at 10 53 21 am](https://cloud.githubusercontent.com/assets/11320314/16924800/e0a101a4-4cd5-11e6-9938-e15a6f4913c3.png)

**Comment by mrmin123** [comment]
I'm not sure if the format displayed for the GCI would work here because of the extra information displayed on the GCI. Will discuss w/ @selinad further.

**Comment by mrmin123** [comment]
@selinad @wrightmw 

The Interpretation sections while in Interpretation view looks like this:
![image](https://cloud.githubusercontent.com/assets/4326866/19365241/b429fe40-9146-11e6-9e0a-bf079ad1e173.png)

Once you begin/edit an interpretation it looks like this:
![image](https://cloud.githubusercontent.com/assets/4326866/19365277/e3013670-9146-11e6-87a8-f4e0881d1342.png)

Are the 'Creator' and 'Particpants' lines necessary? They seem a bit redundant since interpretations are per-user...

**Comment by mrmin123** [comment]
After discussion this ticket has been deemed outdated/unnecessary:

* There are talks of re-vising this entire section of the VCI in the future
* A user can only see their own interpretation at the moment
