### ISSUE TITLE
Link to variant in ExAC even when no population data for the variant

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#846]
1. Substitution variant:

Even when there is no variant data, curators would like to be able to link to the page when it is a subtitution - e.g.

<img width="849" alt="screen shot 2016-07-20 at 11 19 02 am" src="https://cloud.githubusercontent.com/assets/11320314/17000002/849a09fe-4e75-11e6-8adf-56ce7356ce43.png">

2. For non-substitution variant (e.g. indel, copy number), do a region search ( @wrightmw did you get specification on this?)

**Comment by wrightmw** [comment]
2. Yes, for a non-substitution variant (e.g. indel, copy number), the we would do a region search in ExAC for -30 to +30 each side of the variant. E.g http://exac.broadinstitute.org/region/12-112884023-112884083 :
![screen shot 2016-07-20 at 1 43 54 pm](https://cloud.githubusercontent.com/assets/15131169/17002417/066755c2-4e80-11e6-9cd3-bc5926c66195.png)

**Comment by selinad** [comment]
thx @wrightmw - perfect. I couldn't read my scribbles :P

**Comment by wrightmw** [comment]
@selinad I'm having trouble reading mine! It's the luxury of having so much feed back from Steven. What a star!

**Comment by jimmyzhen** [comment]
Hi @wrightmw, @selinad,

For a variant as the following:
http://myvariant.info/v1/variant/chr7:g.117120152_117120270del119ins299

Which position should I be using for -30 and +30 in the region search? Thanks.

**Comment by wrightmw** [comment]
@jimmyzhen There is no definitive answer to this since there are any number of complex variant scenarios in the genome.  My temptation in this instance would be to do -30 from the first number up to +30 for the second, e.g. 117120132 to 117120300

**Comment by jimmyzhen** [comment]
@wrightmw, I was actually thinking about the same thing. Just wanted the confirmation. Thanks!

**Comment by jimmyzhen** [comment]
## Example variants for testing

**Substitution variants (with both clinvar and cadd objects):**
http://myvariant.info/v1/variant/chr15:g.67358465C%3ET
http://myvariant.info/v1/variant/chr7:g.107423741C%3ET

**Substitution variant (with only cadd object):**
http://myvariant.info/v1/variant/chr1:g.957828A%3EC

**Non-substitution variants (type "Duplication"):**
http://myvariant.info/v1/variant/chr7:g.117232396dupA
http://myvariant.info/v1/variant/chr7:g.117171091_117171093dupCTA

Non-substitution variants (type "Deletion"):
http://myvariant.info/v1/variant/chr7:g.117188858del
http://myvariant.info/v1/variant/chr7:g.117182115_117182121del

**Non-substitution variants (type "Insertion"):**
http://myvariant.info/v1/variant/chr7:g.117175364_117175365insT

**Non-substitution variants (type "Indel"):**
http://myvariant.info/v1/variant/chr7:g.117120152_117120270del119ins299

**Comment by jimmyzhen** [comment]
Hi @selinad, @wrightmw,

You may review changes in the following instance:
https://846-jz-exac-variant-link-9863e71-jzhen.demo.clinicalgenome.org

**Comment by wrightmw** [comment]
@jimmyzhen @selinad 
Thanks Jimmy... I will look at the example you suggested... I've added in the VariationID/CA_ID to your examples to make testing easier:

## Example variants for testing

**Substitution variants (with both clinvar and cadd objects):**
http://myvariant.info/v1/variant/chr15:g.67358465C%3ET (VariationID: 139214)
http://myvariant.info/v1/variant/chr7:g.107423741C%3ET (VariationID: 55962)

**Substitution variant (with only cadd object):**
http://myvariant.info/v1/variant/chr1:g.957828A%3EC (CA501146)

**Non-substitution variants (type "Duplication"):**
http://myvariant.info/v1/variant/chr7:g.117232396dupA (VariationID: 7185)
http://myvariant.info/v1/variant/chr7:g.117171091_117171093dupCTA (VariationID: 53905)

**Non-substitution variants (type "Deletion"):**
http://myvariant.info/v1/variant/chr7:g.117188858del (VariationID: 53237)
http://myvariant.info/v1/variant/chr7:g.117182115_117182121del (VariationID: 53205)

**Non-substitution variants (type "Insertion"):**
http://myvariant.info/v1/variant/chr7:g.117175364_117175365insT (VariationID: 54032)

**Non-substitution variants (type "Indel"):**
http://myvariant.info/v1/variant/chr7:g.117120152_117120270del119ins299 (VariationID:: 53981)

**Comment by jimmyzhen** [comment]
Brilliant! Thanks, @wrightmw!

**Comment by wrightmw** [comment]
@selinad @jimmyzhen 
Jimmy, your implementation on this is great. The links to ExAC are all good for the test examples, except:

http://myvariant.info/v1/variant/chr1:g.957828A%3EC (CA501146) is not a good testing example because it is only GRCh38 and so does not currently return any ExAC population data

The "indel" example (http://myvariant.info/v1/variant/chr7:g.117120152_117120270del119ins299 (VariationID: 53981)) has revealed a bug on the Basic Info tab where because of the long insertion in the HGVS names all the formatting of the page has been disrupted. Interestingly, noe of the ClinVar data has not been imported for this example (e.g. no ClinVar primary transcript and no RCV000047172)... I will make separate ticket for this:

![screen shot 2016-08-09 at 4 32 52 pm](https://cloud.githubusercontent.com/assets/15131169/17537146/01a6fbb2-5e4f-11e6-9294-159ff4cd0cb2.png)

**Comment by jimmyzhen** [comment]
@wrightmw Aside from your comments above, did the changes in ticket work as expected for the external ExAC linkout?

**Comment by wrightmw** [comment]
@jimmyzhen Yes. Thanks. The ExAC link functionality worked well for the examples, except the CA ID one that could not render a link because it is GRCh38. That's why I created a new ticket for the wrapping issue because it's separate to your task on this ticket, which I think you have completed.

**Comment by jimmyzhen** [comment]
@wrightmw @selinad 

Further changes have been made for this ticket so that clicking on the "Search ExAC" link will take the user to ExAC's homepage when there is no data at all in the myvariant.info response.

To review the changes, try **CA501146** and **CA501097** on the following new instance:
https://846-jz-exac-variant-link-6b8c062-jzhen.demo.clinicalgenome.org

I have also addressed the long HGVS term issues. Try **53981** and **90973** to review the fix. Thanks.

**Comment by wrightmw** [comment]
@jimmyzhen That's great Jimmy. Both examples work well now. Thanks.

**Comment by wrightmw** [comment]
Works well for me :-)

**Comment by selinad** [comment]
Great!

**Comment by kilodalton** [comment]
Included in last release (R7alpha2). Nice job and thanks for your hard work.
