### ISSUE TITLE
Separate table for Other meta-predictors on Predictors tab

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#850]
Right now, meta-predictors are mixed in with non-meta-predictors.  Would like the following tables:
- ClinGen Predictors
- External Meta-Predictors
- External Predictors

( @wrightmw please feel free to change my wording) - are CFTR and MYH7 considered meta-predictors?  If so, can say "ClinGen Predictors" and then "Other" instead of "External" for other tables....  please advise :-)

**Comment by wrightmw** [comment]
We still do not have the specs for the CFTR and/or MYH7 data.  I will continue to pursue these pieces of information.  I would hold off on the implementation of this ticket until we know the full facts surrounding these datasets... I hope to get these data very soon.

@selinad  I purposely avoided using the work 'external' since some of these tools are based on protein-folding/protein structure algorithms... 'internal' or 'external' (e.g unexposed vs exposed binding sites) can have other meaning for protein tools. 'Other' was accepted by the Nilah and Raj as an acceptable term, however I'm sure there are other synonyms that would also be acceptable if you would prefer a different wording?

**Comment by selinad** [comment]
Sounds good @wrightmw - let's see what they say and go from there!

**Comment by wrightmw** [comment]
CFTR is a meta-predictor
