### ISSUE TITLE
menu bar

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#86]
menu bar is all wrong.  For example, should not have Group Curation.

See specs.

**Comment by forresttanaka** [comment]
The menu bar there is just so I can get to things easily. If people could supply their opinions here, as I currently have two menu bars — the blue one with Login and Accounts. Then there’s the big white one. Not sure if we need both, and if not, which one we should have.

**Comment by forresttanaka** [comment]
* Removed the main navigation bar and moved the Dashboard menu to what I call the navUser menu that’s in the blue tabs at the top of the header.
* The ClinGen logo, once part of navMain, is now on its own because navMain doesn’t exist anymore. It for now goes to /dashboard instead of /.
* Updated the look of the header background image slightly.

![screen shot 2015-07-27 at 10 41 13](https://cloud.githubusercontent.com/assets/1181324/8913146/1ca1455e-344c-11e5-9339-239b41a7e9ea.png)

**Comment by forresttanaka** [comment]
Change Dashboard menu to a house icon.

**Comment by forresttanaka** [comment]
![screen shot 2015-07-28 at 11 32 35](https://cloud.githubusercontent.com/assets/1181324/8940222/939d3a60-351d-11e5-8a91-8b6a9d1abe5d.png)

![screen shot 2015-07-28 at 11 40 56](https://cloud.githubusercontent.com/assets/1181324/8940224/97697dca-351d-11e5-8855-99377d7ac059.png)

**Comment by selinad** [comment]
Sweet...

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
