### ISSUE TITLE
Summary and Provisional Assertion for GDM

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#90]
This is a view of the GDM that calculates the current summary and provisional assertions.

Apparently summaries and assertions are PER curator.  Summary is autogenerated.

**Comment by kgliu0101** [comment]
page to create a new provisional.
![newprovisional](https://cloud.githubusercontent.com/assets/9206696/9947230/74e4b2ee-5d4d-11e5-82a9-f64b1a61273a.png)

**Comment by kgliu0101** [comment]
page to edit existing provisional data.
First, have a view of login user's provisional.
![existingprovisional](https://cloud.githubusercontent.com/assets/9206696/9947282/d2c3affa-5d4d-11e5-8f71-e27dc57756d0.png)

then, click button Calculate Again will get new summary below
![calculateagain](https://cloud.githubusercontent.com/assets/9206696/9947353/49b822d0-5d4e-11e5-9c5c-f8f9e51498f7.png)

**Comment by selinad** [comment]
HI @kgliu0101 Thanks so much for this!

Here are a few comments:

**PAGE TO CREATE A NEW PROVISIONAL**
* "Calcaleted" should be spelled "Calculated"
* Our bad, but I believe the Scoring Details should go right under the Calculated CVC (Clinical Validity Classification) and then the boxes to change and explain would go below Scoring Details.
* What is the default for change box for Classifciation? I think we should put it as No Selection and make it a required field ...see next few comments
* **Change Provisional Clinical Validity Classification"** -> **Select Provisional Clinical Validity Classification**
* Make the above field required
* Add Note above the explain reasons box -> **Note: If your selected Clinical Validity Classification is different from the Calculated value, provide a reason to expain why you changed it."
* The "Back to GDM" button should say "Return to Record Curation" as it does throughout interface.  Users will not recognize GDM
* We will need a little more description for Scoring details - see below for example:

**Number of years since first clinical publication**
Score: **2**
Year of First Publication: 1994

**Number of clinical publications with clincial evidence**
Score: **2**
Number of Publcations: x

**Number of probands associated with a pathogenic variant**
Score: **2**
Individual probands not associated with Family: 1
Individual probands associated with Family: 3

**Experimental Data**
Combined Score: **3.5**

[indent these]

 *Expression (0.5 points each)*
Score: **1.0**
Number of pieces of evidence: 2

*Protein Interactions (0.5 points each)*
Score: **0.5**
Number of pieces of evidence: 1

*Protein Interactions (0.5 points each)*
Score: **0.5**
Number of pieces of evidence: 1

*Model Systems (2 points each)*
Score: **2**
Number of pieces of evidence: 1

[end indent]
<hr>
**Total Score:** 9.5

**Comment by selinad** [comment]
**PAGE TO EDIT PROVISIONAL DATA**
 
* For all titles, the "AND" should be lower case: "Summary and Provisional Classification"

* Kang, could this work more like how @forresttanaka implemented editing a variant assessment?   See his newest instance.  Do you need this page, or can you just have the next one you show? (Curation - New Calculation)

* Titles should be as @forresttanaka has done throughtout interface for VIew (View: Summary and Provisional Classification or maybe View/Reclassify Summary and Provisional Classification)

* Once you have figured out above, can you please seek advice from @forresttanaka as to blue bars and label names?  They should be in sync with his styling.

**Comment by selinad** [comment]
I think Recalculate (rather than Calculate again) button should be on GDM page - you can't recalculate from the Summary page.  The curator could Edit their classification, but that is different from recalculating from the evidence.

**Comment by selinad** [comment]
@kgliu0101 I'm not sure I understand the red note - it just changes their classification, not any data underneath (also, I don't think @forresttanaka has any red notes - red is reserved for errors).

**Comment by kgliu0101** [comment]
Add Summary data, link and button in record title panel.

gdm with Summary and Provisional Classification.
![link](https://cloud.githubusercontent.com/assets/9206696/10026333/0e242ed2-6116-11e5-90df-308d54be36f1.png)

gdm with pathogenic data and assessed as Supports, but without Summary.
![link1](https://cloud.githubusercontent.com/assets/9206696/10026369/4259b5e6-6116-11e5-9555-b4abea43ee15.png)

gdm without assessed pathogenic data.
![link2](https://cloud.githubusercontent.com/assets/9206696/10026392/644f8a54-6116-11e5-96f9-2b51473a19ab.png)

**Comment by kgliu0101** [comment]
Display Summary data as one line in record title panel.
![link](https://cloud.githubusercontent.com/assets/9206696/10034059/70c69314-6142-11e5-978b-b6f99aab9064.png)

**Comment by selinad** [comment]
Hi @kgliu0101 - looking good - here is my similar version with some changes in wording
![mockup-header](https://cloud.githubusercontent.com/assets/11320314/10034151/2e323c8c-6143-11e5-9a47-760053be781e.png)

**Comment by kgliu0101** [comment]
matching above?
![link](https://cloud.githubusercontent.com/assets/9206696/10035231/baebd152-614c-11e5-9e24-6f5081b16795.png)

**Comment by selinad** [comment]
Thanks @kgliu0101 Looks good!

* Since there is room, I think it could say [Edit Classification] rather than just [Edit]
* Could the button hug the right side a little less?  Would like to see more gray around it.
* Also, I realize it should say "Current Summary & Provisional Classification" - if there were no Provisional Classifciation, there could be a "None" or "Not yet provided"

There is one more thing you could try, if you like, since there is more room than I thought.

You could put the following in a 2nd column:

Total Score: 17 (Definitive)
Provisional Classification: Strong [Edit Classification]

That way, you would have 3 columns:

1.
Current Summary
Generated: 2015....

2.
Total Score: 17 (Definitive)
Provisional Classification: Strong [Edit Classification]

3.
[Button]

This might highlight the scoring part.

**Comment by kgliu0101** [comment]
3 columns:
<img width="873" alt="link" src="https://cloud.githubusercontent.com/assets/9206696/10037126/8e918ff6-6166-11e5-9a2e-beb9ef82372d.png">

**Comment by kgliu0101** [comment]
Note for new calculation.
![summary](https://cloud.githubusercontent.com/assets/9206696/10199658/9f860bac-6756-11e5-82ac-ca06aed1a3aa.png)

**Comment by selinad** [comment]
Hi @kgliu0101 - thanks so much - it's coming along!

I like the addition of the note since the header still has the Summary/Classification from before the user hit Generate New Summary. 

Slight change to wording - @forresttanaka, do we need a blue box for a note here?:
The calculated values below are based on the set of curated evidence saved prior to selecting "Generate New Summary."  To save these values as the "Current Summary & Provisional Classification" calculated values and make a new Provisional Classification, click the Save button below.

Could you implement the following text changes?

![image](https://cloud.githubusercontent.com/assets/11320314/10200745/f75164e8-675c-11e5-87b5-e333fe025f50.png)

**Comment by kgliu0101** [comment]
@selinad Have a look
![summary](https://cloud.githubusercontent.com/assets/9206696/10201989/9d7c6a60-6763-11e5-928d-453b158e593f.png)

**Comment by selinad** [comment]
Great!  Thanks, @kgliu0101 

2 things (both on me):
* Note - change to:
The calculated values below are based on the set of saved evidence that exists when the "Generate New Summary" is clicked. To save these values as the "Current Summary & Provisional Classification" calculated values and make any changes to the Provisional Classification, you must click the Save button below.
* Under Proband score, can you make "Proband from Families" and "Proband from Individuals" have Proband in the plural form?

Also, are you requiring a reason if they change the Provisional Score, or did we decide we could not implement that?

Thanks!

**Comment by kgliu0101** [comment]
changed Note and Proband(s)
![summary](https://cloud.githubusercontent.com/assets/9206696/10206193/81df0706-677a-11e5-8323-ca5d4c7301d3.png)

**Comment by kgliu0101** [comment]
change "Proband(s) from Families" to "Number of proband ..."
![summary](https://cloud.githubusercontent.com/assets/9206696/10206302/03980d7e-677b-11e5-9f21-a3af8b0449df.png)

**Comment by selinad** [comment]
Thanks @kgliu0101 - let's use the 2nd one.

Change the text under Proband Score to be:
Number of probands with variants assessed as "supports" pathogenicity

**Comment by kgliu0101** [comment]
Changed. But it's pretty long and hard to stay as one line
![summary](https://cloud.githubusercontent.com/assets/9206696/10207000/b8fb8bac-677e-11e5-856f-8d4d9f377dfa.png)

**Comment by selinad** [comment]
Great!  The "16" is still floating inbetwen - can it be on the same line as "Number of probands....supports"?

Thanks!
Selina

**Comment by kgliu0101** [comment]
"16" at top line
![summary](https://cloud.githubusercontent.com/assets/9206696/10207479/622d6018-6781-11e5-83a7-92d5ebd14a49.png)

**Comment by selinad** [comment]
Excellent!  Thanks for your hard work on this, @kgliu0101

**Comment by kgliu0101** [comment]
I made one if you need it.

[cid:18867b98-4d8f-4f5a-a2da-6f89a271b8d8]


________________________________

**Comment by kgliu0101** [comment]
this one.

[cid:3938f211-bcac-4354-9486-34b39f5e42e8]


________________________________

**Comment by selinad** [comment]
Thanks @kgliu0101 - I can't see it...?

**Comment by kgliu0101** [comment]
this one
![summary](https://cloud.githubusercontent.com/assets/9206696/10260169/b66a291c-6926-11e5-9cf3-b0b00eeb10a7.png)

**Comment by kgliu0101** [comment]
change to Definitive
![summary](https://cloud.githubusercontent.com/assets/9206696/10260291/b70285e8-6928-11e5-8269-3919d96f9f6c.png)

**Comment by kgliu0101** [comment]
should be this one
![summary](https://cloud.githubusercontent.com/assets/9206696/10260311/02936856-6929-11e5-82fc-a82f11146038.png)

**Comment by selinad** [comment]
Thank you @kgliu0101 - that looks perfect!

**Comment by selinad** [comment]
Hi Kang,

I don't have time for thorough testing by any means - @tsneddon can test more thoroughly on Monday. A couple of quick things:
* Generate Summary page did not appear after 2 families and 1 Individual proband added.  When I added Experimental it appeared.
* The first variant I entered (11111) I was never able to assess - it did not save any of the information even after hitting save - no sticky appeared on the button either.  This is the one associated with experimental, if that gives a clue.
* I had a proband (not in a a family) with 2 variants (22222 and 33333) and did not get a count for it
* I am not getting a score for an Individual proband with 1 variant with supports as pathogenicity....
* Added experimental to variant 44444 AFTER had already assessed on it for individual and assessment was erased (see second item - seems to be a problem with experimental and assessment, maybe because you aren't counting experimental towards variant count?)
* Double check when header with variants is supposed to show - it did not show on experimental submit page
* Tried to hit Save on a Generate Summary with an experimental count (since probands weren't counting) and I got this error: Cannot read property 'length' of undefined
<img width="1222" alt="screen shot 2015-10-03 at 8 46 58 am" src="https://cloud.githubusercontent.com/assets/11320314/10263673/61c19758-69ab-11e5-9774-437283bdc9f1.png">
* Here is the URL for my GDM: https://90-kl-summary-and-provisional-c326264-kangliu.demo.clinicalgenome.org/curation-central/?gdm=25b7c65b-5af3-41a2-a98e-465bd8623e91&pmid=123

Sorry I can't test any more before I go!  Thanks for your hard work putting up the instance on a Friday night.

**Comment by tsneddon** [comment]
Yes, there seems to be issues with generating a summary.
One I can add is that I can assess on a variant without selecting any of the drop-downs.
However, when I make a summary all the scores are zero.
I only get the correct score if I select one of the drop-downs from 'Evaluation of Pathogenicity'.
If this is required it should be stated in the Edit Variant Information view and a user should not be able to make an assessment without selecting one of the drop-downs or putting some text in the comments box.
This is the GDM in progress: https://90-kl-summary-and-provisional-c326264-kangliu.demo.clinicalgenome.org/curation-central/?gdm=3e144866-16d9-11e5-b451-60f81dc5b05a
Let me know when this and Selina's issues are fixed and I will review the new instance.

**Comment by kgliu0101** [comment]
@tsneddon and @selinad, currently, pathogenicity of one variant in a gdm is shared in all curators. And each curator assesses to the variant pathogenicity. That is different to the mechanism that each curator makes his/her own pathogenicity and assesses to it only (can not assess other's). Please let me know which one you prefer and I will edit relevant code.

**Comment by tsneddon** [comment]
@kgliu0101 I'm a little confused by your last message. Please clarify what the current situation is and what alternative you are proposing.

**Comment by tsneddon** [comment]
Another comment:
I added Exp 1 to the following instance and saved as 'Supports':
https://90-kl-summary-and-provisional-c326264-kangliu.demo.clinicalgenome.org/curation-central/?gdm=3e144866-16d9-11e5-b451-60f81dc5b05a&pmid=2345676
I also added variationID:177872 but I can NOT save any information including an assessment on this variant.

**Comment by forresttanaka** [comment]
> I also added variationID:177872 but I can NOT save any information including an assessment on this variant.

Traced this to an object not being embedded, so there will have to be a change to ```__init__.py```. I’ll work on that first thing this morning in a new branch.

**Comment by forresttanaka** [comment]
I just noticed the [90_kl_summary_and_provisional](https://github.com/ClinGen/clincoded/tree/90_kl_summary_and_provisional) branch is 82 commits behind dev. I’ve made embedding changes (including for this exact problem) in recent dev merges, so I think we can assume for now that I fixed this problem already.

**Comment by tsneddon** [comment]
Thanks @forresttanaka, so I can continue to assess on this instance?:
https://90-kl-summary-and-provisional-c326264-kangliu.demo.clinicalgenome.org/

**Comment by kilodalton** [comment]
@kgliu0101 Your branch should be updated and a new instance brought up.

@tsneddon I would recommend that you not continue to test on this instance until the the code base behind it (on a new instance) is brought up to date.

**Comment by forresttanaka** [comment]
@tsneddon I can only address assessing variants, and I worked on that towards the end of last week, probably within the 82-commit window. So how much assessing variants proves on this instance, I’m not clear.

**Comment by selinad** [comment]
Please move these comments if they should be somewhere else (I've lost track from afar):

Here's what I tried in order, generated summary, and it worked!:
* Add proband with variant 11111 from Family from PMID1 - works
* Add proband with variant 11111 from Individual from PMID1 - works
* Add proband with variant 11111 from Individual from PMID2 - works
* Add proband with variant 22222 from Individual from PMID1 - works
* Add Exp B experimental (with variant 22222) - works

What did not work:
* Add Models experimental (with variant 22222) - score not added for Models

Features:
* Could we blank out Generate Summary button on Summary page since it does not work (or make it work even though same page generated)
* We need to return # pieces clinical and experimental contradictory evidence (I think OK for the production version, not necessary for beta @tsneddon ?)

**Comment by selinad** [comment]
Experimental Count is showing but not Experimental Score
<img width="785" alt="screen shot 2015-10-06 at 9 55 50 am" src="https://cloud.githubusercontent.com/assets/11320314/10315675/89444e58-6c10-11e5-832b-cc11540528c6.png">

**Comment by kgliu0101** [comment]
I can see "Final Experimental Score" 3. If you mean no score for each experimental evidence (Expression, Biochemical Function, Model System), that is what we decided last week. Since Final Experimental Score is range-based but not directly equal to sum of each evidence score, we decided not showing them.

**Comment by selinad** [comment]
Hmm...I vaguely remember this, but not necessarily for experimental. Fine for beta and we can discuss again.

**Comment by selinad** [comment]
@kgliu0101 I have to stop testing now, but I think the scoring is all working well!!!

**Comment by tsneddon** [comment]
@selinad - I think we are OK not including the # of pieces of contradictory evidence for this initial release but it should be a priority for the next 3-week release. I will start testing now...

**Comment by tsneddon** [comment]
Initial comments:

1. On Edit Individual Information there is a field "Shared Phenotype(s) (free text):". This should just be "Phenotype(s) (free text):". It is correct on the View Individual page.

2. Not for this release but it would be useful to have a Summary View, especially if it was done by a different curator e.g. this record was created by me. Only Selina has added a PMID. The record evidence is empty in my view but the status is "Summary/Provisional Classifications" - is this a feature or a bug? @selinad have you previously assessed on this record?:
https://90-kl-summary-and-provisional-fa45a47-kangliu.demo.clinicalgenome.org/curation-central/?gdm=fae4c241-7417-4a29-9453-f1ecac8c96cc&pmid=21217753

3. I can't save an assessment on this Experimental piece of evidence:
https://90-kl-summary-and-provisional-fa45a47-kangliu.demo.clinicalgenome.org/experimental-curation/?editsc&gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a&evidence=bb3432ca-1788-11e5-aefb-60f81dc5b05a&experimental=6be668d4-2a6e-11e5-804a-60f81dc5b05a

4. @selinad - Experimental Rescue count works for me - with and without an associated/assessed variant. However, a previous Experimental piece of Protein Interaction data was previously assessed by me as supports but it is not included in the summary score:
https://90-kl-summary-and-provisional-fa45a47-kangliu.demo.clinicalgenome.org/experimental/72341d2e-2a6e-11e5-bdd7-60f81dc5b05a/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a

5. I have set this family segregation as Reviewed:
https://90-kl-summary-and-provisional-fa45a47-kangliu.demo.clinicalgenome.org/families/e659bd3a-18f8-11e5-9d3a-60f81dc5b05a/?gdm=9ffd7c1e-16d9-11e5-b283-60f81dc5b05a
This is the only family associated I have with an assessed variant. However, I am still getting a proband count. Why is this?

...still testing...

**Comment by mrmin123** [comment]
@tsneddon Regarding item 3... do you get an error message in the console (command+option+i in Chrome) when you try to set an assessment?

**Comment by kgliu0101** [comment]
@tsneddon
Item 1. I changed tile of field "Shared Phenotype(s) (free text):" to "Phenotype(s) (free text):".
Item 2. GDM status is currently set as "Summary/Provisional Classifications" if there is a summary generated, no who did it. Is it necessary to set the status per user?

**Comment by kgliu0101** [comment]
other items are related to test data in gdm 9ffd7c1e-16d9-11e5-b283-60f81dc5b05a. Some of them may missing required item because of schema change. I suggest starting from a new gdm for testing.

**Comment by tsneddon** [comment]
@mrmin123 - no error, just nothing happens when I click on save.

**Comment by tsneddon** [comment]
@kgliu0101 - re: #2, I don't see a summary and there is no evidence added so I don't think Selina could have made a summary. Why then is Status: Summary/Provisional Classifications and not Status: In progress?

**Comment by kgliu0101** [comment]
@tsneddon gdm fae4c241-7417-4a29-9453-f1ecac8c96cc has a provisional object already. Go to url https://90-kl-summary-and-provisional-fa45a47-kangliu.demo.clinicalgenome.org/gdm/fae4c241-7417-4a29-9453-f1ecac8c96cc to see all data included in the gdm. This provisional is owned by Kang Liu, that is why you can not see it, but the gdm status is Summary/Provisional Classification.

**Comment by tsneddon** [comment]
@kgliu0101 - I'm still confused by the "SMAD3 – Aneurysm - osteoarthritis syndrome Autosomal dominant inheritance" GDM. I created the record, Selina added PMID: 21217753. You are not listed as a participant so I do not understand how you made the Status: Summary/Provisional Classification. Is this just an issue with old data and should I just move on and test new data?

**Comment by kgliu0101** [comment]
The provisional was created for developing and testing without any evidence. The list of curators are generated from owners of evidence, variant, pathogenicity and assessment. Then, Kang Liu is not in participant list. Such test data will be deleted after testing.

**Comment by tsneddon** [comment]
OK, I'm testing with all new data now so hopefully I'll stop reporting bugs due to old data!

**Comment by mrmin123** [comment]
Apologies for jumping in but @tsneddon and I resolved item 3 in a previous comment:
>  can't save an assessment on Experimental piece of evidence:

It was because that piece of Experimental data was created before that experimental data type (Biochemical Function subtype A) were not allowed to have variants involved with them. The test data does have a variant associated with it, so the form burps when trying to deal with it. It shouldn't happen on newly-created data created via the form.

**Comment by tsneddon** [comment]
Re: https://90-kl-summary-and-provisional-77def9e-kangliu.demo.clinicalgenome.org/curation-central/?gdm=d7aad1bd-1c4a-40c2-b8a5-83af3a34e4ad

The current summary score is 5.5 (Limited) which is correct, with the 0.5 coming from Biochemical Function.
However, I just added an Experimental Protein Interactions piece of evidence and if I go to generate summary it says the score will be 7, with an extra 1.5 points coming from Experimental:

Protein Interactions	4	 
Biochemical Function	1	 
Final Experimental Score	 	2

If the single Protein Interactions piece of evidence is not assessed or set to review or contradictory the sub-score is 3, Final Experimental Score = 2.

There should only be another 0.5 points coming from Experimental for the Assessed=Supports piece of Protein Interactions evidence. A total of 1 point from Experimental for a total score of 6.

**Comment by kgliu0101** [comment]
@tsneddon Don't change the gdm. I'm going to check.

**Comment by tsneddon** [comment]
OK, thanks @kgliu0101, I'm working on a new GDM right now...

**Comment by kgliu0101** [comment]
By going through annotations, I get 4 pathogenicity objects, all assessed as Supports. 2 families each associated with 2 variants. 2 experimental objects assessed as Supports, 1 Biochemical Function (Complex Exp) and 1 Protein Interactions (FANC). 3 experimental objects assessed as Not assessed. After assessing these evidence, I get a summary:
![summary](https://cloud.githubusercontent.com/assets/9206696/10326558/9425dc6a-6c51-11e5-8c9d-781ae019d2db.png)

Manually counting as: 1 Biochemical Function = 0.5, 1 Protein Interactions = 0.5, ranges Final Experimental Score to 1; 2 pieces of proband range Proband Score to 1; 2 articles range Publication Score to 2; earlier article published in 2005, that ranges Time Score to 2. All scores correct.

**Comment by kgliu0101** [comment]
then, I change the assessment of experimental FANC to Review, and make a new calculation.
![summary](https://cloud.githubusercontent.com/assets/9206696/10326827/811eb7ec-6c54-11e5-9804-c36ea4fca889.png)

**Comment by kgliu0101** [comment]
then, change the assessment back to Supports.
![summary](https://cloud.githubusercontent.com/assets/9206696/10326864/0b00f394-6c55-11e5-9211-eb0d0a19fd7f.png)

**Comment by tsneddon** [comment]
Hmmm...this is not what I see.
If I go to the record now without changing anything and click on Generate New Summary, I still get a count of 4 for Protein Interactions:

![screen shot 2015-10-06 at 6 08 05 pm](https://cloud.githubusercontent.com/assets/7256012/10326907/a7f0aa50-6c55-11e5-9823-ca198227b6be.png)

**Comment by kgliu0101** [comment]
@tsneddon It's very interesting that I found 4 FANC (Protein Interactions) objects you created today. One of them belongs to the gdm above. Other 3 do not belong to any gdm. They all are assessed as Supports by you. Their assessments link to the same gdm. That is reason you get 4 pieces of Protein Interactions.
<img width="1160" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/10327596/f0bca240-6c5d-11e5-8f2d-2198e0a5465c.png">

**Comment by tsneddon** [comment]
Weird, that obviously shouldn't be happening! Let me know when you figure it out or if you need me to try and recreate the bug.

**Comment by selinad** [comment]
How do you get experimental data not attached to a GDM?

**Comment by selinad** [comment]
Hi @kgliu0101 

This gave me a count of 3 probands when I only have a supports for 111111 (no assessment for 222222) - seems it should be 2? 

<img width="259" alt="screen shot 2015-10-07 at 7 38 05 pm" src="https://cloud.githubusercontent.com/assets/11320314/10356357/3578f096-6d2b-11e5-8d65-f953692ea739.png">

When I assess 222222 as correct, I get 5 (adding 2 would be correct).

**Comment by selinad** [comment]
If I have previously set the classification as Moderate (when calculated as limited) and then generate again, the pull-down says limited, so a save saves as limited - could the pull-down be the same as the current classification instead (moderate)?

**Comment by selinad** [comment]
I haven't found anything else under the first comment with the image that is scoring incorrectly.  

@tsneddon did you happen to test a recessive example?  It seems to work for a proband from a Family. However, if I enter 2 variants for an Individual (not part of a family) and assess one as supports but not the other, it adds a proband.  If I then assess the 2nd, it doesn't - for an Individual, when 2 variants are added, I think we should make it so they have to assess on both to get a +1? ( @tsneddon do you agree? - we will probably have to make this clearer on the interface at some point)

Also, if you want to add to my GDM and test, it is here:
https://90-kl-summary-and-provisional-77def9e-kangliu.demo.clinicalgenome.org/curation-central/?gdm=80a1372b-6528-4544-bb11-079f39426b07

**Comment by kgliu0101** [comment]
@selinad In gdm 80a1372b-6528-4544-bb11-079f39426b07, I found 2 families (fam-group-test, fam2) and 1 independent individual (ind-noprob) associated with variant 11111. Proband counting for this variant should be 3. After assessed variant 11111 as Supports, I got a proband count 3.
<img width="1152" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/10357624/0ceeed02-6d39-11e5-9871-f453b77fda6e.png">

variant 22222 is associated to fam3 (family), ind-prob (independent individual) and prob-ind1 (independent individual), Proband counting for this variant should be 3. I got 3 more after assessing Supports to the variant.
<img width="1161" alt="summary" src="https://cloud.githubusercontent.com/assets/9206696/10357739/7b7df348-6d3a-11e5-88ac-fd69262d53db.png">

They are all correct.

**Comment by kgliu0101** [comment]
No sure your pull-down value question. Try to answer here. The default value of pull-dow is set as same as calculated classification at each time you run summary. if you select other value but not save and then click the Generate button again, your selection will be lost, all values will be re-calculated and re-set to default again. The only way let page remember your selection is save it.

**Comment by selinad** [comment]
@kgliu0101 The non-family individual named "ind-noprob" is NOT a proband, so should not be counted. You can see there is no little red icon next to it.

(the 2nd part about 222222 was just to show that that part worked correctly - there was no problem there - sorry if that was confusing).

**Comment by selinad** [comment]
Re pull-down; we can address in next version - it does not behaving incorrectly per se, but I could also see it being confusing.

**Comment by kgliu0101** [comment]
@selinad "ind-noprob" does not belong to any family, but is a single individual. Still no count?

**Comment by selinad** [comment]
No count unless user selects proband. We only count probands. There is a choice for this on individual page when not coming from family.

**Comment by kgliu0101** [comment]
OK. I'm going to edit the code.

**Comment by selinad** [comment]
I feel like I tested that before and it was good, but possibly not. Thx Kang.

**Comment by kilodalton** [comment]
Two observations:

--typo --> "Selecte Provisional Clinical Validity Classification:"

--button size --> "Generate Summary" button should be sized similar to other buttons throughout site  (i.e.  it should not be "btn-xs") and probably vertically centered in that space....the summary is is one of the value propositions of the site and therefore should a size matching other buttons throughout the site.

**Comment by selinad** [comment]
Thanks @kilodalton - that button was bothering me in my subconscious - appreciate you bringing it up.  I agree it should be the same style as the other blue buttons.

@kgliu0101 thanks for working on the fixes.

**Comment by tsneddon** [comment]
@selinad - I have a couple recessive examples. Is the rule about counting probands in a recessive GDM due to the field in Family "If more than 1 variant, is proband associated with both - yes" or is it calculated from the GDM inheritance itself? I can get a proband not associated with a family counted with 1 assessed variant in a recessive GDM.

**Comment by kgliu0101** [comment]
@tsneddon and @selinad Right new, we don't have any thing to mark associated variants are recessive or not. To determine a multi-variant-associated individual as a proband, must all associated variants be assessed as support or one of them is enough?

**Comment by selinad** [comment]
@kgliu0101 It would make sense for a curator who generates a Summary to return to the same page after they hit Save from which they came....not sure if easy/hard for beta.  Right now, it seems like one always goes to the GDM page with no selected paper?

**Comment by selinad** [comment]
Hi @kgliu0101 - the summary Matrix says Limited starts at 2, but a score of "0" is returning Limited.  

After speaking with ER and NS, here is what we need to do:

Allow Generate New Summary button to appear only after first variant associated with proband has been assessed (Experimental assessed as support cannot trigger this) and there is a proband count of 1.

So, when I have a recessive (2 variants) and I assess supports on only 1 of those variants, proband does not =1, so Generate New Summary should not appear.

If there is a way to have "No Reported Evidence" appear on header before Generate New Summary button appears and a new classification has been saved, that would be ideal....

**Comment by tsneddon** [comment]
To quote from the GCWG paper being reviewed for submission:

"
![image](https://cloud.githubusercontent.com/assets/7256012/10464091/d9424f22-719c-11e5-8092-aa1c32e19381.png)"

**Comment by selinad** [comment]
Hi @kgliu0101 

Overall, it's working beautifully!  All the scores came out as expected. 

One request if trivial:

* The Save button on the Summary page gets lost - I am worried people won't see - could we also put it up higher?

**Comment by selinad** [comment]
Score looks correct on all these actions:
![image](https://cloud.githubusercontent.com/assets/11320314/10495515/2c6a1962-7271-11e5-8b61-c43281446598.png)

**Comment by kgliu0101** [comment]
Very great test. Thanks lot Selina

**Comment by selinad** [comment]
Logged in as different user - seems to work great!

Assessed on others info and on new info added:
![image](https://cloud.githubusercontent.com/assets/11320314/10497346/266dc834-727a-11e5-8770-386b2a733183.png)

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
