### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#95]
it's in the specs:

Page 2 of this file:
ClinGen interface 4 version0.5 only v12 062315.pptx 
Found on ClinGen Resources page of Staff wiki.

The Dashboard is where a user lands once they have logged in.
<img width="798" alt="dashboard_screencapture" src="https://cloud.githubusercontent.com/assets/11320314/8730833/4410910a-2ba8-11e5-8eca-7cd8c489dff7.png">

**Comment by kilodalton** [comment]
From PR #106:
http://localhost:6543/dashboard/
![image](https://cloud.githubusercontent.com/assets/4326866/8785389/3d9be4d2-2edc-11e5-99c2-66a491549d8c.png)

**Comment by selinad** [comment]
Looks good, Min!  Super!

Does GDM:DICER1:Achondroplasia mean Create that record?  If so, we may just want to say:

Create DICER1-Achondroplasia-moi

(where moi = mode of inheritance, e.g. autosomal recessive).

I believe we are using hyphens instead of colons for the GDM, is that correct? 

We may want to be explicit about the status of a GDM under 'Your Gene-Disease records" (btw, Diseases in this title should be changed to singular Disease) - I will add suggestion after my meeting.

**Comment by mrmin123** [comment]
Thanks Selina. To clarify, the GDM:Dicer1:Achondroplasia link under 'Recent history' does not create a record. They are just links to items that the logged-in user is set as the 'owner' to. In the screenshot I added a random PMID to the Dicer1:Achondroplasia GDM I created and that activity/item shows up under Recent history as well.

**Comment by selinad** [comment]
Hi Min - thanks - yes, I was thinking of it this way (as history). I see now that you were trying to express that it was modified, but I was thinking that you were trying to show it was created (sorry, I was in a bit of a hurry to get to my meeting).

Where would the link for the PMID annotation go?  Should it say 'created' rather than 'modified' there?  Or, PMID:NNN... (added to GDM?).  Kang probably has some examples from Spindle and we could discuss wording.

thx!
Selina

**Comment by selinad** [comment]
Looking great, @mrmin123!  This is a great feature for curators to have when the log in.
Just a few text changes:
* Change "View/create gene-disease record" -> "Create Gene-Disease Record" (since they can view in a few other ways)
* Change "View list of gene-disease records" -> "View list of Gene-Disease Records"
* Change create item under Recent History to read like this: "DICER1-Pleuropulmonary blastoma (*autosomal dominant inheritance with maternal imprinting*) - i.e. remove HP term and italicize the mode of inheritance term. Also, remove parentheses from "created 2015 March..." and italicize this: *created 2015 March....*"
* Same changes to formatting for GDM name under Your Gene-Disease Records
* Status - can we call this something else?  If so, I will think of a name.  Something like "In process" 

Hopefully these are all very simple text changes, but please let me know if otherwise - it's good for 0.5 as is (except for first item, which if more functional and would be great to change).  

Thanks! - S

**Comment by kilodalton** [comment]
Additional item to be fixed:
--After you have added a PMID to a GDM it is shown as a link on the dashboard, however when you click on that link from the dashboard, even though it has the PMID in the URL the PMID is not selected (e.g. highlighted on left  and abstract showing in center area) when you go to that page. The URL that it takes you to does show the proper article highlighted if you manually refresh the page.

**Comment by mrmin123** [comment]
@selinad the changes will be made in the next push.
@kilodalton that bug is more related to the curator-central page, so I've made a separate ticket for it as #118

**Comment by selinad** [comment]
For alpha1, can we please gray out the "View list of all Gene-Disease Records" link as it takes one to an internal table?

**Comment by mrmin123** [comment]
Yes, we can remove the link. Should I completely get rid of the text as well, or would you like to have it stay as a placeholder?

**Comment by selinad** [comment]
Staying as a placeholder for now would be good - thanks!

**Comment by kilodalton** [comment]
Great job. Thanks for all your hard work to get the app to production!
