### ISSUE TITLE
Add ability to bring PMID into VCI & add associated text

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#954]
Under certain sections (to be specified in #952 and #953 ), add ability to "Add PMID" as we do in GCI and return the citation information for this PMID.  Additionally, to provide text box that allows a curator to enter information that will be associated with that PMID and Experimental or Segregation/Case information.  

At a later date, we will capture this information in more discrete ways, overlapping with GCI capture of this information wherever possible (the VCI evidence will likely be a subset of the evidence captured in the GCI for both of these).  

If possible, it would be nice to define the Evidence type for experimental evidence as we do for GCI; however, we can include this functionality at a later date.

**Comment by mrmin123** [comment]
@selinad Instance here: http://954-mc-vci-pmid-782f115-minchoi.instance.clinicalgenome.org/

Per our discussion I've 'designed' the UI components like so:

'PubMed Evidence' table (using 'Experimental Studies' subsection of the 'Experimental' tab as an example):
![image](https://cloud.githubusercontent.com/assets/4326866/18583896/501950fc-7bc2-11e6-8da1-ee8601db3f50.png)

Clicking the 'Add PMID' button brings up the modal which behaves as expected:
![image](https://cloud.githubusercontent.com/assets/4326866/18583921/7a2b1092-7bc2-11e6-8455-b55d83db6a2f.png)

Clicking through from the modal updates the main form, adding a citation of the chosen article and a description box and save button. The user can also click the 'Edit PMID' button at this stage to change the article being added.
![image](https://cloud.githubusercontent.com/assets/4326866/18583954/a6aac126-7bc2-11e6-8f48-6842edeec1cb.png)

Hitting Save from here creates the necessary database objects and updates the interpretation. The entry is now shown in a table format, which the user can Edit or Remove a previous entry:
![image](https://cloud.githubusercontent.com/assets/4326866/18583978/d2294926-7bc2-11e6-93af-bb066924a5b6.png)

You can only edit the description.
![image](https://cloud.githubusercontent.com/assets/4326866/18583994/e8c7590c-7bc2-11e6-9b0e-d9477b1239ad.png)

Table w/ more entries added:
![image](https://cloud.githubusercontent.com/assets/4326866/18584016/0c61f9bc-7bc3-11e6-83a8-4cfef426ee84.png)


For testing purposes I've also added in these tables to the 'Observed-in-healthy-adults' and 'Case-control' subsections of the 'Segregation/Case' tab:
![image](https://cloud.githubusercontent.com/assets/4326866/18584039/3abc3296-7bc3-11e6-9ca8-1534fbac5c4a.png)

Demo screencap showing separate sets of article/descriptions for two different sets of articles on the same page:
![image](https://cloud.githubusercontent.com/assets/4326866/18584068/61cac9f6-7bc3-11e6-867e-f766ced4d43b.png)


Still needs work:

* Better styling of Description text labels and boxes
* Save button needs to be disabled when Description box is empty
* Cancel button after retrieving PMID information the first time
* Better locations for Save, Cancel, Add/Edit PMID buttons
* Button colors on Edit are weird
* Collision detection required so that the user does not add the same PMID twice... or maybe we need the ability to add the same PMID twice?
* When Removing, set the status of the extra evidence objects as being deleted

**Comment by selinad** [comment]
Hi @mrmin123 I'm just about to test and may run out of time to get through it before a call at the top of the hour, but need to send a note to say this design in phenomenal!  Thank you so much for all of your thought and hard work on this.

**Comment by selinad** [comment]
@mrmin123 - absolutely awesome!

A couple of super quick things, mostly small, from my 7 minutes of testing that don't do your hard work justice:

- Quick thought - let's change "Description" to "Evidence"
- color of edit button for PMID - should we have it same color as other Edit buttons?
- can add same pmid within a table and type in description, but does not save description
- First time I hit "Remove," it did not delete entry, but did on second try (happened twice so not certain it's me)
- Should we say "Delete" instead of "Remove?"

**Comment by mrmin123** [comment]
@selinad 
Fixed most, if not all, of the issues outlined by both of us.

* Description -> Evidence
* Remove -> Delete
* Colors of buttons unified
* Table headers do not appear when table is empty
* Added ability to Cancel out from Adding PMID
* Save buttons are disabled when description boxes are empty
* Better button locations
* Added collision detection so that the same PMID cannot be added twice to the same group
![image](https://cloud.githubusercontent.com/assets/4326866/18597810/8cd9c782-7c04-11e6-98e4-f243acf03de6.png)

I could not reproduce the Delete not working the first time...

Still need to make it so that the evidence objects are set to status deleted when Deleting.

**Comment by mrmin123** [comment]
@selinad update instance here: http://954-mc-vci-pmid-95613ed-minchoi.instance.clinicalgenome.org/

Some additional changes:

* Allows for multiple entries of the same PMID
* Wired up to curationHistory, but no change on frontend/dashboard
* Sets status of extra evidence object to `deleted` when Deleting

**Comment by mrmin123** [comment]
@selinad new instance will be here: http://954-mc-vci-pmid-733820b-minchoi.instance.clinicalgenome.org/

Should be ready in 10~20 minutes.

**Comment by selinad** [comment]
Hi @mrmin123 - sorry for the delay.

Looking good!
Thanks for changing it to Evidence and to Delete and unifying buttons.

Still testing, but one problem with the delete button - would not delete:
<img width="1438" alt="screen shot 2016-09-17 at 8 44 25 am" src="https://cloud.githubusercontent.com/assets/11320314/18609286/5b71c78a-7cb3-11e6-9503-3c45cb1ccd50.png">

As a side note, my login failed for my personal address, but the curator.test gmail addressed worked.  I'll try again after doing some more testing

**Comment by selinad** [comment]
I'm a little confused by added collision protection for pmid's stated above - I was able to add the same pmid twice (which I think is a good thing).

However, when I went to edit 1 of the 2 pieces of evidence associated with the same pmid, both evidences became editable instead of just the one:
<img width="1086" alt="screen shot 2016-09-17 at 8 48 26 am" src="https://cloud.githubusercontent.com/assets/11320314/18609322/3c991e3e-7cb4-11e6-9846-3bcd39b5f31a.png">

Both buttons show that they will edit.  However, the edit remains specific to the piece of evidence (which is good) - meaning, if I edit in one box and save in the other, it won't save changes (hope that makes sense).

**Comment by selinad** [comment]
@mrmin123 I'd think it might be good to add a little note in an empty table if that would be a reasonable request right now.  
<img width="1071" alt="screen shot 2016-09-17 at 8 59 28 am" src="https://cloud.githubusercontent.com/assets/11320314/18609356/15c8ec16-7cb5-11e6-8740-ea3839c04236.png">

2 suggestions:
- change table name to "Curated Literature Evidence" (we may be adding more than PMIDs at some point
- add a note in an empty table (this could even go in an empty row below an entry): "_Select "Add PMID" to curate and save a piece of evidence from a published article._"

**Comment by selinad** [comment]
should the Edit button here be a blue for consistency?
<img width="1058" alt="screen shot 2016-09-17 at 9 08 03 am" src="https://cloud.githubusercontent.com/assets/11320314/18609421/4d72c398-7cb6-11e6-84c7-79c652ce54f8.png">

**Comment by selinad** [comment]
For some reason, the "Edit PMID" looks inactive even when active - it may be me, but is it the same color as active blue buttons (w/o mouse-over)? It could just be the juxtaposition with the grayed out "Save" button:
<img width="1062" alt="screen shot 2016-09-17 at 9 17 31 am" src="https://cloud.githubusercontent.com/assets/11320314/18609472/c145f4e2-7cb7-11e6-9236-8e78e7eced8a.png">

**Comment by selinad** [comment]
@mrmin123 -  aside from the Delete button and the Edit functionality where 2 pieces of evidence with same pmid become editable when one is picked, this looks FANTASTIC!  It works on both tabs and in all sections.  Superb work!

One thought, but could easily be moved to next release.  If we change title to "Curated Literature Evidence" for a table, maybe the section name could go in parentheses behind - e.g. Curated "Literature Evidence (_de novo_ occurrence)" - I think this could help orient users within a page as it is necessarily vertical, especially on the case page.

Thank you!!!

**Comment by mrmin123** [comment]
@selinad sorry for the late response! Was out all morning.

I have an instance going up at http://954-mc-vci-pmid-64d30d9-minchoi.instance.clinicalgenome.org/ and it should be ready in about 20 minutes.

It'll include these changes:

* Fixed Edit button so it only opens up the Edit interface for one evidence line, even if there are other ones that share the PMID
* Fixed Delete functionality
* Added descriptive table names and note next to Add PMID button:
![image](https://cloud.githubusercontent.com/assets/4326866/18612253/f2e7cb90-7d09-11e6-8f72-c62a58355eba.png)
* Modifier positioning of Add PMID button (see above screenshot) and Edit PMID button. Hopefully this makes the light-blue button color of the Edit button look less jarring:
![image](https://cloud.githubusercontent.com/assets/4326866/18612258/0f098a98-7d0a-11e6-91d5-f00ea2022b0a.png)

**Comment by mrmin123** [comment]
@selinad the Edit button color was also changed:

![image](https://cloud.githubusercontent.com/assets/4326866/18612277/57185f76-7d0a-11e6-8344-060926b625f1.png)

**Comment by selinad** [comment]
@mrmin123 - thanks!  

Everything looks fantastic - edit button functionality and color, delete button works, descriptive table names, new position of PMID works.  Looks good to go!

Thanks for all the hard work!

**Comment by selinad** [comment]
@mrmin123 I did forget to mention one thing.  When I hit Delete, the delete functionality works properly, but all Delete buttons seem to respond for a second (although only correct entry is deleted).  Not a major deal, but in case it's a quick fix.  They all gray out at the same time and then only the entry for the one selected disappears.

**Comment by mrmin123** [comment]
@selinad the Delete function behavior, in its current implementation, is not a quick fix. One way to work around it, however, is to move the location of the Delete button so that instead of it showing up on the main table, we can move it to the Edit view. Perhaps this is the right way to do it in the first place? We can make the [Edit] [Delete] buttons into [Edit/Delete], and one that button is pressed, you'll see the Edit form with the buttons [Edit] [Delete] [Cancel Edit]. Do you think that would be better?

**Comment by selinad** [comment]
Hi @mrmin123 thx for the suggestion.  I think we should do it in a manner that's consistent with the rest of the site, which I believe would not be an [Edit/Delete] button?  (In general, we should have some sort of site review at some point that checks for consistency of user experience).  If this is the case, I'd just leave it for now - it's completely functional.  We can polish in next round - let me know if that makes sense and if you agree it's current implementation is in keeping with the rest of the site.  If so, I can make a ticket for R8 about the delete button behavior or about buttons site-wide.

Thanks!
Selina

**Comment by mrmin123** [comment]
@selinad OK. Let's revisit that in the future then. I'll create a PR for the ticket as-is. Thanks!

**Comment by kilodalton** [comment]
[pls ignore: comment added only to refresh PR display on waffle]

**Comment by selinad** [comment]
@mrmin123 - was working great (love this feature!) until I tried to delete:
<img width="1436" alt="screen shot 2016-09-29 at 10 30 45 pm" src="https://cloud.githubusercontent.com/assets/11320314/18981604/b3c716a2-8694-11e6-96d3-c7fdb1fa23d2.png">

**Comment by wrightmw** [comment]
The delete issue has been dealt with already.... great work @mrmin123 .... the functionality looks great. I worried that long titles might add a lot of vertical space, but even the article with the longest title I came across (PMID:3029678) looked ok.

**Comment by selinad** [comment]
@mrmin123 thx for the fix!  Is there a way for us to test?

**Comment by wrightmw** [comment]
This works well for me now. I can delete. Thanks for the fix @mrmin123

**Comment by kilodalton** [comment]
Included in the last release (R7). This included the Variant Curation Interface. Nice job and thanks for your hard work.
